### ISSUE TITLE
Error from backend being displayed twice

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#1002]
**Describe the bug**
The frontend is displaying the backend error message in two different components.

**To Reproduce**
1. On the add user permission page fill all the info;
2. Simulate a backend error;
3. Click on 'Submit Application' button;
4. See the error

**Expected behavior**
It should only display the error message on the Notification component.

**Screenshots**
![screenshot](https://github.com/bcgov/nr-forests-access-management/assets/117364634/ce86bc8f-f444-47ba-9841-a9fbf8f0803a)

**Comment by OlgaLiber2** [comment]
test to see if this is still an issue @MCatherine1994 @NickSaglioni

**Comment by MCatherine1994** [comment]
Not seeing duplicate error messages anymore, but found the message content error, this need to be fixed

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e810c6852fab2c42a64c421e8709233de5c8a43/Screen%20Shot%202024-01-12%20at%203.41.35%20PM.png" alt="Screen Shot 2024-01-12 at 3.41.35 PM.png" />

**Comment by ianliuwk1019** [comment]
> Not seeing duplicate error messages anymore, but found the message content error, this need to be fixed
> 
> ![Image](https://private-user-images.githubusercontent.com/23131735/296906273-2b220555-4633-4c32-a8d9-a66c16d3ddc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzkxNDcsIm5iZiI6MTcwNjEzODg0NywicGF0aCI6Ii8yMzEzMTczNS8yOTY5MDYyNzMtMmIyMjA1NTUtNDYzMy00YzMyLWE4ZDktYTY2YzE2ZDNkZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYTM1OTNiZDZiN2FkYWRmYjRjODdkNDMzNzAyMTFmN2ZkYjA2NjI5NzIxMjEyMmFhNDdhMWY3OTViMTJmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XYhQxQQdpPHp3gBW_PCEh_CRjcjymXwdGP5Jxc98i8Y)
> 
> To simulate a backend error, could update the following method as shown in the screenshot:
> 
> ![Image](https://private-user-images.githubusercontent.com/23131735/296906477-baa3e7b1-2526-41bc-9da8-cbc4e29a7c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzkxNDcsIm5iZiI6MTcwNjEzODg0NywicGF0aCI6Ii8yMzEzMTczNS8yOTY5MDY0NzctYmFhM2U3YjEtMjUyNi00MWJjLTlkYTgtY2JjNGUyOWE3YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDIzMjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNTA3OGQ1ZWFmY2VkNzFmNjRhNzg3YTJjMWI5MmU2YzlhYWY2MDg1MWU3ZmQ3OTYwYWU4MTI3ZDk5YjkxNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UA249jev7hkXjojCarVOZJjLvI-lRooftFfFm94n_Rk)

I think it is probably better to create another ticket and close this one.

**Comment by MCatherine1994** [comment]
okay, I created a new one, close this one
