### ISSUE TITLE
[Design] Walkthrough onboarding

### ISSUE THREAD

**Issue by aliramoss** [bcgov/nr-forests-access-management#1003]
**Describe the task**
Explore and create a new pattern for walkthrough new users, and make it easier to explain our tools and systems.

**Acceptance Criteria**
- [x] Explore best practices, and documentate it.
- [x] Benchmark other tools that created the same experience.
- [x] Create first user flow.
- [x] Prototype the experience.
- [ ] Create button to view walkthrough again
- [ ] Finish documentation

**Comment by gormless87** [comment]
@aliramoss - can you provide and update on this issue? Have any of the AC been met? Perhaps we can meet tomorrow or next week to discuss how the work can be broken out into separate tasks so they can be completed within a single sprint.

**Comment by aliramoss** [comment]
Walkthrough protype in Figma:
https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=3272%3A67804&mode=design&t=WNYkaMqEZkNrsVOI-1

**Comment by aliramoss** [comment]
Walkthrough protype in Figma:
https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=3272%3A67804&mode=design&t=WNYkaMqEZkNrsVOI-1
