### ISSUE TITLE
[Design] Create Application selector for "Add user permission" sidebar shortcut

### ISSUE THREAD

**Issue by aliramoss** [bcgov/nr-forests-access-management#1005]
**Describe the task**
It is necessary to add a way for the user to select an application when clicking in "Add user permission" from the sidebar.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTk5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5de641be2bdbc83179bd7d14db5150a2f7a8bdfb/image.png)

**Acceptance Criteria**
- [ ] Explore best practice to add the interaction
- [ ] Prototype
- [ ] Review with the team

**Comment by OlgaLiber2** [comment]
@aliramoss can you add the figma link to the mockups here please.

**Comment by aliramoss** [comment]
Sure, here's the link:
https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=4153-40524&mode=design&t=3PHaGDbx7TrIz9VB-4
