### ISSUE TITLE
Add the new fam_app_admin table 

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1007]
**Describe the task**

- [x] Add the new fam_app_admin table in PostgreSQL
- [x] Add a new database user in PostgreSQL. For now just give it SELECT privileges on fam_app_admin.
- [ ] ~Try to use SqlACodeGen to see if we can use that tool to generate the python data model~
- [x] Manually map new table in python data model.
- [x] Add the table and attribute description, audit columns (create/update date time, create/update user as other tables)

**Additional context**
- Update the existing model to include this new table, in server/backend folder
- Reference for the last spike ticket for SqlACodeGen tool #474
- Data model design in confluence https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Admin+Segregated+Schema+Design?

**Comment by ianliuwk1019** [comment]
Checked on `sqlacodegen` package for model.py generation, its current release `sqlacodegen==3.0.0rc3` does support `SQLAlchemy` version 2.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHl5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c041584e9dbc43f32cd13ee8f038b1889f7c67d6/image.png)
<br/>
At locally running db, executed command to reverse-generate a model.py from database:
 `sqlacodegen --generator declarative postgresql+psycopg2://postgres:postgres@localhost:5432/fam --schemas app_fam`. It executed pretty fast and it also created quite detail than previous hand-tweak model.py including all the **comments**, **constraints**, **indexes** and **relationships**!!
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW15QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c55c8db0922cb417a266eaa1082ed0c54d205b3/image.png)
<br/>
Using **newly generated SQLAlchemy mode**l with our backend code, it started up smoothly, however, seems it only functions **partially** with our backend code. I noticed from using frontend UI, loading `/fam_applications` (GET) is good , the `/user_role_assignment` (POST) is also good, but loading **`/{application_id}/user_role_assignment`** (GET) has **500** error internally. If I switched to the old version of model.py, then all works.
From the error log, it isn't clear, so not really sure if this is a `SQLAlchemy` version computability with `sqlacodegen` issue or is it our Python code against new model issue...

For now, I will hand write this new table mapping to our `model.py` and create new ticket to investigate `sqlacodegen` generated code to work with our backend.
@MCatherine1994 @basilv @gormless87 
PS: I seem to also notice that using newly generated model, the frontend run faster on requests (but it may just be my wrong impression).
