### ISSUE TITLE
MVP - API End Points - Application

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#101]
@franTarkenton commented on [Wed Aug 10 2022](https://github.com/bcgov/nr-forest-client-api/issues/31)

* GET - Returns all Applications that exist in FAM
* GET - To return a specific application record `https://famdomain/famapp/<app id>`
* POST - To add new application to fam
* DELETE - Remove application record from FAM
* include testing for new crud methods
* include testing for new routes

**Comment by gormless87** [comment]
@franTarkenton - can you provide an estimate form this issue?

**Comment by franTarkenton** [comment]
in this pr: https://github.com/bcgov/nr-forests-access-management/pull/113

includes the application end point GET / POST / DELETE
and the pattern for how we can refactor the tests.
