### ISSUE TITLE
Add an admin-management API Gateway

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1010]
**Describe the task**
 
- [x] Add an admin-management API Gateway. Map all methods to the new lambda function.
- [x] Add api-gateway url to Cognito callbackUrl.
- [x] Prepared terraform "output" for new api url.

**Additional context**
-- ~separate task to add API gateway log content to CloudWatch.~ (This is already added in #975)

**Comment by MCatherine1994** [comment]
We can do the estimate after done the spike ticket, so we have a better understanding about what we need to do.

**Comment by ianliuwk1019** [comment]
FYI...
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01EQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b862d9c94f7bd378661ccb88739c774a753a331c/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52b2e13b07646ed97b25f9c53767f1cd58424136/image.png)

**Comment by ianliuwk1019** [comment]
The newly created api gateway has these two Security Hub medium/low warnings.
```
"APIGateway.3 API Gateway REST API stages should have AWS X-Ray tracing enabled"
"APIGateway.1 API Gateway REST and WebSocket API execution logging should be enabled"
```
These already has been documented in ticket #975 so there is no need to add enable logging ticket.
