### ISSUE TITLE
[Frontend] - Client ID input field error validation issues

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#1014]
**Describe the bug**
Wrong behavior for some edge cases at the field validation from the Client ID field of the Grant User Permission page. Might need refactoring at the regex expression.

**Screenshots**
1.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1dhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--444734c1546b58a648092d12ae34292444aeba6a/image.png)

2.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2FhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81500b3a6c5c90c492c962c8b50ad8ee33481f7e/image.png)

3.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEthQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97af470f4a87cdd269939eb699183a675312a8ef/image.png)

4.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--832374051007b863e5face284c4e5f94cb941e38/image.png)

**Comment by MCatherine1994** [comment]
we can rethink and discuss within the team, to see if we still want to allow user enter multiple forest client at once, or they can enter one by one.
