### ISSUE TITLE
Fix the frontend issue when assign the role

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1020]
**Describe the task**
In the case the user selected the "fom_submitter" role and entered a forest client number, but changed his mind, and change the role to "fom_reviewer". The forest client card is not got removed, and when click submit application, it's still trying to assign the fom_submitter role with that forest client number.

<img width="887" alt="Screen Shot 2023-11-06 at 11 04 42 AM" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/6cbeb291-e86a-473f-bb7d-3251509b9f38">
<img width="1469" alt="Screen Shot 2023-11-06 at 11 04 49 AM" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/c6713a83-21ad-4364-af34-b66a405b7e5c">

**Acceptance Criteria**
- [x] Fix the role assignment issue when change role 

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
@MCatherine1994 - looks good to me - problem solved :)
