### ISSUE TITLE
Update data model 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#1031]
**Describe the task**
Update data model with details resulting from of  Add the new fam_app_admin table #1007

**Acceptance Criteria**
- [x] Setup SchemaSpy Github Actions followed the yaml https://github.com/bcgov/nr-forest-client/blob/main/.github/workflows/reusable-doc-gen.yml
- [x] Update data model [wiki](https://github.com/bcgov/nr-forests-access-management/wiki/Data-Model) to point to the new data model and schema website generated by SchemaSpy
- [x] Document how to config and maintain the SchemaSpy

**Additional context**
- A wrap-up task for the Epic: Split user management into separate deployment unit#883
- Had a meeting with team Alliance to learn about SchemaSpy

**Comment by MCatherine1994** [comment]
Documentation created at: https://github.com/bcgov/nr-forests-access-management/wiki/Setup-SchemaSpy-for-Auto-Generating-Data-Model

**Comment by ianliuwk1019** [comment]
Hi Catherine, I wonder maybe this part is no longer valid (Data Model Source)?
![Image](https://github.com/user-attachments/assets/ebf5e6de-6512-4a6a-bf89-6866743e0f5f)

**Comment by MCatherine1994** [comment]
I think we're not managing that anymore, but not sure if okay to remove that section, or just put a comment there like "old version"?

**Comment by MCatherine1994** [comment]
> Hi Catherine, I wonder maybe this part is no longer valid (Data Model Source)?
> ![Image](https://private-user-images.githubusercontent.com/81595625/357579972-ebf5e6de-6512-4a6a-bf89-6866743e0f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODU0NDksIm5iZiI6MTcyMzU4NTE0OSwicGF0aCI6Ii84MTU5NTYyNS8zNTc1Nzk5NzItZWJmNWU2ZGUtNjUxMi00YTZhLWJmODktNjg2Njc0M2UwZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDIxMzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODFmYWY4M2Y1MTQzZWE0YTA3NDRjNmNiZWNhMTFkNGY4MmFlNmJjOTQyYTczN2NkNzhhN2ZjOWI2ZDhiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-0REWuTmuYnef-z1NF4a93OTEQtevQvAx3LQ9t9GQQ)

I think we're not managing that anymore, but not sure if okay to remove that section, or just put a comment there like "old version"?

**Comment by ianliuwk1019** [comment]
Sorry, I can't access it so don't know what content it is. Sure, maybe (Old Version) make sense. Thanks!
