### ISSUE TITLE
Implement application admin management UI - add application admin UI

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1059]
**Describe Task**
We need a cool new screen to manage application admins! Implement the awesome design in #886 for adding application admin UI, design in [Figma](https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=3637-204243&mode=design&t=a9nlm8GzUvGPUPz9-0) 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzRVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e8446c70c153dd1281484dbdb6fd922a4b50228/Screen%20Shot%202023-11-28%20at%2011.33.33%20AM.png)

**Acceptance Criteria**
- [x] Create a new component "GrantApplicationAdmin" under the grant access folder, follow the same style as "Add user permission" page. Follow the code implementation as example in GrantAccess.vue component. 
    - [x] On mounted, get all fam applications
    - [x] username field and application selection field are both required
    - [x] submit button is disabled if not pass username validation or missing any field
    - [x] Whenever click submit, call the new api to create an application admin, (need to add the user type "I" to the api call) and redirect to the manage permission page (under the same tab) with the notifications as what we have now
- [x] Follow the current design and create a view component for "GrantApplicationAdmin" and call it "GrantApplicationAdminView"
- [x] Add the router for the new "GrantApplicationAdmin" component, and setup the breadcrumb for it
- [x] Whenever user click "Add application admin" button on the manage permission page, the user will be direct to the new "Add application admin" page

**Comment by NickSaglioni** [comment]
For the item 'On mounted, get all fam applications' should it be all the FAM applications or just the ones the user has access to? @MCatherine1994 @OlgaLiber2

**Comment by MCatherine1994** [comment]
Hi @NickSaglioni, it should be a all FAM applications. Cause as a FAM admin, I should be able to assign application admin to all applications.

**Comment by MCatherine1994** [comment]
Hi Nick @NickSaglioni, I think we need to fix a few things:

- When I click on "cancel" the add application admin form, in the screenshot you will see there is an "undefined" text, which is suppose to the the application name. I feel maybe we don't have to show the application name, maybe just say "Enter the user information to add a new application admin"

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/664f8406-02d2-4a66-ad94-2cef94030d24)

- Change the text content to be"Only IDIR users are allowed to be added as application admins"

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/51af5927-dafb-4a4a-9e5b-5ff8ce170b62)

- And I feel this route error doesn't make sense. We actually need two checks. 
    - The first check, is to check if the user has FAM_ADMIN role, if not, then you return this "NOT_FAM_ADMIN" error
    - The 2nd check, is to check if the selected application is FAM, if not, then we should return another error, which means grant access to other applications shouldn't use this route, but I don't know what name we should give to this kind of error, any idea @ianliuwk1019 ?
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/7049e6e3-b488-4f93-98a7-df0d4a1f573a)
- And we actually need to add the same check in the `beforeEnterGrantUserPermissionRoute` as well. In the case I selected "FAM" from the application dropdown, but I enter "/grant" in the browser, it directs me to the grant regular user access page, which is confused. So if the selected application is "FAM", but the user tries to access to "/grant", we should also return the error to indicates this is not the correct page to grant app admin. 

We might need deeper discussion later for all these access restriction, but for now let's just do basic checks and return some simple message. Thanks so much!!

**Comment by MCatherine1994** [comment]
Also this application in the formData shouldn't be Number

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/8d0f2841-2a4f-4f26-8151-aa0d3e269a37)

**Comment by basilv** [comment]
Did a bunch of testing, feedback/findings in Discord chat.

**Comment by OlgaLiber2** [comment]
![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/06b94197-6629-4711-b9b2-531b3f27d99b)

**Comment by NickSaglioni** [comment]
> [@NickSaglioni](https://github.com/NickSaglioni) [@MCatherine1994](https://github.com/MCatherine1994) new mockup
> ![Image](https://private-user-images.githubusercontent.com/121979429/303449062-06b94197-6629-4711-b9b2-531b3f27d99b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MTg1NzMsIm5iZiI6MTcwNzQxODI3MywicGF0aCI6Ii8xMjE5Nzk0MjkvMzAzNDQ5MDYyLTA2Yjk0MTk3LTY2MjktNDcxMS1iOWIyLTUzMWIzZjI3ZDk5Yi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxODUxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYmQzZjZkZGZhYjM5ZGJkOGI1MDlmMGE3OTE0YmY1ZjAzMjJmNWRmYzYwYmM4ZmI5OTFlZGM4MjQ0ODhhYTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-bhkn1jRKNCHv9voYI5hXe_kde3qamflLsdCOXv3cDM)

Thanks Olga. Just my two cents, that "User Information" group without a subtitle looks really odd to me. Shouldn't we include any text just to keep it consistent with everything else? @OlgaLiber2 @MCatherine1994

**Comment by OlgaLiber2** [comment]
@NickSaglioni I agree. I think it needs a border or something, but not more text. The spacing between the title and the next component is too wide, I think that's part of the problem too. Do you want to just take it out for now, and I'll do another pass to see how we can improve it, and I can write a new ticket for that. @MCatherine1994

**Comment by NickSaglioni** [comment]
> [@NickSaglioni](https://github.com/NickSaglioni) I agree. I think it needs a border or something, but not more text. The spacing between the title and the next component is too wide, I think that's part of the problem too. Do you want to just take it out for now, and I'll do another pass to see how we can improve it, and I can write a new ticket for that. [@MCatherine1994](https://github.com/MCatherine1994)

This is how it looks without the subtitle in actual code:


![Image](https://github.com/bcgov/nr-forests-access-management/assets/117364634/fc8c2eb3-4061-4663-92ef-05696a409d3a)

**Comment by OlgaLiber2** [comment]
@NickSaglioni it needs better margins throughout the page
