### ISSUE TITLE
Document FAM Database pattern on the wiki

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#106]
Please document the pattern for FAM database on the wiki and include the following amongst others:

- Database service used on AWS (Aurora or RDS and provide justification)
- Any Replication/fault tolerance settings that may be have enabled including Availability zones for the DB
-Back-up and restore patterns both within AWS and outside of AWS(using EC2 and Vanilla Postgresql, including security groups to permit network access.

**Comment by rparfig** [comment]
https://github.com/bcgov/nr-forests-access-management/wiki/Database-Infrastructure
