### ISSUE TITLE
Clean up FAM roles

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1066]
**Describe the task**
Following admin segregation tasks, cleanup FAM roles and role assignments that have been moved to application admin table

**Acceptance Criteria:**
- [x] Remove the FAM roles from fam_role table
- [x] Remove associated role assignments fam-user_role_xref table

**Additional context**
- Separated the task from #888
- Or here

**Comment by ianliuwk1019** [comment]
Verified with AWS DEV environment db:
- fam_role table does not contain FAM roles:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/74a3d760-edb1-432f-9651-491498eec02e)

- users with application admin have been removed:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/247e7bee-9b0a-492b-bbb7-873b95f654a3)

- application admin management table looks correct. Two records (SILVA_DEV/SILVA_TEST associated with user 15/2) are new.
(The timestamp on date looks correct, but time portion using flyway is always 00:00:00 I think) 
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/06a54691-2f16-4a36-8aad-a7c93ea8547c)

**Comment by MCatherine1994** [comment]
verified in test and prod
