### ISSUE TITLE
Check frontend username upper/lower case to be consistent as in notification

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1070]
**Describe the task**
The screenshot below shows the username in all uppercase in the notification, but lower case in the table and confirmation popup

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/fb0baf7f-83ed-4fa6-922b-c0e7bcf37c76)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/6ae1b8da-5fce-43f2-be15-6aee2987daf0)

**Acceptance Criteria**
- [ ] Make the username display to be consistent in table, notification and confirmation popup

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by OlgaLiber2** [comment]
@MCatherine1994 @ianliuwk1019 @basilv  should bceid users be case sensitive?

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 ,
The backend does not convert case when granting a user in database record.
This looks like just a minor display issue on frontend code, that the code convert it to UPPERCASE.
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--629f2d3855f1331e6fad77c248429747c70f7980/image.png" alt="image.png" />

**Comment by craigyu** [comment]
done in #1650

**Comment by craigyu** [comment]
They all follow the format `{First Name} {Last Name} (USER_ID}`
