### ISSUE TITLE
Create notification email content in GC Notify

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1073]
**Describe the task**
Draft the notification email that will be sent out when granting a user access to an application, or when adding a delegated admin of an application. 

**Acceptance Criteria**
- [x] Create a GC Notify email content template for granting user application access
- [x] Create a GC Notify email content template for adding a delegated admin

**Additional context**
-link to figma file: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=3907-129570&mode=design

**Comment by ianliuwk1019** [comment]
Hi @MCatherine1994 just wondering how we can access our GC Notify templates, I didn't see it sent invite to my gov email account, should I create an account at GC Notify? Or does Olga or Pete has access to it? Thanks.
