### ISSUE TITLE
Add the new fam_access_control_privilege table

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1085]
**Describe the task**
Add the new fam_access_control_privilege table in PostgreSQL

**Acceptance criteria**
- [x] The new table is created
- [x] Give our fam_admin_management_api db user SELECT, UPDATE, DELETE, INSERT privileges on the new fam_access_control_privilege table
- [x] Update the existing model to include this new table, for both admin_management and backend 
- [x] Add the table and attribute description, audit columns (create/update date time, create/update user as other tables)

**Additional context**
Data model design in confluence https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Admin+Segregated+Schema+Design

**Blocking**
[Add delegated admin GET endpoints](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/1086)
[Add delegated admin DELETE endpoint](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/1090)

**Comment by ianliuwk1019** [comment]
There seems to have no need for this new table "fam_access_control_privilege" to be in regular access server/backend api, so it is not added into `model.py` for regular access api and does not create a grant for the regular access api db user.
