### ISSUE TITLE
Improve the logic when push notifications after grant an access 

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1092]
**Describe the task**
The logic in this handleSubmit method is a little bit confused. Especially in the case when forest client number is undefined , and we set it to be an empty string and pass to set notifications. Need a review and refactoring the logic inside the `handleSubmit` and `setGrantAccessNotificationMsg` method.
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--252561ef6fe0910605e9c7605341cd892f0870d0/Screen%20Shot%202023-12-13%20at%2011.08.42%20AM.png" alt="Screen Shot 2023-12-13 at 11.08.42 AM.png" />

**Acceptance Criteria**
- [ ] Review the logic in those methods, and refactor to improve the logic

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by craigyu** [comment]
Refactored in #1650
