### ISSUE TITLE
Include info to the "terms and conditions" doc and email to Chantelle

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1095]
**Describe the task**
Add info below to the "terms and conditions" doc and send to Chantelle to send to legal.

1. add a bullet under "7C Personal Information" that specifies any personal information accessed through FAM cannot be shared 

2.  draft an email to send to Chantelle with the following info: 
- add a brief description explaining what FAM is 
- add a brief description what is a delegated admin and what they do in FAM
- add any visuals (like mockups) to explain what we're doing 
- include when we want legal review to be complete by

[DRAFT  FAM terms of user.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlZjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--accf8d7ecd323f3503f82fc5ed7a8394b0ab2e3f/DRAFT%20%20FAM%20terms%20of%20user.docx)

**Acceptance Criteria**
- [x] email sent to Chantelle

**Additional context**
- Add any other context about the task here.
-

**Comment by gormless87** [comment]
Added clause 7c:   c.	You must not share or disclose any personally identifiable information accessed via FAM.
