### ISSUE TITLE
[Frontend] - Routing to protected routes without being authenticated

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#1097]
**Describe the bug**
The route guard is not blocking when to user tries to route to a protected routed without being authenticated. It opens up the page and in some cases like trying to open `/grant` for instance, it gives a lot of error messages.

**To Reproduce**
1. Logout from FAM
2. Route the browser to a protected route like `/grant` for instance
3. The page will be loaded with error messages in the screen

**Expected behavior**
The route guard should not allow unauthenticated users to route to protected routes and should redirect to the login page

**Screenshots**
<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2da47c59dcf9c1aa086f909bd7e03689fe0d778/Screenshot%202023-12-15%20at%2008.51.28.png" alt="Screenshot 2023-12-15 at 08.51.28.png" />

**Comment by ianliuwk1019** [comment]
This should be a feature to implemented. We never had router guards before for routes.
And this ticket should be a direct ticket for implementation after previous spike ticket Jota had: #742.

**Comment by NickSaglioni** [comment]
The router guard per se could be considered a feature but because we don't have it implemented right now, it leads to lots of error messages displayed to the user  when navigating to certain routes.

**Comment by ianliuwk1019** [comment]
Hi @MCatherine1994 , I have created a [branch](fix/1097-add-route-security-ian) for this matters, and incorporate your change on toast service refactoring with my simplification changes. We can talk together after you come back next week. Hope you have a great holiday.
