### ISSUE TITLE
Display user’s first name, last name and email in the table

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1115]
**Describe the task**
As mentioned in #911, display user info

**Acceptance Criteria**
- [x] Add new columns first name, last name and email in app admin, delegate admin and user access tables
- [x] Make sure new columns are sortable and searchable

**Additional context**
- Add any other context about the task here.
- IDIR and BCeID in scope
- depends on #1366, #1367

**Comment by OlgaLiber2** [comment]
@MCatherine1994  I think we can close this ticket now.
