### ISSUE TITLE
Document API - toward a common understand for MVP

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#112]
| NAME | ABOUT | TITLE | LABELS |
| :------ | :------ | :------ | :------ | 
| Document API / MVP Development | Describe the current understanding of the end points that need to be defined to achieve a MVP version of the FAM API | Document API MVP | enhancement |

---

**As a** *Developer and or architect * **I want** *communicate api requirements for an MVP* **So That** *we can prioritize future development, and ensure there is a common understanding about how the api will function*

**Additional Context**
As development of the user / role end points have progressed, we have realized that we do not have a common understanding around how the data model should work, and how it will be used to back the api. 

Hoping that discussion of the documentation will eliminate any misunderstandings.  The document that is being produced will likely initially contain many errors.  Its intent is to clarify these misunderstandings and resolve them.

**Acceptance Criteria**
- [ ] Everyone on the team has read, and understands at least at a high level the requirements for MVP.
- [ ]  The document can serve to define an EPIC for FAM MVP

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by franTarkenton** [comment]
Documentation page exists here:
https://github.com/bcgov/nr-forests-access-management/wiki/FAM-API-Common-Understanding-MVP

To be completed:
* define the user end points and how the relate to the existing end points
* Review document with FAM team.
* Edit and remove any errors

**Comment by franTarkenton** [comment]
Read through a few times, added some comments, new sections.  As continue work on it feel like we need to have a conversation about this before any more work is completed on this document.   too many unknowns to be able to proceed.

Example:
* can roles exist independent of application
* can groups exist independent of application

**Comment by franTarkenton** [comment]
Propose that a result of out latest sprint planning meeting we call this done for now?  @gormless87 / @ArogeG
