### ISSUE TITLE
Change button wording

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1126]
**Describe the task**
Change button wording from "submit application" to "grant access" to be more clear to the action the user is performing

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/cdb4ee52-7ffb-4413-a8a7-02aae3645256)

**Acceptance Criteria**
- [x] Update the button wording to "Grant Access", "Create Delegated Admin" and "Create Application Admin"

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
Looks good, wording changes confirmed.
