### ISSUE TITLE
Add role definitions to "grant access" and "create a delegated admin" pages

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1127]
**Describe the task**
Add role definitions to "grant access" and "create a delegated admin" pages

**Acceptance Criteria**
- [ ] second
- [ ] third

**Additional context**
This might change in the future, for now please use this format for role description: 

note: the mockup is for multi-select drop down. Please ignore the multi-select part.
![Capture-accessrole description](https://github.com/bcgov/nr-forests-access-management/assets/121979429/c6e6b59d-e8f6-41e2-945d-1185b864746a)

**Comment by aliramoss** [comment]
This one?
https://www.figma.com/file/4zvMCRE2yDtEp94xwtcpdh/Request-for-user-access?type=design&node-id=35-2212&mode=design&t=uZPwZalwdUKP95QW-4

**Comment by OlgaLiber2** [comment]
@aliramoss yes, thank you

**Comment by gormless87** [comment]
made redundant by #1128
