### ISSUE TITLE
Add "sort" caret to all columns in the user table

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1129]
**Describe the task**
Add "sort" caret to all columns in the user table to clearly indicate the column is sortable

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/ac250371-31f1-4a10-a631-ab4793a4711b)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/8f3a4cb3-ec25-41b4-8dcd-e84f34dd32c9)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by MCatherine1994** [comment]
this is done.
