### ISSUE TITLE
Test environment foreign key constraint not enforced

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#114]
**Describe the Bug**
Test environment foreign key constraint not enforced for tests with **SqlLite** test database.

**Expected Behaviour**
ORM model (and database) is clearly indicating the Foreign Key Constraint is in place.
When writing a test (pytest/**SqlLite db**) that expects an insert with foreign key constraint violation should then throw IntegrityError.
For example, inserting a new role with parent role not existing in db.

**Actual Behaviour**
Currently our Test environment does not throw expected exception when violating foreign key constraint with SqlLite.

** Steps To Reproduce**
Please see screenshot section for code and running result.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/750e484a-ced3-45fa-9a3c-c548a32a21c5)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/2e0d9a7d-a578-4c1a-8922-22246f4a56d6)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/8bc22aaf-dacb-4ad0-89b7-2df054237c76)

**Additional context**
This is in Test environment using **SqlLite**.

Once solution is in placed for Test environment, expecting some existing tests will need to be fixed.

**Comment by gormless87** [comment]
Hi @ianliuwk1019 - here is a first draft of the foreign key constraint ticket. I'm using a 'bug' issue type template instead of a 'feature' issue type, hope that is appropriate.

Can you fill in the Expected and Actual sections? Don't go too detailed, just enough for another developer to get started. A screenshot or error message text capture might suffice.

**Comment by ianliuwk1019** [comment]
I have found a solution from SqlLite. It isn't obvious, and don't know why Pytest framework does not mention that.
```
# This @event is important. By default FOREIGN KEY constraints have no effect on the operation of the table from SQLite.
# It (FOREIGN KEY) only works when emitting CREATE statements for tables.
# Reference: https://docs.sqlalchemy.org/en/14/dialects/sqlite.html#foreign-key-support
@event.listens_for(Engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()
```

The test that intended to test the foreign key violation (role -> parent role) does pass.
The next is to fix existing failing tests.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/a667a0b5-f3db-494f-bd5c-3da8e0f241d9)
