### ISSUE TITLE
Build get_my_FAM_access_API

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1143]
**Describe the task**
Build get_my_FAM_access API  as per [Confluence anchor](https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Delegated+Access+Administration+Design#DelegatedAccessAdministrationDesign-get_my_FAM_accessAPIget_my_FAM_accessAPI)

**Acceptance Criteria**
- [x] API name conforms to Team Heartwood convention (Confluence update required)
- [x] Tested with user that has only FAM-ADMIN role
- [x] Tested with user that has no role
- [x] Tested with user that has multiple app admin roles
- [x] Tested with user that has delegated admin access (ie; FOM_SUBMITTER)
- [x] Regenerate the client-code-gen 
- [x] Return application information (application id and application name), we need to use these to show the application dropdown list  

**Additional context**
Story: 
The UI should use the new get_my_FAM_access API for determining what the user has access to do as a FAM admin or app admin.

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/ca363a28-88d2-425c-8cd4-d2dbea4196a0)

For now, if the user is FAM Admin, the return result for the FAM Admin entry "grants" attribute will have a list of all applications.  But later on, we'll restrict the access of FAM Admin and specify which applications the FAM Admin can manage, then the "grant" attribute list will be different.
If user is Application Admin, the return result include all app roles. App admin can grant all roles.

**Comment by ianliuwk1019** [comment]
I intend to use this for the GET API endpoint PATH (function name does not matter that match): "**(GET): /fam-user-access**".
If there is better path naming suggestion, I can rename/refactoring it easily.
@basilv @MCatherine1994

**Comment by basilv** [comment]
Assuming this follows the conventions of the other API endpoints, I'm fine with this.

**Comment by ianliuwk1019** [comment]
Before implementing the endpoint, I took some time to have a rough final JSON contract for backend/frontend. I adjust the draft structure on confluence a little. I hope my understanding is correct. This is important for this endpoint to capture the correct logic:
If not correct or still doubts, please do see if we have time to discuss on Monday. Thanks. @basilv @MCatherine1994 @gormless87 

"**Top level return structure**":
(Note: I switch from original "**role_key**" to "**auth_key**")
* The user who logged in may contains all 3 (**"FAM_ADMIN", "APP_ADMIN", "DELEGATED_ADMIN"**) privileges with details of what they are granted for:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/5006a234-7d64-4db9-abe1-48e67046cc48)

"**Details return structure**":
```
{
   "access": [
      {
         "auth_key": "FAM_ADMIN",
         "grants": "ALL_APPS"
      },
      {
         "auth_key": "APP_ADMIN",
         "grants": [
            {
               "application": {
                  "id": 3,
                  "acronym": "FOM",
                  "name": "Forest Operations Map",
                  "env": "DEV"
               }
            },
            {
               "application": {
                  "id": 6,
                  "acronym": "SPAR",
                  "name": "Seed Planning and Registry Application (TEST)",
                  "env": "TEST"
               }
            }
         ]
      },
      {
         "auth_key": "DELEGATED_ADMIN",
         "grants": [
            {
               "application": {
                  "id": 4,
                  "acronym": "FOM",
                  "name": "Forest Operations Map",
                  "env": "TEST"
               },
               "roles": [
                  {
                     "id": 3,
                     "key": "FOM_REVIEWER"
                  },
                  {
                     "id": 3,
                     "key": "FOM_SUBMITTER",
                     "forest_clients": [
                        "00001234",
                        "00005678"
                     ]
                  }
               ]
            },
            {
               "application": {
                  "id": 7,
                  "acronym": "SPAR",
                  "name": "Seed Planning and Registry Application (PROD)",
                  "env": "PROD"
               },
               "roles": [
                  {
                     "id": 57,
                     "key": "SPAR_SPR_MIN_FOREST_GENETICS",
                     "forest_clients": [
                        "00001001",
                        "00001002"
                     ]
                  },
                  {
                     "id": 57,
                     "key": "SPAR_SPR_SILVICULTURE_SUPERVISOR",
                     "forest_clients": [
                        "00001003",
                        "00001004"
                     ]
                  }
               ]
            }
         ]
      }
   ]
}
```

**Comment by basilv** [comment]
The ALL_APPS should be an actual list of applications.

**Comment by MCatherine1994** [comment]
Hi Ian, I'm fine with the new structure, just wondering so for now for "FAM_ADMIN", will you just return a string "ALL_APPS", or you'll return a list of all apps?

And I'm just wondering maybe it's more clear to use "application_id", "role_id", instead of just "id"? and "application_name", "role_name", so it's also consistent?

**Comment by ianliuwk1019** [comment]
Discussed with Basil the previous comments on "ALL_APPS" and the use of id naming.

(although initially I was thinking we do already have endpoint for this and did not want to see this endpoint abuse itself to stack all information in one endpoint and cluttered on user's brower's cache)

I will use the "**actual list of applications**" instead of "ALL_APPS" 

For naming, I will stick to "**id**" (e.g., `application.id`, not `application.application_id`) and **no prefix again**, for this endpoint only. I intend to refactor other endpoints schema later (when get a chance, not many endpoint anyways); for whatever model standard (Oracle or else) the backend has will stay with the backend and free the frontend from tightly coupled with model (and also with python snake_case).
