### ISSUE TITLE
Use API to get list of applications for FAM admins

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1146]
**Describe the task**
Use cached results from get-my-access API to list applications for FAM admins for Grant Application Admin screen

**Acceptance Criteria**
- [x] Stop making API call; use cached results instead
- [ ] Tested with user that has FAM-ADMIN role

**Additional context**
Story: The UI should use the new get_my_FAM_access API for determining what the user has access to do as a FAM admin or app admin.

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/6df4fecd-c892-45ca-a2d6-df416c75e859)

refers to API in #1143 

#378 relates to this issue

**Test note:**
In ticket #1144, we cached the user access in the local storage "famLoginUser" (this could change depends on how #1144 is implemented). When we write component tests in this ticket, we can set the local storage "famLoginUser" with the access we want (based on different test scenario), and mount the "Grant Application Admin" page, and verify if the application dropdown returns the expected applications. For example, as a FAM admin, my access in the cached result could be like the following, then the application selection dropdown will list the applications in the "grants" list. 

{ "application": { "id": "3", "acronym": "FAM", "name": "Forest Access Management", "env": "" }, role_key: "FAM_ADMIN", grants: [ { "application": { "id": "1", "acronym": "FAM", "name": "Forest Access Management", "env": "" }, { "application": { "id": "2", "acronym": "FOM", "name": "Forest Operations Map", "env": "DEV" }, ... },

**Comment by MCatherine1994** [comment]
Use cached results to list applications in the Grant Application Admin screen is done in ticket #1145, only left test for this ticket
