### ISSUE TITLE
Delegated admin list screen (frontend)

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1149]
**Describe the task**
Create screen for managed delegated admin table

**Acceptance Criteria**
- [x] New table component for delegated admin created
- [x] New tab section created
- [x] API completed in #1086 called to populate the table
- [x] "Add user" text on button changes to "Create Delegated Admin"  (see Figma)
- [x] Manage Permissions sidebar link leads to this screen (if user is admin for chosen app).
- [x] Show the delegated admin management functionality only if I'm an app admin (not including FAM admins)

**Additional context**
Story: As an app admin I want to review the list of delegated admins for my application 
![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/2c5a4e7a-2e33-419d-8743-ad1eb1c049fb)

Link to figma mockup: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Delegated+Access+Administration+Design?preview=/163414102/187011845/FAM-delegated-admin-user-table.png

NOT adding tests at this time as the component is not fully stable

Will not display first/last name as that task is not yet complete

**Comment by ianliuwk1019** [comment]
Based on Basil's delegated access design, I was having a thought of this **basic** picture in mind (probably aligned the same with what Basil's in mind, but there **might be more creative user UI designs**):

![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/e53435ff-48d9-48ca-9bfc-77114eb145ca)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/8b53369c-0b0d-4549-b235-30fd273bc4c6)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/040bcf95-5fb4-47cf-a176-e4635730306e)

@OlgaLiber2 @basilv

**Comment by basilv** [comment]
Yes, your first diagram (at the top) does a good job illustrating the intent. One potential point of clarification, the "Add User Permissions" screen will likely look a bit different for app admins vs delegated admins, so not sure yet whether it will actually be the same screen or not.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019  not sure what you mean
