### ISSUE TITLE
Support Forest Client: BC Service Card login issue

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1155]
**Describe the task**
Team Alliance is getting bc service card login issue. They found that when try to login using test BC Service Card account, sometimes they will get a read time out error. I found that as well sometimes when using the OIDC debugger tool. And if try to login again, it works fine, the login will be successful. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/ba282600-a58d-4f54-a5cf-8f36b1242f45)

The original email from Maria is in the screenshot:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/e87fc7a8-bcb2-4fa0-b121-477e68c33133)

**Acceptance Criteria**
- [x] Find out what causes the issue

**Additional context**
- Send the email to Wesley, but starts to feel the timeout might happen on our side. 
- From Ian: Based on the problem description (if I understand correctly), you wont be finding Cloud Watch log for our lambda log (our FAM log) but might be the log that AWS auto created for lambda (access log).
Because what I think is if the assumption or first time reaching the lambda when it is COLD is true, AWS is invocating the lambda (thus not yet executing the handler within our FAM code yet) and our Cognito receive time-out and thus generating 302 redirect for the user browser.
If you look at the sequence diagram, when the “code” received from the BCSC, browser then hand over to Cognito, which then tries to pass the “code” to our lambda. But because our lambda is COLD so time-out for Cognito. Then the rest of the happy path sequence diagram isn’t fulfilled.
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/8478b56d-9638-4344-b73e-f26d33f11092)
- From Basil: We should be looking at either cognito timeout settings (to make the timeout duration longer), or look at the lambda configuration to see if we can keep it hotter. Also, it might not be the lambda itself – could be the database proxy

**Comment by MCatherine1994** [comment]
API Lambda logs when bc service card login fail, it generates 2 logs:

1st one:
[log-events-viewer-result.csv](https://github.com/bcgov/nr-forests-access-management/files/14068327/log-events-viewer-result.csv)

2st one:
[log-events-viewer-result (1).csv](https://github.com/bcgov/nr-forests-access-management/files/14068336/log-events-viewer-result.1.csv)

Try to login again, and successfully login, it generates 1 more log, and add logs in the last 2:

The last 2 logs with more information:
[log-events-viewer-result (2).csv](https://github.com/bcgov/nr-forests-access-management/files/14068358/log-events-viewer-result.2.csv)
[log-events-viewer-result (3).csv](https://github.com/bcgov/nr-forests-access-management/files/14068359/log-events-viewer-result.3.csv)

The new generated log:
[log-events-viewer-result (4).csv](https://github.com/bcgov/nr-forests-access-management/files/14068360/log-events-viewer-result.4.csv)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/90da1147-88b8-469e-a567-9a491eefa55a)

**Comment by MCatherine1994** [comment]
From the AWS documentation https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html, when Amazon Cognito calls your Lambda function, it must respond within 5 seconds. 

When checking the logs in the login failure case, the call to get the bc service card token takes about 3s, in the login successful case, it takes about 0.5s. 

code where we make the call: 
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/1ccd65a8-e4d9-4d6e-ae37-a161414cd8f2)

failure case:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/01cf8dd3-d82d-4c9d-bf9d-72b424ad136e)

successful case:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/d79af604-99f4-4181-b0d6-c30750337118)


So next step needs to contact Wesley and ask about the response time for making the call to `https://idtest.gov.bc.ca/oauth2/token`

**Comment by basilv** [comment]
Decided resolution is for the BCSC team to cache (hardcode) our public key in their system, to avoid the ~2 sec key lookup overhead that was causing the Cognito get user info call to our get user info endpoint to timeout after 5 seconds.

I've researched our use of the key and documented it in our secret registry that when we change it we'll need to update the BCSC team.
