### ISSUE TITLE
Technical design discussion

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1158]
**Describe the task**
Technical design discussion on reusing components of the grant access screen (reusing components on the end user access, app admins, and delegated admins pages)

**Acceptance Criteria**
- [x] Conclusion if we can reuse any components, and which ones. 

**Additional context**
User story: As an app admin I want to grant a user access to be a delegated administrator for a particular application, role(s), and forest client(s).

Links to mockups: 
- manage permissions: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-button.png?version=1&modificationDate=1705432026000&api=v2 

- add delegated admin page: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-form.png?version=1&modificationDate=1705432155000&api=v2

- popup modal: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-form-popup.png?version=1&modificationDate=1705432242000&api=v2

**Comment by MCatherine1994** [comment]
Reusable components:

username input
user domain selection
forest client number input
