### ISSUE TITLE
Frontend display of "add delegated admin" form

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1159]
**Describe the task**
Create a "add delegated admin" form (on the front end) 

**Acceptance Criteria**
- [x] Grant delegated admin access page exists (frontend)
- [x] Get the role list from the cached user accesses
- [x] Validation of required fields before submitting is working
- [x] New path to delegated admin page route included
- [x] Make sure only app admin can access to this route

**Additional context**
User story: As an app admin I want to grant a user access to be a delegated administrator for a particular application, role(s), and forest client(s).

Can reuse user domain select, username input, forest client input components

Depends on #1160

Links to mockups 

- add a delegated admin page: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-form.png?version=1&modificationDate=1705432155000&api=v2 
- validation popup modal: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-form-popup.png?version=1&modificationDate=1705432242000&api=v2
- display option on left nav bar: https://apps.nrs.gov.bc.ca/int/confluence/download/attachments/163414102/FAM-delegated-admin-button.png?version=1&modificationDate=1705432026000&api=v2

**Comment by gormless87** [comment]
test close
