### ISSUE TITLE
Submit grant delegated access function (frontend)

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1160]
**Describe the task**
Submit delegated grant access function (frontend) 

**Acceptance Criteria**
- [x] Submit grant access function (frontend)
- [x] includes confirmation pop-up
- [x]  Includes display of success message
- [x] Error conditions displayed appropriately
- [x] Cancel button click returns to Managed Delegated Admin table (list page)

**Additional context**
See #1089 for API return result

User story: As an app admin I want to grant a user access to be a delegated administrator for a particular application, role(s), and forest client(s).

**Comment by basilv** [comment]
AC "Includes functionality of adding a new user to the top of the user table and highlighting the row" should be split into a separate ticket

**Comment by MCatherine1994** [comment]
Hi @OlgaLiber2 , do we have mockup for the success, or error notification message for granting delegated admin? For example: 

`IANLIU was successfully granted privilege to manage the Client 00001011,00001012`, 

`IANLIU was not granted privilege to manage the Client 00001011,00001012` something like this?
