### ISSUE TITLE
Restrict create application admin endpoint to only allow IDIR user

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1175]
**Describe the task**
Restrict create application admin endpoint to only allow IDIR user

Add rule to API for creating access assignments to prevent granting fam/app admin access to a BCeID user; and
Ensure grant access screen for granting FAM/app admin does not include the option for BCeID user.

**Acceptance Criteria**
- [x] Add check on user type when creating application admin, return error message when user type is bceid
- [x] Update tests to check on user type
- [x] return descriptive error notification 
- [x] Remove temporary addition on repository query filter `FamUser.user_type_code == UserType.IDIR` (and the comment) from `application_admin_repository.get_user_app_admin_grants()` as after restriction is added there won't be such record (other than idir type user) being created.

**Additional context**
- See #1059 for frontend-related work already in review
- could be done in router guard or service validation check (router preferred)

**Comment by gormless87** [comment]
Status of done in project, open in github; forcing close in github
