### ISSUE TITLE
Add rule to API to prevent granting fam/app admin access to a BCeID user.

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1178]
**Describe the task**
Add rule to API for creating access assignments to prevent granting fam/app admin access to a BCeID user; and 
Ensure grant access screen for granting FAM/app admin does not include the option for BCeID user. 

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
dupe

**Comment by gormless87** [comment]
Status of Done in the project, but still open in github; forcing close in github.
