### ISSUE TITLE
Log into FAM with a Business BCeID account

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1179]
**Describe the task**
Log into FAM with a Business BCeID account

**Acceptance Criteria**
- [x] Enable "Login with BCeID" option on FAM login screen
- [x] Enable business BCeID identity provider for FAM application
- [x] Have Cognito map attributes from the identity providers claim into the FAM identity token
- [x] Confirm FAM user profile screen shows available information for the current BCeID user based on the token. (create a new ticket if the profile doesn't display info properly)
- [x] Requires delegated admin  - same behavior as IDIR login without permissions 

**Additional context**

- Based on our BCeID Service Agreement, we'll have access to the following fields: user GUID, user ID, user display name, email, business GUID, business legal name (and asking for 'also known as'). We'll want to map all of these fields. 

- In the user profile screen we'll want to show all of these attributes except the GUIDs.

**Comment by MCatherine1994** [comment]
We already have the attribute mapping, just need to add `custom:idp_business_id` to the read and write attributes so Cognito can override it and return to us. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/255a8791-fb3a-42bb-af3d-8fd6f50bb1eb)
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/080948b7-d7e0-4be7-afa5-ce796959b2e7)
