### ISSUE TITLE
Sort out RDS duplicated secrets

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#118]
For both sysadmin and fam-proxy-api database users, we have the secret in SecretManager created via terraform (which is _missing_ the RDS hostname) and we have an additional secret that looks like was created automatically and has much more information including the RDS hostname, port, etc..

Duplicating secrets for the same user is bad because it prevents doing rotation and is confusing to maintain. I'd prefer we use the automatically-generated secrets and avoid creating duplicates in terraform.

**Comment by ConradBoydElliottGustafson** [comment]
The one with the extra information was created by the Query Editor tool in the administration console. It was not created by Terraform. It can safely be deleted, but it is convenient to be able to use the Query Editor tool to do testing in DEV. This would not exist in PROD (probably?)
