### ISSUE TITLE
Backend API to validate BCeID 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1180]
**Describe the task**
When retrieving details of a BCeID user from the IDIM web service include the BCeID Business GUID so that business rules based on BCeID organization can be enforced. 

**Acceptance Criteria**
- [x] Update FAM backend calling IDIM web service proxy to return BCeID Business GUID
- [x] Create router to interface with idim-proxy endpoint created as part of (idim-proxy # 72)
- [x] Test API
- [x] Regenerate client code

**Additional context**
- See endpoint creation issue in idim-proxy repo (issue# 72)

**Comment by MCatherine1994** [comment]
Hi Basil @basilv, just wondering does it matter where I add this new api endpoint to? to the new admin management directory where it has all admin endpoints, or to the previous backend directory where it has all regular endpoints?  The current endpoint for searching IDIR user is in the backend directory, maybe I'll add the endpoint for searching bceid at the same place? so it already has the configuration to integrate with IDIM proxy


![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/95abdf50-02a7-402f-aa9e-97dcd67a6cd9)

**Comment by basilv** [comment]
@MCatherine1994 yes, adding to the same backend makes sense right now.
