### ISSUE TITLE
Write front-end logic for a scenario that BCeID delegated admin is trying to add a BCeID

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1183]
**Describe the task**
Write front-end logic for scenarios that the delegated admin is trying to add a BCeID user
**Acceptance Criteria**
- [x] Frontend add logic to require verify bceid user, call Backend API to verify
- [x] In the successful case, display the information, userid, first name, last name, organization
- [x] As an IDIR user I can validate any Business BCeID
- [x] As a BCeID user if I attempt to validate a user in a different organization, I get the error msg, Error message noting "information about the users cannot be displayed because they are not in your organization [organization name]"
- [x] User not found case has same behavior as for searching IDIR
- [x] implemented in UserNameInput component, create a follow up ticket to update/create the test for the UserNameInput component

**Additional context**
- This applies to any scenario where BCeID user details are displayed:

On validation of the id when granting access
On displaying user first & last name for granted user access.

We'll use the BCeID Business GUID attribute to check the organization of each user.

For any record not matching, redact / blank out / hide / remove attributes of personal information (PIA states that "no information about the result will be displayed", but we can at least confirm that the user id is valid). The result returned to the front-end will specify that information about the users cannot be displayed because they are not in the same organization.

**Comment by NickSaglioni** [comment]
Do we have a test BCeID user? @MCatherine1994

**Comment by MCatherine1994** [comment]
yes, I'll send you in the chat

**Comment by J0taFerreira** [comment]
How should the message be displayed when the bceid user tries to verify outside of his organization? @MCatherine1994 @OlgaLiber2 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/b90b7eae-31f3-4a97-b1ac-2571cae8b896)


![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/6123afc3-6705-4c67-a8f9-256dc61ae0b8)

**Comment by OlgaLiber2** [comment]
@J0taFerreira I would do the format of the first screenshot you have without the user name. But I will give you better wording next week. We can change the text in the future, it should be quick.
