### ISSUE TITLE
FAM Login Returns Error: Unsupported configuration for OIDC Provider.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#1197]
**Describe the bug**
This problem(error) seems to be happening recently since the week of **Feb 05, 2024 or close to that time**.
Either the **pipeline** or **login** to FAM can (not always) see this error: "**Unsupported configuration for OIDC Provider. Please review the documentation for specification."**

**To Reproduce**
1. Hard to reproduce, but might happen on first time login. Subsequent login might see no issue.

**Expected behavior**

**Screenshots**
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/3e2adc85-78f9-4a29-abe8-6f401e102691)

**Acceptance Criteria**
- [ ] Update terraform to manual add IDP config endpoints for IDIR and BusinessBceid (authorization, token, user info, jwk)
- [ ] Test the business and idir login in test environment, then test in prod after deployed to production

**Additional context**
- There is no Terraform changes.
- PROD also emits the same behaviour but still can login. However, PROD at this time was released few months ago (last year) so there is no code change that seem to create this issue.

**Comment by MCatherine1994** [comment]
Meet with Pathfinder SSO team Marco Villeneuve and Jonathan Langlois. The "unsupported OIDC identity provider" issue returns from Cognito before connect with Keycloak or lambda, and there is no log generated in our CloudWatch. The guess is that when auto fill IDP endpoints (authorization endpoint, token endpoint, userInfo endpoint etc.) from the issuer url, there might be slow response or something blocked it.
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/fea93942-dafc-4e2d-9d37-b2376cf5cba3)
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/e2367642-67c5-413c-b85b-9f07ab9d0a1f)

The solution for now is to manually enter all those endpoints, and the endpoints can be found at `[issuer_url]/.well-known/openid-configuration`, for example https://test.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration.

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/37d4f6dc-5f6a-4c5e-8101-837d37574b14)
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/1c13271d-584e-4f3d-8e99-5d3db2ebc691)

Made the change in AWS TEST for TEST-IDIR, will keep try the FAM-TEST in 1-2 weeks to see if the login error happens again. If it's working fine, we might want to add these config endpoints to terraform.

**Comment by MCatherine1994** [comment]
Documentation for setting up IDP provider detail attributes in terraform: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html#API_CreateIdentityProvider_RequestSyntax
