### ISSUE TITLE
Support SPAR: add new roles

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1206]
**Describe the task**
As required from SPAR team, they need 3 new roles:
- Orchard Manager – internal (or ministry), no need forest client number
- Orchard Manager – external (or non-ministry), this one requires forest client number
- TSC_Admin, no need forest client number

**Acceptance Criteria**
- [x] Write the flyway script to add three roles, add role purpose
- [x] Add three roles to all env, SPAR_DEV, SPAR_TEST and SPAR_PROD
- [x] Requesting team has provided role purpose

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by MCatherine1994** [comment]
Meet with Sabina and Craig and Olga, they have a concern in the future if they want to pass the token from old spar to new spar, maybe it's better to keep using the old role name. Consider the possibility and that's the future plan, we'll still use the new role name for consistency in FAM, and they are fine with it, in the future if they still want to old role name, we can switch for them.

**Comment by ianliuwk1019** [comment]
In the PR it has these 3 new roles and descriptions to be added:
```
TSC_ADMIN user role allows a ministry SPAR user to access SPAR administrative screens and perform administrative functions such as seedlot registration approval, or seedling request approval

SPAR_SPR_MINISTRY_ORCHARD user role allows ministry SPAR users to access the A class registration screens and to create, review, update and submit A class registration forms.
Ministry users may enter and update lots within their own Organizational Unit.

SPAR_SPR_NONMINISTRY_ORCHARD user role allows non ministry SPAR users to access the A class registration screens and to create, review, update and submit A class registration forms.
Non-Ministry Users may enter and update lots where their sign in client profile matches the Applicant Client.

SPAR team is okay to use the role name SPAR_TSC_ADMIN, SPAR_MINISTRY_ORCHARD and SPAR_NONMINISTRY_ORCHARD for consistency
```
And pr mentioned the descriptions are adjusted version to fit into max column size (200) in FAM.
Just want to confirm that: does the team confirm they are ok for the description we adjusted for them?
Thanks Catherine.
@MCatherine1994

**Comment by MCatherine1994** [comment]
Hi Ian, thanks for checking, we didn't change much about the description, it's almost the same.

**Comment by MCatherine1994** [comment]
verified in dev db:


![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/a5872505-18dc-4f6d-a9ce-3f7cefe71901)
