### ISSUE TITLE
Address accessibility debt on all FAM pages

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1223]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [x] Address accessibility debt
- [x] Test all FAM pages with screen reader
- [ ] Push all changes into prod

**Additional context**
- Accessibility changes noted in mural: https://app.mural.co/t/climatechange4363/m/climatechange4363/1709752035266/0e0f72d31be90633c4f744e8b4b53b59f47475b4?sender=u84301558fa490f89e6792901 
- 
- Use BC Gov guidelines for content and accessibility https://www2.gov.bc.ca/gov/content/governments/services-for-government/service-experience-digital-delivery/web-content-development-guides/web-style-guide/writing-guide/headings

NOTE: this MAY impact existing tests

**Comment by NickSaglioni** [comment]
I am going to include documentation for this task in the comments section here.

**Comment by ianliuwk1019** [comment]
This ticket has additional minor sideNav look and feel adjustment.

```
not bolded ul
only clicked-on item is bold font
tab "Add user permission" under manage permissions
tab "Add delegated admin" under manage permissions
remove the icons
```

![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/3f19f9a1-b143-461c-b97c-5aa68e4afdcb)
