### ISSUE TITLE
UI changes: update icon on "nothing to display yet" page

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1226]
**Describe the task**
- Change UI icon on "nothing to display yet" page. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/66cd8968-3261-4798-8580-6e4650d8a58e)

**Acceptance Criteria**
- [x] change the icon to the new one to be consistent with the other apps

**Additional context**
-link to Carbon's icon, titled "search locate" https://carbondesignsystem.com/elements/icons/library/

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/0eb87d0e-cd22-4e9a-8e8c-1abda6babe2c)

**Comment by MCatherine1994** [comment]
Verified in FAM DEV

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/5c2a0b6b-e4fe-4ce1-8a2e-4c3d741df40c)
