### ISSUE TITLE
Restructure FAM directory 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#124]
---
name: Feature request / user story
about: Suggest an idea from the perspective of a user
title: ''
labels: enhancement
assignees: ''

---

**As a** *(User Type/Persona)* **I want** *(Feature/enhancement)* **So That** *(Value, why is this wanted, what is the user trying to accomplish)*

**Additional Context**
Option 2
/server
/server/backend
/server/frontend
/server/infrastructure
 heart 1

[1:38 p.m.] Vandegriend, Basil
Currently:
/server - with terraform and sample
/backend - with terraform clone and real API

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged into DEV

[1:36 p.m.] Vandegriend, Basil

**Comment by ianliuwk1019** [comment]
Due to inflexibility of the terraform cloud, the decision is to move current 'backend' to within 'server'.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/2bf48b95-3987-4768-a118-92867693de10)
