### ISSUE TITLE
Add display Name for roles

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#1242]
**Describe the task**
Add a database column to store a role display name

**Acceptance Criteria**
- [x] Add db column (100 character limit) for role display name - nullable
- [x] Populate the new column for existing roles (to be added to this ticket)
- [x] Ensure child roles use parent abstract role display name as their display name
- [x] Update ORM model(s) for fam_role for new column
- [x] Update the return results of return-my-access-api to include role display name and role purpose
- [x] Update get-user-role-assignment, ~~get-app-admin~~, get-delegate-admin to include role display name 
- [x] Add/update test if need

**Additional context**
- Proper English role name to display in UI
-  #1128 is for display
- column needs to be nullable

mockup:

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/0c3626e6-4648-46c5-9792-2f668aa9be09)

**Comment by ianliuwk1019** [comment]
From database we have these roles across applications.
We don't have role display names for them.
Would these look fine (column two below):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/po-yi.liu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/po-yi.liu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#467886" vlink="#96607D">


role_name |  
-- | --
Admin | Admin
Approver | Approver
CLIENT_ADMIN | Client Admin
CLIENT_EDITOR | Client Editor
CLIENT_VIEWER | Client Viewer
FOM_REVIEWER | Reviewer
FOM_SUBMITTER | Submitter
Planner | Planner
SPAR_MINISTRY_ORCHARD | Ministry Orchard
SPAR_NONMINISTRY_ORCHARD | Non-ministry Orchard
SPAR_TSC_ADMIN | TSC Admin
Submitter | Submitter
Viewer | Viewer



</body>

</html>

@OlgaLiber2

**Comment by OlgaLiber2** [comment]
Here is what we have @ianliuwk1019 
![FAM - Design_2024-08-22_14-31-20](https://github.com/user-attachments/assets/254da979-93d1-4e3b-a7d6-f8ebc189a0a1)

**Comment by ianliuwk1019** [comment]
> Here is what we have [@ianliuwk1019](https://github.com/ianliuwk1019) ![FAM - Design_2024-08-22_14-31-20](https://github.com/user-attachments/assets/254da979-93d1-4e3b-a7d6-f8ebc189a0a1)

Great, thank you so much Olga!!

**Comment by ianliuwk1019** [comment]
Ticket #1563  created for SILVA roles inconsistency.

**Comment by ianliuwk1019** [comment]
The new column for display name will be `display_name`, will not be `role_display_name`.
