### ISSUE TITLE
/fam_application/{application_id}/roles - GET 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#126]
**As a** *Developer* **I want** *this endpoint** So That** *MVP req met*

**Additional Context**
GET - gets all the roles that are directly associated with an application - if a role has a child that role should be returned also

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged into DEV

**Comment by franTarkenton** [comment]
until we can deploy a feature branch, cannot demo on AWS. 

To view feature checkout branch and run:
```
cd server/backend
docker-compose up
```
Then navigate to http://localhost:8000

* create a new role POST - api/v1/fam-roles with this payload
```
{
  "role_name": "test_role",
  "role_purpose": "test test test",
  "application_id": 2,
  "create_user": "Ian Clause",
  "role_type_code": "C"
}
```

* retrieve using GET - api/v1/fam_applications/{application_id}/fam_roles, where application_id is 2

**Comment by franTarkenton** [comment]
also... I think this ticket also closes: 
https://github.com/bcgov/nr-forests-access-management/issues/253

**Comment by franTarkenton** [comment]
hey @basilv / @ianliuwk1019, we have two different types of roles:
* C (concrete) can assign a user to this role, cannot assign a role to this role
* A (abstract) can assign a role to this role, cannot assign a user to this role

For the end point  `api/v1/fam_applications/{application_id}/fam_roles`, if there are only concrete roles associated with the application then i'm proposing the return json would look like this:

``` json
{
    "application_name": "test app",
    "application_description": "a really good app",
    "application_client_id": null,
    "application_id": "1",
    "fam_role": [
        {
            "role_name": "FAM_ADMIN",
            "role_purpose": "FAM Admin",
            "parent_role_id": null,
            "application_id": 1,
            "forest_client_number": null,
            "role_type_code": "C"
        },
        {
            "role_name": "FAM_TEST",
            "role_purpose": "FAM Testing",
            "parent_role_id": null,
            "application_id": 1,
            "forest_client_number": null,
            "role_type_code": "C"
        }
    ]
}
```

And when there is an concrete role that falls under an abstract role:

``` json
{
    "application_name": "test app",
    "application_description": "a really good app",
    "application_client_id": null,
    "application_id": "1",
    "fam_role": [
        {
            "role_id": 5,
            "role_name": "FAM_TEST_PARENT",
            "role_purpose": "FAM Testing parent role",
            "parent_role_id": null,
            "application_id": 1,
            "forest_client_number": null,
            "role_type_code": "A",
            "child_roles": [
                {
                    "role_id": 6,
                    "role_name": "FAM_TEST",
                    "role_purpose": "FAM Testing",
                    "parent_role_id": 5,
                    "application_id": 1,
                    "forest_client_number": null,
                    "role_type_code": "C",
                },
                {
                    "role_id": 7,
                    "role_name": "FAM_TEST2",
                    "role_purpose": "FAM Testing2",
                    "parent_role_id": 5,
                    "application_id": 1,
                    "forest_client_number": null,
                    "role_type_code": "C",
                },
            ]
        }
    ]
}
```

comments / feedback?

**Comment by franTarkenton** [comment]
Hey @ianliuwk1019... good question...  My understanding is that `FOM Submitter` would be an abstract role, and the various forest client based roles would be concrete roles.  I was thinking `Explorer Co` would be the role name, and `00001234` comes from forest client number??  so the data struct that would feed that page would look like:

``` json
{
    "application_name": "Forest Operation Map",
    "application_description": "What if I told you there was an app...",
    "application_client_id": null,
    "application_id": "1",
    "fam_role": [
        {
            "role_id": 5,
            "role_name": "Fom Sumbitter",
            "role_purpose": "a role that forest client roles would get applied to",
            "parent_role_id": null,
            "application_id": 1,
            "forest_client_number": null,
            "role_type_code": "A",
            "child_roles": [
                {
                    "role_id": 6,
                    "role_name": "Explorer Co",
                    "role_purpose": "FAM Testing",
                    "parent_role_id": 5,
                    "application_id": 1,
                    "forest_client_number": "00001234",
                    "role_type_code": "C",
                },
                {
                    "role_id": 7,
                    "role_name": "East Fraser",
                    "role_purpose": "trees from the east side",
                    "parent_role_id": 5,
                    "application_id": 1,
                    "forest_client_number": null,
                    "role_type_code": "C",
                },
                {
                    "role_id": 7,
                    "role_name": "Supercut",
                    "role_purpose": "mountain needs a mohawk",
                    "parent_role_id": 5,
                    "application_id": 1,
                    "forest_client_number": null,
                    "role_type_code": "C",
                },

            ]
        }
    ]
}
```

Thoughts?

**Comment by basilv** [comment]
So we want the API to list the roles per application. And whether the role is concrete or abstract. We don't care about the child roles, we're letting the user assign to a new or existing child role irrespective of whether it already exists. So I'd propose not including child roles in the API for now. 

For FOM, we'd have the Ministry role as concrete, not under anything, and the Submitter role as abstract, not under anything.

I don't know why the API response includes information on the application - I would assume it should just return the list of roles.

**Comment by basilv** [comment]
Hmm, I knew I was missing something. When we eventually do delegated admin, then we want to know the subset of forest clients the user is authorized to request. But that's different from what you were proposing to return anyways. So I'd say worry about that later (post-MVP), and for now we can just have the API return what we need for MVP.

**Comment by franTarkenton** [comment]
@basilv , so to be 100% certain I'm understanding.. this is what you would like returned?

``` json
[
    {
        "role_id": 5,
        "role_name": "Fom Sumbitter",
        "role_purpose": "a role that forest client roles would get applied to",
        "parent_role_id": null,
        "application_id": 1,
        "forest_client_number": null,
        "role_type_code": "A"
    },
    {
        "role_id": 6,
        "role_name": "Explorer Co",
        "role_purpose": "FAM Testing",
        "parent_role_id": 5,
        "application_id": 1,
        "forest_client_number": "00001234",
        "role_type_code": "C",
    },
    {
        "role_id": 7,
        "role_name": "East Fraser",
        "role_purpose": "trees from the east side",
        "parent_role_id": 5,
        "application_id": 1,
        "forest_client_number": null,
        "role_type_code": "C",
    },
    {
        "role_id": 8,
        "role_name": "Supercut",
        "role_purpose": "mountain needs a mohawk",
        "parent_role_id": 5,
        "application_id": 1,
        "forest_client_number": null,
        "role_type_code": "C",
    },
    {
        "role_id": 9,
        "role_name": "Fom Ministry",
        "role_purpose": "gov user",
        "parent_role_id": null,
        "application_id": 1,
        "forest_client_number": null,
        "role_type_code": "C",
    }
]
```

**Comment by ianliuwk1019** [comment]
Hi @franTarkenton , we don't need to grab information from the **child_roles** json object for the "**Forest Client:** " field on the UI page. That will be through new endpoint to API backend (with Forest Client API integration). For now, that will only be input box (no drop down, until we have the endpoint)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/94cde24b-d388-4b20-aebc-f636685f9c31)

So yes, I feel @basilv 's suggestion on **not** including **child_roles** is what we need (for FOM). But not sure if that will fit into other use-cases... I kind of feel later either frontend or backend will have business logic built-in to code depending on '**Application**' scenarios (I may be wrong).
Initially I was thinking if frontend pass a query-parameter in request url (like 'api_url?**include_child_roles=true'**) would cover something but that probably still needs thoughtful design to see if it is really needed or maybe there is a improved design in datamodel for querying to avoid baking Application specific business into Python (but we don't know the scenarios yet, so we better just do mvp for now).

**Comment by ArogeG** [comment]
Reviewed, I am able to retrieve roles via the FAM Application Role endpoint.

**Comment by ArogeG** [comment]
Reviewed, I am able to retrieve roles via the FAM Application Role endpoint.
