### ISSUE TITLE
FAM data flow map

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1262]
**Describe the task**
Draft a data flow map to understand FAM's flow of data 

**Acceptance Criteria**
- [ ] first draft complete
- [ ] shared with Michelle
- [ ] posted on confluence

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
@OlgaLiber2  
- was this part of sprint 11 or 12?  
- what was the estimate?
- Is there an artifact to link to?

**Comment by OlgaLiber2** [comment]
I think that's a duplicate ticket @gormless87
