### ISSUE TITLE
/fam_application/{application_id}/role_assignment - GET

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#127]
**As a** *Developer* **I want** to be able to call an endpoint **So That** I can have a list of role assignment belongs to the application.

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged into DEV

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/b1c1677d-9056-47b7-8643-1fe1c0d62c7b)

**Comment by franTarkenton** [comment]
hey @basilv / @ianliuwk1019, This is a proposal for what I think the return json should look like for this endpoint... comments appreciated!

```json
{
    "application_name": "test app",
    "application_description": "a really good app",
    "application_client_id": null,
    "application_id": 1,
    "fam_role": [
        {
            "role_name": "FAM_ADMIN",
            "role_purpose": "FAM Admin",
            "parent_role_id": null,
            "forest_client_number": null,
            "role_type_code": "C",
            "fam_user_role_xref": [
                {
                    "user_role_xref_id": 1,
                    "user_id": 1,
                    "role_id": 1,
                    "user": {
                        "user_type_code": "B",
                        "cognito_user_id": "22ftw",
                        "user_name": "Mike Bossy",
                        "user_guid": "dd6f86d2-d976-4ceb-8db8-d57f52ccc6b6",
                        "create_user": "Al Arbour",
                        "update_user": "Al Arbour"
                    }
                }
            ]
        }
    ]
}
```

**Comment by ianliuwk1019** [comment]
Thanks Kevin. I forgot if it is easy to ignore fields in Python for response json object; Some fields 'application_client_id', 'user_guid', 'create_user', 'update_user' probably will not be useful.

**Comment by franTarkenton** [comment]
@ianliuwk1019 if you want me to include those fields it can be done?  Let me know what your preference is?

**Comment by ianliuwk1019** [comment]
@franTarkenton , I don't feel we need those fields for api so was wondering if it can be done easily from FastAPI. I don't meant to include these fields.

**Comment by franTarkenton** [comment]
role assignment end point has been created and functionality is now merged with ,main.

Remaining work:
* add some assertions to verify that get role assignments by application are working correctly
* refactor for sonar safe variables
* refactor for consistent fixture names across test suite
