### ISSUE TITLE
Store and update business guid when create the user

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1270]
**Describe the task**
For business bceid user, when we grant them access or add them as delegated admin, we need to store their business guid. So even they never login to any FAM applications, we can still have their business guid, and will only return their information to the delegated admin from same organization. 

**Acceptance Criteria**
~~- [ ] Update api `create_user_role_assignment`, and `create_delegated_admin` to validate the user by user_guid, and get the business_guid~~
- [x] Update api `create_user_role_assignment`, and `create_delegated_admin` to store business guid for business bceid user when create the user, or update the business_guid if user already exists (business_guid shouldn't be changed? this will be the case that we add business_guid for existing business bceid users in our database which didn't record that in the past)
- [x] Update the router guard where we verify the business_guid to search user by user_guid, not by user_name
- [x] Update tests

**Additional context**
- Need to do #1285 first, to let frontend pass the user_guid to the api calls
- may require a second pass to implement testing fully

**Comment by MCatherine1994** [comment]
Hi @basil, just thinking ahead, later we'll work on another ticket to store user's guid as well when create the user, then feel it will be simpler to still do a search (validation) by user name and type on backend, and grab both user guid and user business guid (if has), and store them. And no need to pass business guid or guid from frontend anymore. How you feel about this?

**Comment by basilv** [comment]
Well, later we might have the user be able to do a search by user's first/last name on front-end and pick a specific account. Also, since the user name can be changed at any time, the safest option is to use user guid to pass to backend.

**Comment by MCatherine1994** [comment]
> Well, later we might have the user be able to do a search by user's first/last name on front-end and pick a specific account. Also, since the user name can be changed at any time, the safest option is to use user guid to pass to backend.

oh yeah... I agree, that's good point, thanks!!

**Comment by ianliuwk1019** [comment]
Also create a ticket to improve backend tests: #1358 .
