### ISSUE TITLE
Frontend hide user domain when bceid user grant access

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1282]
**Describe the task**
When a delegated admin is business bceid user, and when tries to grant user access, hide the user domain selection, and the user domain will be business bceid. Business bceid delegated admin can only grant access to business bceid user from the same organization. 

**Acceptance Criteria**
- [x] Hide the user domain option on the grant access page when the login user is business bceid
- [x] Set the user domain form data to business bceid
- [x] Check/Update tests

**Additional context**
- at this point we do not have scenarios where a BCeID will add an IDIR user therefore that option should be removed for BCeID delegates

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/1232b4dc-8378-4d6c-a70c-709ad36ff3b0)

**Comment by ianliuwk1019** [comment]
Verified in Dev. Looks good.
