### ISSUE TITLE
FAM support FOM production bceid login loop back error

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1293]
**Describe the task**
FOM reports a bceid login issue:
<img width="939" alt="Screen Shot 2024-04-09 at 9 41 46 AM" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/26bfc933-751a-4d69-9229-5d57f55c73b3">

Checked the AWS PROD Cloudwatch Auth Lambda log, found an error for the audit log when try to get the business guid

<img width="1439" alt="Screen Shot 2024-04-09 at 9 34 42 AM" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/e698efba-a70f-49a4-9a4c-cf5162f2c496">

Tested with my prod business bceid account, and it works fine. So the error could happen when the login user doesn't have a business_guid somehow, we need more investigation on that. Cause we'll need the business_guid for checking organizations later, we expect the business bceid login user should have a business_guid (Updated: the error is not caused by login user doesn't have business_guid, it's because we didn't configure it to be returned from Cognito, see the note below in the additional context)

<img width="923" alt="image" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/ad13267e-1c02-4c4b-9389-d35081fc2b59">

**Acceptance Criteria**
- [x] Quick fix, remove the audit log for business guid
- [x] Update the auth lambda audit log to use "get" for optional attributes that not all applications are configured 
- [x] Add test to check the different log 

**Additional context**
- Business bceid user should have a business guid returned from login, but we have the read/write permission configured for each application integrated with FAM, and only FAM enabled to return the business_guid. So if I login to FAM with my business bceid already, Cognito already has my business_guid, so my login to FOM works as well. But for other bceid users, FOM is not configured to return the business_guid, so our Auth Lambda audit log won't be able to find the `custom:idp_business_id`
- Or here

**Comment by ianliuwk1019** [comment]
Would it be useful trying these failing users' BCeIDs (from different organizations) on our prod IDIM-Proxy swagger and see what's the return (the user type and if it contains business GUID)?

**Comment by MCatherine1994** [comment]
Verified the business bceid user through IDIM web service, and they have business_guid. And the detail of the cause can be found in the ticket description. 

Deployed the quick fixes to prod at v1.14.1, confirmed from Julius the bceid login works now.
