### ISSUE TITLE
Enable the entry of multiple forest client numbers with or without space after the comma

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1307]
**Describe the task**
Currently there is only one correct format to enter multiple forest client numbers: 
00001011,00001012

We need to enable the entry of multiple forest client numbers with or without space after the comma so it is less prone to user error: 
00001011, 00001012

Both ways should be valid. 

**Acceptance Criteria**
- [x] Either entry format (comma followed by a single space or no space) works
- [x] Update/create tests if need

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
@J0taFerreira  - adding this to sprint 12
