### ISSUE TITLE
FAM load testing - phase 1

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1321]
**Describe the task**
Perform level 2 testing 

**Acceptance Criteria**
- [x] Topic documented in Confluence  -what are the levels (1,2,3), objectives, tools and process description
- [x] Plan for load testing - performance risk assessment, user/role volume calculation, responsiveness requirement for login, etc.

--Split out to new ticket:
- [ ] Generate Realistic user/role volumes
- [ ] Test UI responsiveness based on bigger user/role volumes
- [ ] Demo / pair with team

**Additional context**
- Good topic for internal demo and/or FDS demo

**Comment by MCatherine1994** [comment]
Confluence documentation: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Load+Testing
