### ISSUE TITLE
Refactor sidenav component for hidden items

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#1324]
**Describe the task**
The sidenav component should be refactored so the hidden items are not rendered in DOM. Currently the elements are rendered with the CSS set to `display:none`. The ideal scenario is to not render any items that are not being displayed.

**Acceptance Criteria**
- [ ] Frontend not rendering in DOM the items that should not be displayed.
- [ ] Check if it doesn't break any tests.

**Additional Context**
![Image](https://github.com/bcgov/nr-forests-access-management/assets/117364634/b9ebc6e8-1b99-46d8-a691-d844ccfa0dd0)

**Comment by craigyu** [comment]
sub menu item removed #1650
