### ISSUE TITLE
UI - update profile to look like the SPAR profile

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1328]
**Describe the task**
Make the buttons clickable not just on the text/icon, there's no on hover indication as well

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/1976b787-805f-404b-8846-ca3729e5e547)

**Acceptance Criteria**
adjust design to reflect the carbon design system: 
- [x] Make the buttons clickable not just on the text/icon 
- [x] Add on hover indication
- [x] Adjust the style on profile to align it with SPAR
- [x] remove the word "options"
- [x] decrease the width of the component (make the same width as SPAR) --> For the profile SPAR has width of 25 rem, which is 25*16 = 400px, for screens smaller than 400px it takes 100vw

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by OlgaLiber2** [comment]
looks good. I'm closing the ticket.
