### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1330]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] Bug fixed and FAM behaves as expected 

**Additional context**
Bug: Craig had entered a bunch of permissions in Fam for Matheus and Ricardo, however when I logged in, the list under manage permissions did have them. When I tried to provide them with access, I got the message in the top right hand corner that I didn't have the right permissions. What I did was cleared my cache, refreshed the page and then the table with the new permissions updated.

Might be that  when another users enters data, we need to clear the cache to see it.

**Comment by OlgaLiber2** [comment]
might be related to ticket 1460 https://github.com/orgs/bcgov/projects/65?pane=issue&itemId=68215422

**Comment by craigyu** [comment]
will probably get solved with #1612
