### ISSUE TITLE
Remove "idir" domain option for BCeID delegate

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1335]
**Describe the task**
Remove "idir" domain option for BCeID delegate

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- at this point we do not have scenarios where a BCeID will add an IDIR user therefore that option should be removed for BCeID delegates

![Image](https://github.com/bcgov/nr-forests-access-management/assets/121979429/1232b4dc-8378-4d6c-a70c-709ad36ff3b0)

**Comment by MCatherine1994** [comment]
close as duplicate as #1282
