### ISSUE TITLE
FAM frontend 403 error

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1338]
**Describe the task**
Craig found an issue that he's trying to add a few roles assignments and suddenly he can't do anything anymore,  he still seems "logged in" FAM, but can't perform any action. Refresh doesn't help. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/a45736bd-dee1-430a-8774-7a39352fb8b1)

**Acceptance Criteria**
- [ ] Investigate the 403 error 
- [ ] second
- [ ] third

**Additional context**
- The access token should expire in 5min, but it should auto refresh if the user refresh the page or go to a new route

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/42896f3e-83b9-4c79-ac4f-17b6be36280c)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/6f4b4cd4-5b74-4a44-a776-fcd9712a1a35)

**Comment by MCatherine1994** [comment]
Checked cloud watch API Lambda log, after user login 5 mins, backend can't find the requester by cognito_user_id anymore...

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/ee63c881-13ad-4872-b1aa-002b5bb16b6c)



![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/a735d055-3093-4b76-881b-84e17d7981dc)

**Comment by ianliuwk1019** [comment]
Hi @MCatherine1994 , I am looking at SqlAlchemy doc for "[engines](https://docs.sqlalchemy.org/en/20/core/engines.html#configuring-logging)".
Perhaps these two might be helpful to be enabled if the issue does need to be investigated deeper:
- "**echo_pool**" 
   ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/4f1c473c-efdc-434b-8e59-1876e7d527a9)

- "**pool_pre_ping**"
   ![Image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/fe9a122f-0ae3-4b06-8a79-f3893d05052b)

**Comment by MCatherine1994** [comment]
By checking the log, it returns a "ROLLBACK", wondering if the db session got some exception, will add a log here. Also some reading https://stackoverflow.com/questions/64763770/why-we-use-yield-to-get-sessionlocal-in-fastapi-with-sqlalchemy and an example to create a db session using FastAPI and SqlAlchemy https://github.com/tiangolo/fastapi/issues/6006

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/c8f3edb2-a7c3-4989-b4a6-03d08118953f)

**Comment by MCatherine1994** [comment]
Sqlalchmey has a connection pool mechanism by default. So in the get_db() method, we'll get a session for each single request. [Using "yeild"](https://stackoverflow.com/questions/64763770/why-we-use-yield-to-get-sessionlocal-in-fastapi-with-sqlalchemy) so the `db.close()` will be called after finish all queries. When call `db.close()`, it doesn't mean the session is completely removed. It actually gives the connection back to the connection pool of Engine and doesn't close the connection, the session can be used again. [The default connection pool size is 5.](https://docs.sqlalchemy.org/en/20/core/pooling.html) It's also possible that in the busy time, we need more than 5 connections simultaneously.  



Reference:

https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.close
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/cc58805c-7549-40f7-9b00-700a4030efdc)


https://stackoverflow.com/questions/21738944/how-to-close-a-sqlalchemy-session
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/51497213-e930-4937-84b6-645ebf1b8a15)

**Comment by MCatherine1994** [comment]
Set up the AWS Prod CloudWatch for the **DatabaseConnections** for RDS proxy `fam-cluster-fam-api-proxy-api` and database cluster, but need more understanding of how to read the graph, and this might be not related to the sqlAlchemy connection pool size. The maximum number of connections allowed to an Aurora DB instance is determined by the max_connections parameter:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Performance.html#Aurora.Managing.MaxConnections
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Managing.html#AuroraPostgreSQL.Managing.MaxConnections

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/af277caf-060c-4491-9ba3-b278a0edb28c)


CloudWatch Dashboard in PROD for data in the past 3 month:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/99580f25-4c45-4156-9e92-2aa107034d3d)


CloudWatch Dashboard in TEST for data in the past 3 month:
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/963a3075-4e8c-480a-8cff-df4a504d1e51)



Will keep trying to see if can get this 403 error again in the future.
