### ISSUE TITLE
Frontend tab disappear on phone screen

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1371]
**Describe the task**
Adjust the styling for tab on small screen

**Acceptance Criteria**
- [x] Fix the style for tab on small screen in the common theme repo

**Additional context**
- ![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/278c6ad8-3402-405f-8cd5-33eaa1ef5be1)
- ![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/dc211a3f-d151-4a5b-9944-c78808559444)

**Comment by J0taFerreira** [comment]
Hello!What should be the smallest screen size for the design? 
How the tab should be displayed? 
fyi the table is not optimized for mobile
@MCatherine1994 @OlgaLiber2

Something like this? 
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/cfbbdaa2-d763-4aab-9d16-80fdd5fa7d8c)

or this?
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/c1826d1f-6e08-4783-bf2c-0fadaf7ff20f)

**Comment by ianliuwk1019** [comment]
Verified in Dev and works for smaller screen (360).
