### ISSUE TITLE
Improve the loading behaviour for the frontend tables

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1402]
**Describe the task**
While loading data, the frontend table loading state is not looking good. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/7860360e-1f5b-4277-a9e6-d403c1a2c16d)

**Acceptance Criteria**
- [x] default Prime Vue loading implemented for all tables
- [x] customizations (wording "Loading .. please wait") removed

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by J0taFerreira** [comment]
Primevue table have a prop for load that we can use a spinner or Skeleton both provided by primevue as well.
https://primevue.org/datatable/#lazy_load

https://primevue.org/progressspinner/
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/aeee0542-c658-4ae5-ac6f-79e3de338dd7)

https://primevue.org/skeleton/
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/d1dceb2d-9fd6-46fa-8d4d-491674e9776f)
