### ISSUE TITLE
Handle the case that IDIR and BCeID cannot lookup for self

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1436]
**Describe the task**
There is no user_guid, business_guid and email information returns when business bceid users try to lookup for themselves. Already sent email to ask that case, but we might need to change the logic so we can display the user information when the busniess_guid is none, but username is same as the requester. 

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/0d497b49-455c-48ad-8e29-fa3a11f45348)

**Acceptance Criteria**
- [ ] Error message mockup -indicate user cannot grant access to self
- [ ] Implement error handling -frontend only; block backend call
- [ ] 

**Additional context**
- Based on user type code and username
-

**Comment by MCatherine1994** [comment]
fyi, the current error message doesn't make sense. Because we can't get the business_guid for self, it will be treated as different organization. 
![Image](https://github.com/user-attachments/assets/02383432-cb96-42cd-800d-b3d58ff5fb20)

**Comment by OlgaLiber2** [comment]
I looked into this more and for now we can change the text to "You cannot grant permissions to yourself". We can change the styling when we work on the new FAM designs. 
@Kghiya no more action is needed :) 
@MCatherine1994 @ianliuwk1019

**Comment by craigyu** [comment]
will handle this on the frontend

**Comment by craigyu** [comment]
more of a cup of tea ticket
