### ISSUE TITLE
BUG: token expire will return frontend server error

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1460]
**Describe the task**
Sabina reports an error when she tries to grant Kevin access in FAM.

- login to SPAR TEST 
- open new tab and login to FAM
- get errors
- refresh FAM
- try again get errors
- close the entire window and clear cache
- come back to FAM
- try to verify Kevin in FAM, but got the error
- tried again and it worked
- then tried Krista Copeland and got error

Login to SPAR and FAM both with IDIR

Check the PROD Cognito log, and found a jwt expired error. So when user logs in more than 5mins, and try to verify the user, we probably don't do an auto refresh of the token, so backend can't validate the token. But need to check when we auto refresh token.

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/3d9b012b-5af2-401c-a5db-3edb6074fa66)

**Acceptance Criteria**
- [ ] Investigate when and where we auto refresh user tokens
- [ ] Handle the situation when user token expired

**Additional context**
Investigation ticket
![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/aa2292d0-89eb-44f6-b6f2-dc7c82cacfe5)

**Comment by gormless87** [comment]
Solved as par of #1610
