### ISSUE TITLE
Handle error case when email sending failed

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1471]
**Describe the task**
Add error handling for failed email

**Acceptance Criteria**
- [x] When email fails to send, display notification in frontend

**Additional context**
- error could be from GC Notify bad email address
- relates to #799 and #1469
- ticket #1532 is created to follow up for frontend to be able to display multiple notification messages for a type

**Comment by MCatherine1994** [comment]
![Image](https://github.com/user-attachments/assets/ffe9998b-442a-4704-b54c-fbe84068e83c)



![Image](https://github.com/user-attachments/assets/c45c8bd7-1558-4f76-bc4e-78c8d4301b57)

**Comment by MCatherine1994** [comment]
We are using Trail version and team key, so it can only send email to our team members or the safelist people. So we have to request go live and setup the limits.

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 would you mind add the frontend general email sending failure error message text here from the mockup or the link to it? Thank you very much!

**Comment by ianliuwk1019** [comment]
Also will change email templates to reflect:
* not show word "**for the following organizations**" when granting concrete role such as fom_reviewer.
@OlgaLiber2

**Comment by OlgaLiber2** [comment]
@marina-carvalho can you help Ian with the error mockup please?

**Comment by marina-carvalho** [comment]
Sure, @ianliuwk1019 Here's the link to the mockup with the error message: https://www.figma.com/design/WhDujL6e0lkgpno740BZBx/Manage-and-add-permissions%3A-Application-admin?node-id=3061-126007&t=YXh6qnJSubTHpIP6-4

**Comment by ianliuwk1019** [comment]
> Sure, [@ianliuwk1019](https://github.com/ianliuwk1019) Here's the link to the mockup with the error message: https://www.figma.com/design/WhDujL6e0lkgpno740BZBx/Manage-and-add-permissions%3A-Application-admin?node-id=3061-126007&t=YXh6qnJSubTHpIP6-4

Hi @marina-carvalho Thank you very much! But I seem to have no permission to the link. It asks me to send you request and I did.

**Comment by marina-carvalho** [comment]
@ianliuwk1019 can you try again, please?

**Comment by ianliuwk1019** [comment]
Hi @marina-carvalho I can view them now, thanks for granting me access!!

**Comment by ianliuwk1019** [comment]
Although the mockup text: "failed to send email to [[email@address.com]]:
![Image](https://github.com/user-attachments/assets/dbf0948c-8938-4a00-aa43-cad8f10c86bf)

Currently the component only knows the ID(username), use it to display for now, hope it still make sense:
![Image](https://github.com/user-attachments/assets/914ad356-bf6c-4b22-bd48-540b99409ec3)
[although possible to know email (if exists) from user search, but need a bit work on changing other components at frontend]
@OlgaLiber2

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 I think for this iteration we can include whatever data we have. Can you add tickets for the things that we are missing and we need to work on, for example a ticket to make the user email show in the error message.

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2, spent little time for it, now it is displaying email in error message now. No ticket is needed.

**Comment by ianliuwk1019** [comment]
Sent GCNotify contact us email to ask if it is possible to remove logo, hope getting response in few days.

**Comment by OlgaLiber2** [comment]
That's great! Thank you @ianliuwk1019!
