### ISSUE TITLE
Display "email" for verified user information.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#1480]
To be able to cross reference the user search, we like to include "email" field (other than first name and last name) on search result at "Verified user information".
![image](https://github.com/user-attachments/assets/603c49b6-e871-4db9-b4a2-40abbc41fa87)

**Acceptance Criteria**
- [ ] "email" included at FAM backend search result return.
- [ ] Recreate api-client for frontend if necessary.
- [ ] Add "email" to frontend "Verified user information" searched result (IDIR/BCeID).
- [ ] Adjust tests if necessary.

**Additional Context**
- enter text here

**Comment by craigyu** [comment]
Done in #1650
