### ISSUE TITLE
Support SILVA: add silva roles

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1482]
**Describe the task**
Create silva roles as requested. 

**Acceptance Criteria**
- [x] Remove the existing test roles (which were created when initially onboard SILVA for them to play around) for SILVA
- [x] Create SILVA roles with role name, role type and purpose
- [x] Add new roles to all env, SILVA_DEV, SILVA_TEST and SILVA_PROD

**Additional context**

Roles: 

Viewer: View Silva data for assigned clients or organizational units.
Submitter: View and update Silva data, including activity reporting and milestone declarations.
Approver: Review and approve or reject submissions on behalf of the Minister or designate.
Planner: Conduct planning and managing activities for government-funded programs.
Admin: Manages Silva data and performs administrative tasks.

![Image](https://github.com/user-attachments/assets/9ca0ad1a-2f1f-4208-9b23-d324c3656134)

**Comment by OlgaLiber2** [comment]
@MCatherine1994 roles and definitions have been verified with Caroline.

**Comment by OlgaLiber2** [comment]
Tagging @jazzgrewal so he knows when the roles are set up.
