### ISSUE TITLE
Technical design for access by org unit

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#1484]
**Describe the task**
Confluence page with technical design including data model, components, work breakdown. 

**Acceptance Criteria**
- [x] Confluence page created
- [x] Review session with team
- [x] Data model reviewed with Michelle Douville
- [x] Data model reviewed with Chantelle Abanilla
- [x] Data model reviewed with architects

**Additional context**

**Comment by OlgaLiber2** [comment]
I spoke with Michelle and Chantelle following our team meeting and here are the next steps we should take, we can create a new ticket for that: 
- Find out how FTA uses access by org unit (they only assign org units not attached to a client number, how does it work on the backend?) 
- Talk to Sabina and Caroline if we stay on the current data model, does assigning org units via client numbers satisfy the scoping requirements for SPAR and Silva in the long term? 
- Draft an architectural response doc weighting option 1: staying with the current data model, and option 2: moving to a new data model. Analysis and what are the pro and cons of each option. use this template: https://apps.nrs.gov.bc.ca/int/confluence/display/AR/0000-00-00+ARD+Template , or something similar to this: https://github.com/bcgov/nr-silva/wiki/2.-Decision-Log#geospatial-tool-for-silva---react-leaflet-vs-maplibre

@basilv

**Comment by basilv** [comment]
@OlgaLiber2 I've confirmed via Anne-Marie and your talk with Chantelle that FTA requires access by org unit for at least districts, so we'll eventually need that feature in FAM its just a question of when.

The architecture response document then is more of a question specifically for SPAR/SILVA, not for the enterprise overall, and doesn't really impact what FAM needs to do. (That is, irrespective of whether SPAR/SILVA move to that design, FTA will use it.)

**Comment by OlgaLiber2** [comment]
@OlgaLiber2 do we need access by org unit for FOP?
