### ISSUE TITLE
Allow verifying test forest client numbers in FAM Prod for Test APPs

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1488]
**Describe the task**
Currently our FAM production only allows searching production forest client numbers (cause it's only connected with production Forest Client API). However, for the application integrated with FAM, their DEV and TEST environments are also integrated with our FAM production, we need to allow them to verify and add test forest client umbers to their APP in test environment. For example, we should allow Sabina to verify a test forest client numbers and grant access for SPAR TEST using FAM PROD. 

Currently since forest client has same number in TEST and PROD, we didn't notice the issue. But the status could be different. For example, the test forest client number 00001011 is active in test env, but inactive in prod env.

**Acceptance Criteria**
- [x] Update admin management to allow verifying forest client numbers to use the api url based on app env 
- [x] Update backend to allow verifying forest client numbers to use the api url based on app env 

**Additional context**
- follow up on #1481

**Comment by ianliuwk1019** [comment]
When working on this ticket and ticket #1481 (IDIM user search), we had some discussion for the confusion of how to identify which application environment (dev,test/prod) is the user intended to search from (IDIM Test/PROD or Forest-Client Test/Prod).
Although initially application_env was passed from frontend to backend endpoints, later we decided to pass "**application_id**" to endpoints and let backend to find the "application_env" from database.
