### ISSUE TITLE
View All Users and their roles on an Application

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#149]
As a an application access administrator I want to view all users  on an application So That  I can review the list of users and roles
Additional Context
-- Access administrator should be able to view list of users and associated roles provisioned for users.
--Access administrator should be able to search for users by BCeID or IDIR,  Forest Client ID, Forest Client and Roles
--Results should be displayed in a table format

---For Future Consideration:

Acceptance Criteria

 
Definition of Done

 Ready to Demo in Sprint Review
 Does what I have made have appropriate test coverage?
 Documentation and/or scientific documentation exists and can be found
 Peer Reviewed by 2 people on the team
 Manual testing of all PRs in Dev and Prod
 Merged

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/0edce48b-fc11-4bbe-9723-d3c4b07947a7)

**Comment by ArogeG** [comment]
Tested this, works as expected. @basilv are you still working on this?

**Comment by basilv** [comment]
No, yesterday I fixed the defect you reported during standup, and Nick has approved the PR and I've merged, so this is done.
