### ISSUE TITLE
Refactor POST user role assignment api to support multiple forest client numbers

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1511]
**Describe the task**
Currently when we grant user access with multiple forest clients numbers, we call the Backend API multiple times. But we don't want to send notification email multiple times, update the Backend API to support multiple forest client number in one api.

**Acceptance Criteria**
- [x] Backend update post user role assignment api to support grant access with multiple forest clients numbers
- [ ] Update/add backend tests if need
- [x] Frontend update form data to support multiple forest client numbers
- [x] When submit the form, make one api call with the updated api

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by OlgaLiber2** [comment]
option to send email is at the bottom of the screen 
@MCatherine1994 @ianliuwk1019 

![Image](https://github.com/user-attachments/assets/a9d02738-f8d9-4b63-aad1-165a27696645)
