### ISSUE TITLE
Display error/next steps when clicking login and "OAuth responses require a User Pool defined in config"

### ISSUE THREAD

**Issue by mbystedt** [bcgov/nr-forests-access-management#1516]
**As a** *user* **I want** *login* **So That** *I can use the tool*

**Additional Context**
- Not formally onboarded to FAM

**Acceptance Criteria**
- [ ] Given I click on login, When request sent, Then UI should reflect this (disable button, show spinner, etc.) 
- [ ] Given I don't have access, When the login result ends in an error, Then I should know how to resolve it.
- [ ] Given I go to the login page, When I search for information about the tool, Then I should know how to find it.
- [ ] Given I go to the login page, When click on things that look like links , Then it should navigate. (Re: "Forests Access Management" looks like a link)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by OlgaLiber2** [comment]
thanks for bringing this up @mbystedt. At this time we will not action the request since we are still working through high priority items.
