### ISSUE TITLE
Publicly available landing page with login button

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#152]
**As an** Application Access Manager **I want** a publicly available login page** So That** I can login to FAM

**Additional Context**
--use VUE!
--UX style will be BC Gov bootstrap theme
--No integration with anything at this point 
--Cloudfront for static files (as in Cloud Pathfinder (SEA) sample apps )
--GHA builds and publishes files to Cloudfront using Terraform https://github.com/bcgov/startup-sample-project-aws-serverless
--Deployment completed in #165
-- Find an existing Vue app to plagerize
-- link to bootstrap theme:
   * https://github.com/bcgov/forestry-bootstrap-theme
   * https://github.com/digitalspace/bcparks-bootstrap-theme

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by ianliuwk1019** [comment]
Package '[bootstrap-vue-3](https://cdmoro.github.io/bootstrap-vue-3/getting-started/)' (Bootstrap 5/Vue3) is still in alpha version and not production ready. We can include that later when we see a need.

Also bcgov '[bootstrap-theme](https://github.com/bcgov/bootstrap-theme/releases/)' also isn't truly using Boostrap 5 (it is using bootstrap@~4.3.1) either. Installing it with bootstrap 5 will have npm error. So, for now, will not import from this theme package.

For now, I am thinking to just individually install Bootstrap 5 first and go from there to create our layout page and hoping we don't have too much difficulty using it for vue components.

**Comment by basilv** [comment]
Another option would be to fork bcgov bootstrap-theme and upgrade to Bootstrap 5. Maybe Michelle knows who supports BCgov bootstrap theme?

**Comment by ianliuwk1019** [comment]
Hi @ArogeG I move this ticket to In Review. Do have time so I can quickly show you for part of the done process for this ticket before Sprint Review?
Thanks.

**Comment by ianliuwk1019** [comment]
Hi @ArogeG I move this ticket to In Review. Do have time so I can quickly show you for part of the done process for this ticket before Sprint Review?
Thanks.

**Comment by ianliuwk1019** [comment]
Merged to main branch today.

**Comment by ianliuwk1019** [comment]
Hi @ArogeG , I think this is the current frontend deployed on AWS https://d14evo4qtbdgsm.cloudfront.net/index.html. (Please ignore the 'Junk'. Probably Conrad was testing).

**Comment by ArogeG** [comment]
Thanks Ian, I'm hoping further iterations will clean up the response from the API call. Closing this ticket now.

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/9d35fdbc-f065-47ae-95ee-e81a664bdaf2)
