### ISSUE TITLE
Slow performance on initial login

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#1523]
On login to FAM, after credentials are entered and navigation to the FAM callback URL starts, there's a long delay before anything is displayed (just see a blank screen). 

LIkely cause is that if there is an application selected by the user previously, we try to load the user role assignments before entering the router and the screen stays blank while that loading happens.

Suggest loading in background and not blocking rendering - even if it is just to display a loading screen.

**Comment by craigyu** [comment]
Should be done in #1650
