### ISSUE TITLE
Add capability for frontend Notification component to display multiple messages

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#1532]
Current Frontend notification design does not have capability to show messages with the same types on ManagePermission page (on top of user-role table).
For example, for type 'error', with multiple errors to be shown, one will override the other, depending on which one would be later to add to the notification state object.

We need that showing multiple messages for the same type capability, such as displaying granting error + email not sent error.

**Acceptance Criteria**
- [ ] Change notification state to handle multiple messages for a type.
- [ ] Implement capability to be able to show multiple messages on UI (ManagePermission screen). Might need to talk to Olga how we like to see the order of the different types of messages.
- [ ] Refactor/adjust several components for existing pushing to notification logic.
- [ ] Adjust component testing if required.
- [ ] Make sure scenarios work: single message type with single/multiple messages; muti-message types with single/multiple messages.

**Additional Context**
- ![image](https://github.com/user-attachments/assets/01591cc4-8140-44d7-8844-2f0c8b747c65)
- Current notification state:
![image](https://github.com/user-attachments/assets/601cda34-ee6f-4529-8625-00de14d1b7e2)

**Comment by craigyu** [comment]
done in #1650
