### ISSUE TITLE
Design for the audit table

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1533]
**Describe the task**
Design the audit table, work on the data model. https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Audit+History+Design?

**Acceptance Criteria**
- [ ] Document the design in the confluence page
- [ ] Come up with the data model

**Additional context**
- Epic story 1 #1534
- Or here

**Comment by ianliuwk1019** [comment]
Hi @basilv , thank you so much, as always, for the very detail architectural design for us!!
I do have few questions/wondering:
* Initially when reading the **privilege_details** column (json), for the "**privilege_type**" I almost got it mixed with "**privilege_change_type_code**".

  `privilege_change_type_code`: **Grant**, **Revoke**, or **Update**
  `privilege_type`: (**END_USER**, **DELEGATED_ADMIN**, **APPLICATION_ADMIN**)

  Do you feel "**privilege_change_action_type_code**" would be a little clear?
  
* Wonder why **application detail** isn't in the "**privilege_details**" jsonb column and is as a foreign key column?
  Is `application_id` as a foreign key is to support the notion that UI is always based on **application selected** first and also it is convenient to be able to do **filter** on the UI (if need to)? 
If the UI is based on the "**user**" selected first and to display the audit history for all permission changes on that user with information in "privliege_detail" to display role change along with which application it got changed on (the user might have privilege changes on different applications), then it might need extra effort to display these information.
Or, can we both have application_id as foreign key and also application information in the "privliege_detail" jsonb?
  
* Wonder why "**change_performer_user**" has both `user_id` column and `user_details` columns but "**change_target_user**" only has `user_id` column in audit table?

Thank you Basil!
