### ISSUE TITLE
Store audit records when granting/removing user access

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1538]
**Describe the task**
Store the audit records when granting and removing user access to an application

**Acceptance Criteria**
- [x] Update the existing create user role assignment api to add the record in audit table when granting access
- [x] Update the existing delete user role assignment api to add the record in audit table when removing 
- [x] Add the forest client name when create the audit record, for creating user role assignment, we already verify forest client number, so we can get the forest client name. For deleting, we need to search the forest client number as well, if we can't find, then either return unknown forest client name or fail the transaction.
- [ ] Add tests (adding and removing)

**Additional context**
- Epic story 1 #1534 
- Error handling - if an error happens the transaction rolls back 
- Create one audit record when granting access with multiple organizations

**Comment by ianliuwk1019** [comment]
The `create_user` is a string/varchar type (100), other than "admin" user, it it intended to store the value as change_performer's `user_name`? 
![Image](https://github.com/user-attachments/assets/82b9a6b5-2014-442b-be5e-84ca82a8e581)
@basilv

**Comment by basilv** [comment]
Yes, Ian that's correct.
