### ISSUE TITLE
Data migration to add audit records for the existing user role assignments

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1539]
**Describe the task**
Data migration to add audit record for the existing user role assignments. Need to think about if ignore or need a way to handle the records have been done through a batch upload. For the user role assignments that have been done through the batch upload, the create_user column in the database will show the lambda user (need to double check).

**Acceptance Criteria**
- [ ] Create the data migration script to add audit record for existing user role assignments
- [ ] Handle the situation when create_user is a system user (db user or lambda user)
- [ ] Add the forest client name to the table if the role has forest client numbers (could run a sql data migration first to get the records, and then an api to update the forest client name)
- [ ] add client number names for all records
- [ ] migration script should be based on cut-off time before new audit feature is deployed.

**Additional context**
- Epic story 1 #1534
- Might need logic details
- only add creation of records

**Comment by gormless87** [comment]
Based on team discussion, decision made to NOT complete this task. Adding a new issue to  add 'audit record not available' message for historic.
