### ISSUE TITLE
IDIR integration to FAM frontend

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#154]
**As an** Application Access Manager **I want to** login to FAM with my IDIR **So That** I can provision application access

**Additional Context**
-- OIDC login using Cognito

**Acceptance Criteria**
- [ ] Given the user has an IDIR, When the user attempts to login, Then the FAM Welcome page will be displayed (including the login username)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged

**Comment by ArogeG** [comment]
Duplicate ticket with more details created in 260.
