### ISSUE TITLE
Store audit records when granting/removing delegated admin access

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1545]
**Describe the task**
Store the audit records when granting or removing delegated admin access. 

**Acceptance Criteria**
- [x] Update the existing create access control privilege api to add the record in audit table when creating a delegated admin
- [x] Update the existing delete access control privilege api to add the record in audit table when removing some access for a delegated admin
- [x] Add the forest client name when create the audit record, for creating access control privilege, we already verify forest client number, so we can get the forest client name. For deleting, we need to search the forest client number as well, if we can't find, then either return unknown forest client name or fail the transaction
- [x] Add tests

**Additional context**
- Epic story 2 #1549
- Create one audit record when create delegated admin with multiple organizations

**Comment by ianliuwk1019** [comment]
At this ticket, the frontend user permission history page is also minor adjusted to show delegated admin content for role change.
After this ticket is done, we can also close #1546 , #1548.
