### ISSUE TITLE
Update the api for returning user access history to include delegated admin history

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1546]
**Describe the task**
Update the api for returning the user access history to also include user's delegated admin access history

**Acceptance Criteria**
- [ ] Update the api for returning user access history to also include user's delegated admin access history for the selected user and application
- [ ] Only application admin of the selected application is able to make the api call
- [ ] Regenerate the client-code for frontend if the return data schema changed
- [ ] Test this scenario

**Additional context**
- Epic story 2 #1549
- Or here

**Comment by ianliuwk1019** [comment]
It seems this ticket probably is outdated and won't do.
