### ISSUE TITLE
Update frontend user access history table to support delegated admin history

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1548]
**Describe the task**
Update frontend user access history table to support user's delegated admin access history

**Acceptance Criteria**
- [ ] Update the table to support delegated admin access information
- [ ] Update the component testing for the user access history page to test the delegated admin access information
- [ ] third

**Additional context**
- Epic story 2 #1549
- Or here

**Comment by ianliuwk1019** [comment]
Minor adjustment is done at ticket #1545 for showing delegated admin audit history.
This ticket is not necessary anymore.

**Comment by craigyu** [comment]
done in https://github.com/bcgov/nr-forests-access-management/issues/1619
