### ISSUE TITLE
Update RDS certificate

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#1555]
**Describe the task**
We got the email that our existing RDS certificate ‘rds-ca-2019’ will expire on August 22, 2024.

**Acceptance Criteria**
- [x] Update the RDS certificate in AWS DEV, TEST and PROD

**Additional context**
- Email notification we got: [RDS_TLS_certificate_update_email.pdf](https://github.com/user-attachments/files/16696208/RDS_TLS_certificate_update_email.pdf)

- Steps to update the certificate:
  - Click **Modify** for the cluster 
  - Update the certificate from the dropdown
  - Make sure to select "Apply immediately" if this is an urgent fix

![Image](https://github.com/user-attachments/assets/3edf02b9-0c54-45ea-88d3-c56817e66be0)
![Image](https://github.com/user-attachments/assets/9fd95b70-3d03-4a67-9fab-0382a2b2c219)
![Image](https://github.com/user-attachments/assets/0ce53956-1952-4782-a5ce-345708542897)

**Comment by ianliuwk1019** [comment]
AWS TEST RDS certificate is updated now. App works fine.
Remaining to update PROD RDS certificate today.
@MCatherine1994

**Comment by MCatherine1994** [comment]
done in PROD
