### ISSUE TITLE
‼️ Forest Client BC Service Card Error in Dev

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forests-access-management#1585]
**Describe the issue**
Team Alliance has reported that the dev environment is experiencing issue when logging in with BC service card in the Dev environment. 
The log in method used is via the "Test with username and password" button

An error url is returned after credentials are entered
> https://nr-forest-client-33-frontend.apps.silver.devops.gov.bc.ca/dashboard?error_description=username+attribute+mapping+required&state=tBfm4OVw5JTj3XN4BX7Gp3ymP8ivefEf&error=invalid_request

**Steps to reproduce**
1. Go to the [dev link](https://teams.microsoft.com/l/message/19:7b68e561-6faa-435a-a9d9-2b20fc24de44_d3ab503d-5cc3-4089-81d4-14f43febd835@unq.gbl.spaces/1725466537562?context=%7B%22contextType%22%3A%22chat%22%7D)
2. Once on the BCSC login page, click on the "Test with username and password" button
3. Enter username and password then submit  
4. An error is returned
![image](https://github.com/user-attachments/assets/925f07b9-0e06-42ef-abb6-87d9c4094f0c)

**Comment by ianliuwk1019** [comment]
This is handled and confirmed with Team Alliance Maria that it is now working after BCSC team switching configuration JWKS value to PROD in DEV environment.
