### ISSUE TITLE
Frontend - Browser refreshing on certain path is broken.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#1588]
**Describe the bug**
During implementing frontend new navigation to user detail (new history) page (#1542), it appears there is an issue when refreshing the browser the page is completely broken.

The intended `path` (on browser address bar) for the new page/route is `http://localhost:5173/user-details/users/9/applications/2`. User refreshes the page, will triggers the application to issue request to backend with **404 error**. It can be seen from the network tab that the application is getting **a resource with wrong requesting path**:
![image](https://github.com/user-attachments/assets/1f689777-20b7-468e-b7e3-832de057ccf4)

One other observation is this does not happen on other existing page when refreshing the browser.
 
**Expected behavior**
- No fetching or loading error.
- Page is refreshed and page is still showing the content correctly.

**Screenshots**
See above description.

**Additional context**
- Some other existing page refreshing is still good, but this page appears to have issue.
- This could be likely due to Vue Router configuration or Vite setup, not yet clear where it is causing the issue as some other page refreshing are still good.
- At the time of this issue ticket was written, the new component/page is just a placeholder (under construction).

**Comment by OlgaLiber2** [comment]
Shouldn't happen after refactoring work (tickets #1540).
