### ISSUE TITLE
Implement Email Styling Enhancements

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forests-access-management#1596]
**Describe the task**
Spike done in #1552 
Make the email template more scannable

**Acceptance Criteria**
we want to:
- [x] show roles as the display name (not db names) for example, "Submitter", "Reviewer", etc 
- [x] add organization names associated with client numbers 
- [x] add a bullet for each role + client number 

mockup for the desired changes: 
![Image](https://github.com/user-attachments/assets/c11fdde1-07a4-4bd8-a8b3-346eaec69bc2)

![Image](https://github.com/user-attachments/assets/c7086df1-42d7-4ed0-b5df-27ccd7d8ec02)

[Context](https://github.com/bcgov/nr-forests-access-management/issues/1552#issuecomment-2334604061):
GC Notify's reply (Their respond speed is impressive!).

```
Hi Ian,

Unfortunately, we don't natively support what you are trying to achieve. Also, we don't support HTML content in templates or variables. 

However, if you are using the API, you could dynamically create the content of a variable in your own code to fit the what you need. You would put in a variable the desired content using the same formatting than you would in a template. 

In your code, you build something like this variable = "* Item 1\n* Item 2\n* Item 3" (dynamically built from the number of items you have). Use the \n new line character between your items. 

And in the template, you would put ((variable)) which will take the content you pass it from the API. 

JSON payload:

{
  "email_address": "recipient@email.com",
  "template_id": "aaaaaa-bbbb-ccc-dddd-11111111111",
  "personalisation": {
    "variable": "* Item 1\n* Item 2\n* Item 3"
    }
}

Let us know if this works. 

Regards,
Jimmy P.
The GC Notify Team
```

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , do you have mockup for the FOM Submitter role with organization?
Thanks.

**Comment by craigyu** [comment]
Possible client info formats

CanFor Inc (0074124214)

CanFor Inc [0074124214]

0074124214 - CanFor Inc

CanFor Inc - 0074124214

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 I updated the mockup. Let me know if you have any questions.

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , in delegated admin email template enhancement, do you intend to remove this statement (it was in first version)?
`As a delegated admin, you are required to comply with our terms and conditions.`

**Comment by ianliuwk1019** [comment]
As discussed, we will keep the T&C for delegated admin template and show only for BCEID user.
Hi @OlgaLiber2 , do you want to add username display in template as:
e.g. `Hello Bceid User (username: bceidtester)`

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 ,
GC Notify does not have way to add few empty lines between paragraph. I tried several combinations and attempts and did not work.
I will need to send email to their support to ask the possibility.

Do you have the hyper link to the Terms and Conditions so I can add to the template?

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , 
If we don't have the T&C pdf stored as a truth source and has as a hyperlink for the email template, then GC Notify can do it as sending a file (within the email sending). 
I looked into GC Notify doc, it has [two modes](https://documentation.notification.canada.ca/en/send.html#sending-files-by-email-is-an-api-only-feature) for sending files (attachment mode and link mode):
![Image](https://github.com/user-attachments/assets/50c5945b-4950-430e-a5fa-a352115ddd18)

Either way it needs the file (pdf) to be converted into into based64 encoded format and send it to the template by code (our FAM backend):
![Image](https://github.com/user-attachments/assets/4c946c72-c94b-4b45-bf0e-4defadbdd3d1)

I assume we don't like to store the pdf into our project repository, if that's the case, maybe I need to use online tool to covert this pdf into base64 string and deposit it into code to send to GC Notify for email template. Is there a concern for this approach?
@basilv @craigyu

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 if it helps at all with the conversion I also have a doc version of T&C

**Comment by ianliuwk1019** [comment]
> [@ianliuwk1019](https://github.com/ianliuwk1019) if it helps at all with the conversion I also have a doc version of T&C

Thanks @OlgaLiber2 , pdf is good.
Conversion isn't the problem. We can try the converted string and test it how it look when GC Notify include the file (T&C) in email sending. The question is more on 
* if there is any concern if we save the converted data in code/repository (as you might have reason not to deposit the original T&C in a site like confluence that can have a link to be included in the email template).
* if there is any concerns(privacy/security) if I use online tool to convert the pdf.

I might be wrong, but if this T&C is to be seen among BCEID users (public), then it is probably no concerns with the T&C being saved in code (converted Base64 string).

**Comment by basilv** [comment]
No privacy concerns with converting T&C doc online. No concerns on my end with storing it in code/repo - we just need to document the process for how to change the T&C contents in the future.

**Comment by ianliuwk1019** [comment]
About adding few extra blank lines in between, seems GC Notify currently has no way to do it and they are looking into it:
![Image](https://github.com/user-attachments/assets/6bc07993-4e08-4cde-9f5a-3735a8dfb62e)

We can for now have the template without the extra few lines and adjust the template when GC Notify has the solution.
