### ISSUE TITLE
Add new role for CLIENT

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#1614]
**Describe the task**
Add a suspend role for CLIENT

**Acceptance Criteria**
- [ ] role is added in TEST and DEV environments
- [ ] display name should be "Suspend"

**Additional context**
![Image](https://github.com/user-attachments/assets/d92c47b1-b0fc-4bdd-9e24-4537f59ddb20)

**Comment by ianliuwk1019** [comment]
@OlgaLiber2 Is this a concrete role (C) or abstract role (A)?

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 it would be a concrete role that does not require client numbers.
