### ISSUE TITLE
Paginate GET user_role_assignment endpoint

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forests-access-management#1626]
**Description**

Paginate the results displayed on the Users Table
![Image](https://github.com/user-attachments/assets/fe402c5d-17b4-43ef-b813-0498d4021e7e)

Endpoint design:
- Updating the endpoint name to use dashes instead of underscores
    - `/fam_applications/{application_id}/user_role_assignment` to `/fam-applications/{application_id}/user-role-assignment`
    - `/fam_applications/{application_id}/users/{user_id}` to `/fam-applications/{application_id}/users/{user_id}` 
    - Refactor areas that use these endpoints, e.g. tests, front-end
- Default: `/fam_applications/{application_id}/user_role_assignment`
    - Will sort by user name, page = 1, page size = 50
- with pagination: `/fam_applications/{application_id}/user_role_assignment?page={pageNumber}&size={pageSize}`
    - if one of them is missing, then use the default values, e.g. if page number is 1 and no pageSize is provided, then use the default 50 for pageSize
- with Sort `/fam_applications/{application_id}/user_role_assignment?sortBy={columnName}`
    - should reject a call if an invalid column name is provided, 400 Bad request
    - default page number and page size should apply if not present
- with Search `/fam_applications/{application_id}/user_role_assignment?search={keyWord}`
    - should be able to encode and decode search string, e.g. a space would be %20
    - default page number and page size should apply if not present
- maintain the current privileges 
- should return an `x-total-count` header
- return an Empty list `[]` if there's no hit

**Acceptance Criteria**
- [ ] An `x-total-count` header 
- [x] A page number that starts with 1 defaulted to 1, a page size defaulted to 50, with a max limit of 100 items per page.
- [x] Sort by columns, default sort by username, should be able to sort by all columns
- [x] Search by keyword on columns [ username, full name, email, client number, Role display_name]
- [x] Make a PR to a feature branch

**Additional Context**
We will be adding forest client name to this endpoint later. 
This will break frontend's user table if deployed, so it should be deployed to a feature branch, the feature branch will be merged to `main` once frontend is ready

**Comment by basilv** [comment]
This story should result in addressing defect #1486

**Comment by craigyu** [comment]
decided to remove pagination metadata from header and put them into response body
