### ISSUE TITLE
Add client details to GET access_control_privileges endpoint

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-forests-access-management#1639]
**Description:**  Add ClientDetails for each FamApplicationUserRoleAssignmentGetSchema in the paginated result of GET access_control_privileges endpoint

**Acceptance Criteria**
- [x] Integrate the /api/clients/search endpoint from Forest Client API
- [x] Add Client name property to response body
- [ ] ~~modify frontend column to display client name and client number~~
- [x] sort by client number
- [ ] ~~Change column name from `Client number` -> `Organization`~~
- [x] Add tests!
- [x] Adjust all router endpoints to follow convention using "-" for naming instead of "_" and do client-code-gen.
- [x] For FAM forest client "search" (GET /forest_clients/search), internally replace using "find_by_client_number" with "search" function just built in this ticket from "ForestClientIntegrationService" (to prevent confusion). Verify if that will cause frontend issue before replacing it (perhaps some error logic handling to the frontend).
- [x] Adjust endpoint `/admin-user-accesses` at response schema to return forest client name as well using this ticket's search ability.

**Additional context**

**Comment by OlgaLiber2** [comment]
@craigyu we should sort by client name (not number), same for ticket 1638.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 @craigyu if possible to do this ticket before other tickets in sprint backlog column that would be great.. this way we can have it deployed to prod sooner so Andrew & Rob can start working on the user manuals.
