### ISSUE TITLE
Sample VUE app deployed in Terraform pipeline

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#165]
**As a** User **I want** a landing page **So That** I can do stuff with FAM

**Additional Context**
-- Hello World Vue app deployed with Terraform to Cloudfront so it is web accessible
-- Deployment verification test (curl-based test)
-- vanity URL is OOS

**Acceptance Criteria**
- [ ] Given , When I hit the relevant URL, Then I see 'Hello FAM' 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged

**Comment by franTarkenton** [comment]
PR - needs review attached to this ticket
link to app: 
https://d3t77o3i70rv6u.cloudfront.net

**Comment by franTarkenton** [comment]
Added the curl test into the GHA... introduced a couple issues.  `terraform output` when pipled to stdout through GHA extra text can get injected into the output that can make parsing the output tricky.

Other issue is the cloudfront is geographically restricted to CA, modified this, however terraform did not detect a state change and trigger an update to cloudfront.  Ran again and forced re-deploy of cloudfront.  Geographic restriction change didn't take.

**Comment by franTarkenton** [comment]
completed: https://github.com/bcgov/nr-forests-access-management/pull/232

* modified the geo restrictions to allow US, so that that curl test can run from gha.

**Comment by basilv** [comment]
A few review comments:
.github/workflows/debugging_frontend_deploy.yml could be removed since the PR is closed.
pull_request.yml:
 line 163 – probably want to run “npm ci” instead of “npm install”
 line 157 vs line 175 – I’d expect we’d just run terraform plan once for our entire stack. Running it multiple times in the same action is redundant.

push.yml: similar comments to pull_request.yml

Otherwise the Vue starter app looks cool!

**Comment by basilv** [comment]
Ah, I got confused by line #170 creating a 'backend.hcl' file. And I thought Conrad's intent was to have everything related to AWS Terraform under the server directory (e.g. move terraform files for cloudfront/VUE app into /server/frontend).

**Comment by gormless87** [comment]
Add comment to GHA to document why separate builds are needed

**Comment by ConradBoydElliottGustafson** [comment]
Here's the RC thread that explains why the separate workspace is used: https://chat.developer.gov.bc.ca/channel/aws-how-to/thread/4un3eXu9EHbbT3Eps

Fundamentally, build-time for the front-end depends on deploy-time for the back end. So the back-end terraform runs, then the github action for the front-end runs (injecting the API URL), THEN the front-end terraform runs.

**Comment by ConradBoydElliottGustafson** [comment]
I was confused too, which is why I asked on RC. There may be a better way to do it, but this way is proven to work for now.

**Comment by franTarkenton** [comment]
minor cleanup, deactivating the debugging gha, ready for review
