### ISSUE TITLE
Github workflow requires update in November 2024

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#1651]
**Describe the task**
Announcement
Posted to bcgov on Nov 7, 2024

GitHub is deprecating version 3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) and [actions/download-artifact](https://github.com/actions/download-artifact) as of Dec 5, 2024. Update workflows to use version 4.

GitHub is scheduling the following times where workflows using version 3 will fail:

Nov 14 9am - 10am PST
Nov 21 6am - 2pm PST
Read more at [GitHub's announcement page](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).

![image](https://github.com/user-attachments/assets/c5677d64-93e5-49b8-b772-20d9f0a1fa3c)

**Acceptance Criteria**
- [ ] FAM repo `actions/upload-artifact@v3` update to v4.
- [ ] Deploy

**Additional context**
-

**Comment by OlgaLiber2** [comment]
@DerekRoberts will help with this ticket
@craigyu @ianliuwk1019

**Comment by DerekRoberts** [comment]
Please see https://github.com/bcgov/nr-forests-access-management/pull/1670.

**Comment by ianliuwk1019** [comment]
The pr #1670 ran [failed](https://github.com/bcgov/nr-forests-access-management/actions/runs/11961050300/job/33346654228?pr=1670) the first time for `actions/upload-artifact@v4`.
![Image](https://github.com/user-attachments/assets/3ceec8e3-aa77-4113-9fc8-b06fd41f77e8)

We have to upgrade to @v4. However, can't really tell why it had this error. I rerun again the failed job and it passed. Hope this is just one time error.
@craigyu @basilv

**Comment by DerekRoberts** [comment]
@ianliuwk1019 Visit the repos associated with Actions. There's probably been a parameter change. It happens a lot!
