### ISSUE TITLE
Set up rds_proxy

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#169]
We want to use rds_proxy when we connect to the DB. This gives us the ability to do connection pooling.

**Comment by ConradBoydElliottGustafson** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html

Figured out why the rds_proxy was erroring out. We created our database as serverless v1. It has to be serverless v2.

Will test to make sure this is correct.

**Comment by ArogeG** [comment]
Completed, to be closed after Demo has been done to team.
