### ISSUE TITLE
Define API scope for FOM requirements

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#17]
Our first iteration of the FAM API will be primarily to support FOM. In this task, we will figure out what FOM needs to be able to do within FAM and describe the features of FAM that will be included in MVP.

Consider how much of FAM UI and API needs to be build to support FOM. Can we go faster by managing FOM setup with DB scripts, etc.

AC:
List of user stories that the API will support in order to enable FAM.
Identify the data setup that needs to be created for FOM if FAM doesn't support full admin functionality in MVP.
Document what is decided to be clearly out of scope for FAM(FOM) MVP.

List of user stories:
1. Create user assignment for FOM Admin role
2. Create user assignment for FOM submitter role (include list of forest client IDS)
3. Look up forest client ID by forest client name
4. Remove someone from FAM role

Data Setup:
1. Populate the forest client table in FAM
2. Create a FOM Admin role
3. Create a FOM Submitter role for each forest client ID
4. Create any FAM roles necessary for "Julius" ( FOM access manager person)
5. Remove FAM roles from a user

Clearly out of scope: 
1. integration with forest client api (doesn't exist yet)
2. Lookups for the BCeID/IDIR user ID (match on username for MVP)
3. UX for managing roles (one time data load for now)
4. UX for managing forest client (one time data load for now)
5. Managing admin users (just hardcode Julius for now)

Endpoints required:
Put someone in FOM Admin Role: input roleID, input username (IDIR or BCeID username) (Forest client ID not allowed)
Put someone in FOM Submitter Role: input RoleID, input User ID, List of Forest Client ID (required) 
(Temporary) Forest Client lookup API -- input part of FC name -- output forest client ID and forest client Name
   (in the future, the forest client lookup API will just be a convenience proxy for the real forest client api)
   (temporarily, FAM will host a copy of forest client data to make this lookup work)
Remove someone from FAM role

Assumptions: 
* Roles and forest clients are pre-populated
* USER ID has to be coming from the IDIR 
* We are building this as a Lambda function, managed by Terraform
* Expose the lambda through AWS API Gateway
* for MVP, matching will be on username, not user ID (to get around being blocked with the lookup service)

Link to data model: https://github.com/bcgov/nr-forests-access-management/wiki/Data-Model

Backlog (to do later):
Do a search on a user to find their ID (Eventually is a proxy for IDIM consulting lookup service)
Integration with IDIM user lookup service
Change matching algorithm to match on user ID instead of username

**Comment by ArogeG** [comment]
@franTarkenton @ConradBoydElliottGustafson Do we need a separate ticket to collect requirements for other FOM roles aside from Submitter and Admin. We could make this an agenda item for our meeting with FOM on Monday.  Would it be possible for users to create new roles based on permissions requirement at some point?

**Comment by ArogeG** [comment]
Really good API design for FAM FOM, thanks @ConradBoydElliottGustafson and @franTarkenton. Will be closing the ticket after our discussion tomorrow.

**Comment by ConradBoydElliottGustafson** [comment]
@ArogeG 

There is a list of public forest clients that is currently used by FOM. We are going to copy the list into FAM so we can create a role for each of them in advance. The only data we are copying across is the ID and the name. The IDEAL situation would be to have a FOREST_CLIENT_API that both FOM and FAM can use to get the up-to-date data (no need to synchronize at that point). We are proposing to copy for now and then refactor when that API is ready. Hopefully team alliance is working on that as part of their MVP for forest client api product.

There are no roles in FOM other than "admin" and "submitter". For "submitter", there is a separate role for each forest client. We are pre-populating these roles to make it easy for Julius (admin) to add users to roles. At some point, FAM would have the feature to allow users to log in and create new roles. See https://github.com/bcgov/nr-forests-access-management/wiki/Requirements-&-Opportunities for a long-ish list of possible future features.

**Comment by basilv** [comment]
The FOM roles are called fom_ministry (admin isn't the best description, more like a reviewer) and fom_forest_client_0XXX (yes, the submitter, for each specific forest client).

**Comment by ArogeG** [comment]
Thanks everyone, do we need to include an API to edit and disable users? @ConradBoydElliottGustafson

**Comment by ConradBoydElliottGustafson** [comment]
@ArogeG "Edit" users isn't really a thing, since we don't store any user data. Disable users is in the requirements wiki page, but we didn't think we needed it for MVP (FOM). We could certainly add it in if we think it will be necessary for the first release.
