### ISSUE TITLE
Front-end to add users by BCeID /IDIR

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#178]
As a application access manager I want to assign users to an application role by BCeID/ IDIR So That users can access an authorized application such as FOM.

**Additional Context**
-- Private page to add the user ID, select the login domain and select the application role, or add/select the forest client role.
--Ability to add the forest client role. If the forest client role does not exists, the backend would create the role. (All the business logic is handled in the API)
--If you create a role assignment that already exits, return a successful result. 
--Upon successfully assigning roles, display a message "Access granted"
--Upon clicking "Grant Access", submit an object the username, roles, and forest client
-Upon clicking "Grant Access" return a response " Access granted" or 'Error Saving' and if successful, clear the user id field and remain on page. 
-Note navigation buttons on the mockup.
--if the forest client already exists, update the table and if not add the forest client.

Note: A separate ticket, the forest client API will be integrated the front -end and the back-end for validation. 
- 

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/eba4c54f-1442-4ae5-acf3-ec725331a17c)

**Acceptance Criteria**

 Given I have click on the Grant Access, create an object with user ID, application role and/or forest client as a  database record.
 Given I have logged in successfully with an IDIR, When thee are no applications returned, Then I am advised to check with the FAM Team
**Definition of Done**

 **Ready to Demo in Sprint Review**
 Does what I have made have appropriate test coverage?
 Documentation and/or scientific documentation exists and can be found
 Peer Reviewed by 2 people on the team
 Manual testing of all PRs in Dev and Prod
 Merged

**Comment by ianliuwk1019** [comment]
A side note for AWS dev environment.
* To test with example like "FOM" application, roles needs to exist first (probably need another version of alembic/flyway migration).
I use this script locally for database inserts: 
```
insert into app_fam.fam_role(role_name, role_purpose, application_id, create_user, role_type_code)
values('FOM_SUBMITTER', 'FOM Submitter', 2, 'fam_proxy_api', 'A');

insert into app_fam.fam_role(role_name, role_purpose, application_id, create_user, role_type_code)
values('FOM_REVIEWER', 'FOM Reviewer', 2, 'fam_proxy_api', 'C');
```

* Also, due to some fixes in backend for this ticket, backend needs to be re-dployed to AWS.

**Comment by ArogeG** [comment]
@basilv, is this what I should be looking at in Dev for the Grant Access screen? 

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/731bb1dc-0314-45e9-b30a-7e6e20bd6d3a)

**Comment by basilv** [comment]
I checked, and I'm seeing the updated screen. Are you maybe looking at the test environment URL instead of dev? URL: https://d2solh97t525i7.cloudfront.net/grant

**Comment by ArogeG** [comment]
Thanks Basil, I was looking at Dev, but it is working now. It was probably showing me the screen I opened before deployment. probably, my cache or something. 

@basil how do I confirm that the records are in the database?

**Comment by ArogeG** [comment]
Looks good, I have some questions that I would like to ask tomorrow.

**Comment by basilv** [comment]
You can call the get role assignments endpoint on the API to check what's in the database.
