### ISSUE TITLE
Enhance FAM API CI/CD process

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#19]
We will make the FAM API auto build, test, and deploy using Github Actions.

AC:
Create Terraform definitions for API infrastructure (Lambda function + API Gateway definitions + DB connections)
When PR is merged, Terraform deploys the latest version of the API
When the API is deployed, I can hit a "version" endpoint that tells me it's working (?)

**Comment by gormless87** [comment]
Closing out as this work has been captured in a series of other tickets.
