### ISSUE TITLE
Diagram display issues for GitHub dark mode

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-forests-access-management#190]
Diagram linked below is using a transparent background, which displays poorly using GitHub dark mode.  A solid background should solve this.

https://github.com/bcgov/nr-forests-access-management/wiki/Architecture

![Screenshot from 2022-09-16 09-49-48](https://user-images.githubusercontent.com/4391600/190689775-fa5cc973-943a-42e9-bd06-23e9852df654.png)

**Comment by OlgaLiber2** [comment]
@ConradBoydElliottGustafson Is this diagram your artifact? If so, would you be able to export the image on a white background and update it on GH?

**Comment by ConradBoydElliottGustafson** [comment]
The diagram is a draw.io diagram sitting in our repo, so anyone can change it. Having said that, I'm happy to do it if it is assigned to me.

**Comment by OlgaLiber2** [comment]
@DerekRoberts do you have access to this draw.io diagram in our repo? Can you export the image with white background?

**Comment by DerekRoberts** [comment]
@OlgaLiber2 Done!  :)
https://github.com/bcgov/nr-forests-access-management/pull/910
