### ISSUE TITLE
Clean up Sample API Lambda and Gateway

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#192]
Remove the "Kevin Lambda- Test Lambda" and update the github actions to build and deploy the Server-backend dir into the FAM API that has the gateway in front of it.

AC: 

- The endpoint for FAM API can be called from the internet without any errors. 
- There is only one API Lambda being built and deployed to AWS.

**Comment by franTarkenton** [comment]
Thinking we can add dealing with the CORS issue to this ticket?

**Comment by gormless87** [comment]
Created #240 for CORS-related task
