### ISSUE TITLE
Spike: DB Snapshot Restore

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#193]
As an Operations Specialist, I want to restore FAM db from a snapshot on AWS, so that I can get the DB to its most recent state. 

- Need a process to restore snapshots for AWS RDS.

Additional Context - this issue is really about db backup/recovery in general

Acceptance Criteria
--need ability to restore (PITR or PR-based)
--Document current snapshot schedule
--Document process for restore on the FAM Wiki

Brent to  provide a demo at the next AWS Touchpoint (Early August)

Acceptance Criteria

 Given (Context), When (action carried out), Then (expected outcome)
 Given (Context), When (action carried out), Then (expected outcome)
Definition of Done

 Ready to Demo in Sprint Review
 Does what I have made have appropriate test coverage?
 Documentation and/or scientific documentation exists and can be found
 Peer Reviewed by 2 people on the team
 Manual testing of all PRs in Dev and Prod
 Merged

**Comment by ArogeG** [comment]
@rparfig discussed this with AWS support team- Brent and we are waiting for some feedback from Brent

**Comment by ArogeG** [comment]
Current state, Restore can be completed by creating a new DB and dropping the old one. This will mean that there will be an outage. Need information from AWS on how to restore a snapshot to the database.

**Comment by gormless87** [comment]
@basilv -timeboxed this to 5 points and labelled it 'SPIKE'
