### ISSUE TITLE
Document API End-point security rules on the wiki

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#197]
**As a** *developer* **I want** *security rules documented* **So That** *I know whether or not I'm in compliance*

**Additional Context**
-intent of ticket is to design the documentation pattern and get feedback 

**Acceptance Criteria**
- [ ] Given the pattern is documented, When I use follow the pattern, Then there is clarity around development task sequence and priority

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged

**Comment by ConradBoydElliottGustafson** [comment]
https://github.com/bcgov/nr-forests-access-management/wiki/API-Security

**Comment by ianliuwk1019** [comment]
Probably need to include two other endpoints in the document:
* /fam_application/{application_id}/roles - GET
* /fam_application/{application_id}/role_assignment - GET
Currently the two endpoints are in tickets for this Sprint but not implemented yet.

**Comment by ConradBoydElliottGustafson** [comment]
@ianliuwk1019 Thanks for the catch. I added rules for those two endpoints into the document. Will update the graphic when the new one is available.
