### ISSUE TITLE
Implement the API (break down later by endpoint)

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#20]
Based on the OpenAPI spec that we designed, code the implementation of the spec.

AC: 
Choose API backend technology (Node.js or other)
Implement the endpoints
Automated local unit tests (that pass!!!)
Runs locally (not yet integrated into deployment pipeline)

MVP API endpoints - create issue for each of:
- [ ] Add user 
- [ ] Get user 
- [ ] Add role *could pre-populate all roles
- [ ] Get role 
- [ ] Add application *low priority; SQL for MVP
- [ ] Assign user to role
- [ ] Remove user from role *low priority; SQL for MVP
- [ ] Get users for role 

Initial rough estimate is 5 points for each endpoint

Alembic vs Flyway: use Alembic to generate SQL scripts that will added to the FAM code repo to be executed by Flyway; evaluate for possible pivot later.

**Comment by gormless87** [comment]
Closing as duplicated by %56, #57, #58
