### ISSUE TITLE
FAM data model changes to ER/Studio

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#203]
**As a** *developer, data architect, data custodian, or database administrator* **I want** *ER/Studio updated with the latest FAM changes* **So That** *all parties refer to the same data model*

**Additional Context**
- Several rounds of FAM data model changes have been implemented, ER/Studio is out of sync with as-built.

**Acceptance Criteria**
- [ ] Given that ER/Studio is updated, When interested parties examine the FAM data model, Then it accurately refelcts the current state.

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs
- [ ] Merged

**Comment by rparfig** [comment]
@franTarkenton : Could you please point me to the DDL scripts that contain the changes that need to be pushed to ER Studio?

**Comment by rparfig** [comment]
Updated ER Studio repository with data model changes made in the code. Final review required

**Comment by rparfig** [comment]
Completed all changes. To request QA by DAs
