### ISSUE TITLE
FAM database column comment updates

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#206]
**As a** *Data Architect* **I want** *FAM database comments complete* **So That* *the data model is coherently described**

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by rparfig** [comment]
-- Columns that require proper comments:
fam_application.application_name
fam_application.application_description
fam_application_client.cognito_client_id
fam_forest_client.client_name
fam_group.group_id
fam_group.group_name
fam_group.purpose
fam_role.role_name
fam_role.role_purpose
fam_user.user_guid
fam_user.cognito_user_id
fam_user.user_name
fam_user_type_code.user_type_code

-- Tables that require proper comments
fam_application_group_xref
fam_group_role_xref

**Comment by rparfig** [comment]
Updates to column definitions (comments) have been defined as follows:

-- Columns that require proper comments
COMMENT ON COLUMN fam_application.application_name         IS 'The commonly used name associated with to identify an application.';
COMMENT ON COLUMN fam_application.application_description  IS 'A general description of the application, including its main function and purpose';
COMMENT ON COLUMN fam_application_client.cognito_client_id IS 'Primary key for the OIDC Client record in the Cognito user pool. This pool resides in the AWS Cloud and it is used to control access to proxy servers in the BC Government teams';
COMMENT ON COLUMN fam_forest_client.client_name            IS 'The name of the Ministry Client - Company or Individual. Entered as: the full corporate name if a Corporation; the full registered name if a Partnership; the legal surname if an Individual.';
COMMENT ON COLUMN fam_group.group_id                       IS 'Automatically generated key used to identify the uniqueness of an Group registered under FAM';
COMMENT ON COLUMN fam_group.group_name                     IS 'A description given to a set of roles that are intended to satisfy a specific group of functions';
COMMENT ON COLUMN fam_group.purpose                        IS 'A description of the function that a group of roles is intended to satisfy';
COMMENT ON COLUMN fam_role.role_name                       IS 'The name given to a role that describes a specific function within an application';
COMMENT ON COLUMN fam_role.role_purpose                    IS 'The description of the specific function that a role is intended to perform within an application';
COMMENT ON COLUMN fam_user.user_guid                       IS 'Each user or group in a directory has a unique identifier called a GUID or Globally Unique Identifier. The value is a 128 bit number that is displayed and passed around the network as a 32 character hexadecimal string.';
COMMENT ON COLUMN fam_user.cognito_user_id                 IS 'Primary key for the user record in the Cognito user pool. This pool resides in the AWS Cloud and it is used to control access to proxy servers in the BC Government teams';
COMMENT ON COLUMN fam_user.user_name                       IS 'The full name of the user for whom access is granted to.';
COMMENT ON COLUMN fam_user_type_code.user_type_code        IS 'Identifies which type of the user it belongs to; IDIR, BCeID etc.';

-- Tables that require proper comments
COMMENT ON TABLE fam_application_group_xref IS 'Describes de association between a group of roles and a given application system';
COMMENT ON TABLE fam_group_role_xref        IS 'Identifies the list of specific roles that are grouped under one single identifier (group) for ease of use and administration';

@franTarkenton : FYI
