### ISSUE TITLE
Create Front-end for FAM Application Delegate (client) to provision access

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#222]
As an application administrator, I want to be able to specify who can act as an authorization grantor to grant or revoke application roles and application groups to users, so that I can ensure that the application has its own authorization grantor(s) who assume responsibility for maintaining user assignment to application roles and application groups. 

Individuals without this privilege for a particular application should not be able to use FAM to add or remove users to roles or groups for the application.

Variation: Specify authorization grantors that can act as an authorization grantor to grant or revoke specific application roles and application groups to users, but only in the context of a specific forest client.

Additional Context
-- Remove Users using by a known BCeID or IDIR username for delegate organization
-- Ability to display users for a particular organization 
-- Delegate should be for FSA and not just a specific app (Need to confirm that the same delegate will be used for all forestry app. 
-- Delegate will be required to login to FAM or a public version of FAM via BCeID
-- API will validate that external user have the FAM role required to perform an operation using the FAM API

---For Future Consideration:

Acceptance Criteria

Definition of Done

Ready to Demo in Sprint Review
Does what I have made have appropriate test coverage?
Documentation and/or scientific documentation exists and can be found
Peer Reviewed by 2 people on the team
Manual testing of all PRs in Dev and Prod
Merged

**Comment by OlgaLiber2** [comment]
refined user story will be created on a new ticket.
