### ISSUE TITLE
Incorporate feedback provided by Data Architects into the FAM Data Model

### ISSUE THREAD

**Issue by rparfig** [bcgov/nr-forests-access-management#236]
Data Architects provided some feedback on the FAM Data Model on October 19th, 2022

Here is a summary of our recommendations and questions:

**Code Tables** 
- The use of code tables is recommended where they would be useful.
- For example, for user types 

**Consistent naming** 
- For the group table, add “group” to the name and purpose columns.
- Note: We are having a discussion internally about whether table names should be upper-case or lower-case for Postgres data models. We do not have a standard at this time but it is something we are hoping to decide on shortly. 

**Notation** 
- Could you please change the model notation to IE (Crow’s Feet) to match the symbology of our other ER Studio models?

**Comprehensive definitions** 
- It would be helpful to include examples and standard patterns to definitions for both tables and columns. For example, what pattern do user names follow?
- Include acronym definitions in table and column definitions. For example, what does OIDC stand for in the application client table description?

**Questions:** 
- Forest client – is this a clone of data from the legacy forest client system?
- Cognito user ID column in the user table – where is this coming from? An external reference?
- IDIR user and BCEID user subtypes – why are these symbolized in this way (yellow and disconnected)?

Without definitions for all of the tables and columns, it was difficult to get the full picture of the model. Perhaps we could set aside some time for you to walk us through it? Otherwise, we can take another look once your team has had a chance to add in those definitions.

**Comment by basilv** [comment]
Hey Richard, when I first worked on FOM's data model, I was told there were standards (two different sets, one old :). But the new standard said to use lower case table names for postgres. I'll try to find a link to that standard.

**Comment by basilv** [comment]
Cody was doing the review if I remember and pointed me at the new standard so you could possibly ask him as well.

**Comment by basilv** [comment]
Found it - the standards FOM used I documented at https://apps.nrs.gov.bc.ca/int/confluence/display/FOM/Physical+Data+Model which were based on NRS guidelines: https://apps.nrs.gov.bc.ca/int/confluence/display/NRMDDDG/NRM+Data+and+Database+Development+Guidelines

FYI one of the lessons learned I raised from FOM is to communicate data standards before the physical data model is created, looks like that wasn't actually learned organizationally so we are back to the same issue for FAM. 

Also, I find it frustrating when data architects try to review a model without understanding the application context. E.g. OIDC and other business/IT concepts should be covered in the application overview, and not need to be redefined for each column/table. Same with business concepts like forest client. 

For your question on how forest_client table will be populated see discussion in https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-forests-access-management/179 as we discussed that today. But in short, yes its a partial local cache of forest client data retrieved via forest client API.

**Comment by basilv** [comment]
(FYI I was forced to use code tables on FOM, I prefer to have the option of using check constraint instead of code table.)

**Comment by rparfig** [comment]
> (FYI I was forced to use code tables on FOM, I prefer to have the option of using check constraint instead of code table.)

I think there is a place and a justification to use code tables as opposed to check constraints. In essence, if the check constraint value has a meaning for the business, then the code table is recommended; so to avoid any hard coding; so I agree with you! :)

**Comment by rparfig** [comment]
Comments missing is being tracked under #206

- Not adopting varchar datatype without limits
- Added some comments to clarify "OIDC"
- Added code tables, updated naming for indexes and keys as per guidelines
- Updated notation
- Change names of some columns, like in fam_group
- Prepared script with all changes. To be reviewed with the dev team before merging into Dev branch

**Comment by rparfig** [comment]
Completed changes and reviewed them with @franTarkenton.
Pending: Update comments for some tables and columns. Likely, it will be a separate migration.

@franTarkenton has proposed to divide all these changes by change type. E.g. one migration for renaming indexes, another for removing default values, and so on

Attaching all expected changes into this ticket.

**Comment by rparfig** [comment]
`-- Delete default timestamp for update_date audit columns
ALTER TABLE app_fam.fam_application ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_forest_client ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_user ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_application_client ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_group ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_role ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_application_group_xref ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_group_role_xref ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_user_group_xref ALTER COLUMN update_date DROP DEFAULT;

ALTER TABLE app_fam.fam_user_role_xref ALTER COLUMN update_date DROP DEFAULT;

-- Make description on code table mandatory
ALTER TABLE app_fam.fam_user_type_code ALTER COLUMN description NOT NULL;
ALTER TABLE app_fam.fam_role_type_code ALTER COLUMN description NOT NULL;

-- Validate these commands !!
ALTER TABLE app_fam.fam_role_type RENAME TO app_fam.fam_role_type_code;

ALTER TABLE app_fam.fam_group RENAME COLUMN purpose TO group_purpose;

-- Change varchar column to timestamp
ALTER TABLE app_fam.fam_application_client ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;

-- Change other columns to timestamp without time zone:
ALTER TABLE app_fam.fam_forest_client ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;          
ALTER TABLE app_fam.fam_forest_client ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_group ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_group ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user_group_xref ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user_group_xref ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user_role_xref ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_user_role_xref ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_group_role_xref ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_group_role_xref ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application_group_xref ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application_group_xref ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_role ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_role ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application_client ALTER COLUMN create_date TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE app_fam.fam_application_client ALTER COLUMN update_date TIMESTAMP(6) WITHOUT TIME ZONE;

-- Assign a size for forest_client_number's column
ALTER TABLE app_fam.fam_forest_client ALTER COLUMN forest_client_number VARCHAR(10); -- NOT NULL

-- Rename INDEXES
ALTER INDEX app_fam.Ref216 RENAME TO app_fam.fam_grp_group_id_idx;

ALTER INDEX app_fam.ref425 RENAME TO app_fam.fam_grp_client_number_id_idx;

ALTER INDEX app_fam.ref329 RENAME TO app_fam.fam_usr_grp_xref_user_id_idx;

ALTER INDEX app_fam.ref230 RENAME TO app_fam.usr_grp_xref_group_id_idx;

ALTER INDEX app_fam.fam_usr_rle_pk_1 RENAME TO app_fam.fam_usr_grp_xref_pk;

ALTER INDEX app_fam.ref219 RENAME TO app_fam.fam_app_grp_xref_group_id_idx;

ALTER INDEX app_fam.ref720 RENAME TO app_fam.fam_app_grp_xref_application_id_idx;

ALTER INDEX app_fam.ref1217 RENAME TO app_fam.fam_grp_rle_xref_role_id_idx;

ALTER INDEX app_fam.ref218 RENAME TO app_fam.fam_grp_rle_xref_group_id_idx;

ALTER INDEX app_fam.ref310 RENAME TO app_fam.fam_usr_rle_xref_user_id_idx;

ALTER INDEX app_fam.ref1212 RENAME TO app_fam.fam_usr_rle_xref_role_id_idx;

ALTER INDEX app_fam.ref722 RENAME TO app_fam.fam_rle_application_id_idx;

ALTER INDEX app_fam.ref1223 RENAME TO app_fam.fam_rle_parent_role_id_idx;

ALTER INDEX app_fam.ref424 RENAME TO app_fam.fam_rle_client_number_id_idx;

-- Primary key index on fam_role_type_code
ALTER INDEX app_fam.PK19 RENAME TO app_fam.fam_role_type_code_pk;

`

**Comment by franTarkenton** [comment]
Ideally the changes described in the SQL should be translated into alembic migrations. 
* modify the model.py to reflect changes
* create alembic migration
* create flyway / sql
* q/a sql.

thinking should be completed in a series of migrations, basically everywhere there is a comment in the sql file delineates a new migration.
