### ISSUE TITLE
SPIKE: how to Integrate openapi spec to AWS gateway

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#238]
**Acceptance Criteria**
**As a** *Developer* **I want** *to ingest the open api spec generated by  the api* **So That** *the AWS api gateway is aware of the individual end points and we can explore securing end points through the gateway*

**Additional Context**
- ticket 84 got the gateway up and running however the setup could likely use a bunch of enhancements... I'm thinking getting the openapi spec ingested is the first of the enhancements
- other considerations that may ease development is to publish the swagger doc that gets generated by our api
- Once the openapi spec has been integrated, we should take a look and verify that CORS can now be configured by the AWS API Gateway

**Definition of Done**
- [ ] Api spec has been integrated into our gateway configuration
- [ ] New end points are automatically added to the gateway configuration
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by gormless87** [comment]
It really does exist!  https://en.wikipedia.org/wiki/The_Santa_Clause
