### ISSUE TITLE
Define authorization lookup database query and token attribute format

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#24]
In this task we will clearly define the inputs and outputs for the authorization lookup. 

AC: 
Clear programming contract for V1 of the authorization lookup function
Define the SQL query (pseudocode) for getting the right data out of FAM
Choose a format for how to represent FAM data within the JWT that is returned by Cognito

**Comment by ConradBoydElliottGustafson** [comment]
Here's the documentation on the plan. Pretty much ready to code if we agree on this format.

https://github.com/bcgov/nr-forests-access-management/wiki/Authorization-Mechanism

**Comment by basilv** [comment]
Documentation looks really clear and well-written. I assume Cognito will issue the token then to the invoking application with the groups as overridden by the "groupsToOverride" attribute in the response. We'll eventually need documentation for consumer applications like FOM to know what to expect in the token, but I think that would be a separate ticket (unsure if this exists, likely post MVP)
