### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#240]
**Describe the task**
CORS is currently not functional in FAM

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
Created this issue to keep #192 focused on code cleanup

**Comment by gormless87** [comment]
@basilv - minimalist stub of an issue based on our CORS discussion this morning

**Comment by basilv** [comment]
Paired with Kevin to fix API to add * for origin. Will need better setting for prod.
