### ISSUE TITLE
SPIKE: business value in auditing

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#243]
**Acceptance Criteria**
**As a** *developer* **I want** *to understand which audit information is valuable to the business perspective* **So That** *we build the right thing*

**Additional Context**
- Service design?
- this issue is about what audit information should be stored in the database; observability/transparency is OOS

-  Do audit tables have any value at all? 
- Given that the only thing interacting with the DB will be the API, wouldn't 
    event monitoring at the API level be far more interesting and usable?
-  What is the business requirement for the audit columns other than "it's a standard"?
- Some reporting requirements are easily met by including audit columns 
   like created/updated date. E.g. for FAM how many new users added for application X in the last Y 
   months/year - can be answered easily if you have a create timestamp column on your user / role assignment tables.
- FAM is a security system, likely be forensic scenarios were we'd want to know when a 
   user's access is added or removed. This could also be achieved by logging events instead of audit 
   columns/tables (typically logs are harder to query).  
- Another way to answer the question of why audit columns/audit tables is that they help meet non-functional 
  requirements in terms of supportability and auditability    

 ** Related questions **
- Are we doing logical deletes or physical deletes for FAM?
- Agree that revision_count is not needed?
- What retention period is appropriate?

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team

**Comment by ArogeG** [comment]
Discussion with Michelle: Auditing could be more at the API level instead of on the database level. Since the database is accessed through the API.
