### ISSUE TITLE
Error handling approach

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#247]
**As a** *developer* **I want** *a common and clearly defined error handling approach* **So That** *alerts/errors/warnings are displayed in a consistent manner*

**Additional Context**
- We need an application-wide approach to displaying errors/warnings to the end user (e.g. via alert popup - ugly, or via message area on screen) including especially errors from the back-end
- enter text here

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by ArogeG** [comment]
My opinion is to use a banner/ message area on screen or pop-up for error handling. Leaving it to @basilv and @ianliuwk1019 to decide on an interim approach pending when a program level decision is made.

**Comment by basilv** [comment]
I prefer a banner/message area instead of a popup 99% of the time. This can also be used for informational messages.

**Comment by basilv** [comment]
Documented approach briefly at https://github.com/bcgov/nr-forests-access-management/wiki/FAM-Frontend-Design
