### ISSUE TITLE
Implement Database Changes Identified in #206/#236

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#259]
**Implement the data model changes recommended by Data Architects**

@rpardofigueroa has worked with the data architects to identify some key improvements to our existing data model.  These are described in the following two tickets:

* https://github.com/bcgov/nr-forests-access-management/issues/206 - Add Column Comments
* https://github.com/bcgov/nr-forests-access-management/issues/236 - Misc Fixes

This ticket describes the implementation of those changes.

The sql file described [here](https://github.com/bcgov/nr-forests-access-management/issues/236#issuecomment-1293830333) includes comments that describe different types of changes that need to be implemented.  Each section identified by a comment should have its own migration file.

**Acceptance Criteria**
- [ ] Changes made to the orm model (server/backend/api/app/models/model.py)
- [ ] All tests pass after changes implemented
- [ ] Alembic migrations created and verified
- [ ] Corresponding flyway migrations are created
- [ ] Changes have been tested with local postgres instance
- [ ] Changes implemented in the AWS database.

**Comment by ArogeG** [comment]
#206 - Add Column Comments  and #236 - Misc Fixes needs to be reviewed to determine MVP tasks on the ticket.

**Comment by basilv** [comment]
#206 has been completed. (Even if there was anything outstanding, it wouldn't be MVP.)

**Comment by basilv** [comment]
Here's my assessment of what's outstanding and what needs to be done:
Pre MVP:
- Change timestamp columns to include time zone (TIMESTAMPTZ)


Post MVP:
- Rename column group.purpose to group.group_purpose (I don't like the naming standard but might as well be consistent).
- Add comments for: user.cognito_user_id, user.user_guid, user.user_name, fam_application_client.cognito_client_id, 


Never:
- Change case of table names 

Already Done:
- add user_type_code table
- update most table comments
