### ISSUE TITLE
SPIKE: Generate a list of Dev/Ops action items

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#267]
**As a** *developer* **I want** *a list of pipeline tasks* **So That** *we can prioritize implementation*

**Additional Context**
- start with a conversation with Derek
-  ie; code coverage report; block build if not met
 
**Acceptance Criteria**
- [ ] GitHub Epic with an issue for each item detailing improvements and the value expected
- [ ]

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by basilv** [comment]
Derek has a whole bunch of DevOps features in his bcgov-nr-quickstart-typescript repo. The deployment ones are specific to OpenShift, but otherwise we could potentially just leverage what he has built.
