### ISSUE TITLE
Spike: Back-end  calls from the Front-end API

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#278]
**Describe the task**
Decide on Design for how the front-end calls the back-end API for FAM.

**A couple of options:**
- Fetch

- Axios library or other libraries?

- Generate from the Open API

**Acceptance Criteria**
- [ ] Decision documented for API call for the front-end
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
From Vue community on the internet, there seem to be two main approaches when come to http calls; the native javascript **Fetch** and **Axios** library. While Vue official documentation did not provide recommended way (but they do show example using Fetch API). Most online reading I see are using the library Axios. 
Checking on Axios npm site, it is extremely popular, weekly download exceeds more than 
35,000,000, and it is well documented and lots of projects depend on the library. In short, I feel it is good to use this well-supported http library for our project convenience(although it adds a bit packing size).

The advantages being:
- Many examples online, very popular, and well-documented api.
- **Promise based** Http style, very friendly.
- Supports all major (and latest) browsers.
- **Automatically transform request/response** (Fetch API is lacking this - do your own transform).
- **Globally scoped configuration** in one place (This is convenient for any project).
- **Allowing intercept requests and responses** (multiple interceptors) before handling (This is a very convenient feature, Fetch does not have this out of the box, need to write your own wrappers) 
- Even previous Vue2 cookboos says it is a nice library.
 
References (Fetch vs Axios):
	- https://www.npmjs.com/package/axios
	- https://eversis.com/blog/how-to-make-a-remote-call-on-vue-js
	- https://v2.vuejs.org/v2/cookbook/using-axios-to-consume-apis.html


For generating OpenAPI client, when comes to generating http client for Fetch API or Axios, they are all being supported by the OpenAPI Generator. For Fetch API, there is a client generator "**typescript-fetch**". For Axios, there is a client generator "**typescript-axios**". The tasks needed to configure this generation probably is the same. I find a little 
online example that generates API client for "typescript-axios" with Python FastAPI backend. This is probably exactly what we want. See below references:

References (OpenAPI Client Generation):
	- https://openapi-generator.tech/docs/generators
	- https://gaganpreet.in/posts/hyperproductive-apis-fastapi/
           (This is a nice example, might be missing some details but has the summary we need)
@ArogeG @basilv

**Comment by basilv** [comment]
@ianliuwk1019  I agree on using axios instead of fetch. I particularly liked the automatic request transformation (for adding our authorization header), and how the library supported the notion of a base URL, but I'm sure there are other benefits. (For example, hopefully common error handling)

I also like the idea of using the OpenAPI generator, you are right that the one article seems to outline exactly what we need to do. Lets first convert the existing single fetch call to use axios as one PR, then look to add the generated client as a second PR, just so we can compare. We'll leave this spike open until I can look at the resulting PRs and then do a short writeup.
