### ISSUE TITLE
PIA for FAM

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#282]
As a MISO
I want to understand the privacy risks of an app so that I can
so that make sure it follows ministry approved best practices and will not expose privacy risks

Acceptance Criteria:
MPO has completed PIA to review

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Peer Reviewed by 2 people on the team
- [x] PIA has been submitted

PIA forms here https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=91204093

**Comment by ArogeG** [comment]
First draft of the PIA has been completed and reviewed by the MISO. PIA has also been sent to Privacy, Compliance and Training Branch | Ministry of Citizens’ Services. See details on the PIA request below. The PIA needs to be signed by the PCT branch for approval of BC Services Card agreement. 

Good afternoon,

Thank you for submitting your BCSC PIA and checklist PIA.  Wynne MacAlpine has been assigned and the tracking numbers are:

WLRS23015 – Forest Access Management           
WLRS23016 – FAM Checklist

If you have any questions or are working under a tight deadline, please contact Wynne directly. 

Best,
Sandy Tremblay (they/them)
Privacy Analyst
Privacy, Compliance and Training Branch | Ministry of Citizens’ Services
236-478-2265

**Comment by ArogeG** [comment]
Confluence page with PIA documents
https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=160072515

**Comment by ConradBoydElliottGustafson** [comment]
@gormless87 Is this not mostly done? It's sitting in "new issues"

**Comment by gormless87** [comment]
CPO signed copies at  https://apps.nrs.gov.bc.ca/int/confluence/x/Q4OKCQ

Post-hoc estimate of 13 story points added
