### ISSUE TITLE
Request Keycloak clients

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#29]
In order to create a IDP in Cognito for IDIR/BCeID Business/BCeID Basic first we need a confidential client ion the Pathfinder SSO Gold instance.

For each of dev/test/prod:

AC:
New team created with Pathfinder SSO CSS application
New integration created with Pathfinder SSO CSS application
Dev/Test provisioned, Prod approval process underway (BCeID)
Confirm Prod integration has been provisioned for IDIR

**Comment by ConradBoydElliottGustafson** [comment]
![image.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/32b84baf-41b1-4ade-a913-83d29d5d122a)
![image.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/fd26cae9-4791-435d-a6a3-a3c0e63cf43e)

**Comment by ArogeG** [comment]
@ConradBoydElliottGustafson are you able to add me to the team as well. Thanks.

**Comment by ArogeG** [comment]
Decided to Common Login Page for MVP. Azure could be added on later.
