### ISSUE TITLE
draft Ops Guide for FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#296]
**Describe the task**
As a Fingerprint Team member I want a complete and concise Operations Guide for FAM so that I can reliably and efficiently carry out required tasks with consistent results.

**_**Ops guide should include the following:*_**

- Incident Management Actions 

- Major Incident Management Actions

-Security Incident Actions

-Defect Management Actions

Incident management Actions should include:
- How to deploy hot fix to Production
- Where do we log incidents (Zenhub for now, this could change)
-  Include links to the AWS Dashboard logs to check for errors and check the error logs 

Defect Management should include:
- Document Steps for Release Management: Teams should be able to create release template on confluence

Major Incident Management should include:
-Document how to assemble team in the event of a major incident
-brain storm ideas and issues

Major Security Incident Actions should include:
-Document how to shut down the API gateway if under attack
-Do we want to capture the IP addresses to identify source of attack? 

Process for notifying DA the data model changes (#177)

Process for doing maintenance, pipeline upgrade, package upgrade

**Annual/ Bi-annual Operational Activities:**
bi-annual review of access of the FAM source code and application. 

**Acceptance Criteria**
- [ ] all info needed to deploy a given version of all FAM components
- [ ] ownership and key contacts
- [ ] monitoring, troubleshooting, and problem escalation
- [ ] backup/recovery schedule and instructions
- [ ] known issues

**Additional context**

[ ] - Counterpart documentation User Guide is described in #456

**Comment by MCatherine1994** [comment]
Also wondering how we store and share secrets in our team?

**Comment by ConradBoydElliottGustafson** [comment]
Secrets can be safely stored in GitHub Actions if they need to be passed to Terraform during CI/CD.
Secrets that need to be accessed by the FAM components at runtime can be safely stored in AWS secrets.
Secrets that need to be shared between team members can also be put in AWS secrets. Anyone who can access the AWS projects (i.e. our team) can read the secrets in AWS.

**Comment by ArogeG** [comment]
Update the Wiki with missing component from this tickets.

**Comment by OlgaLiber2** [comment]
include this content https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Critical+Incident+Procedure
