### ISSUE TITLE
Gated DEV deploy on PR open/update

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#304]
**As a** *Developer* **I want** *the ability to deploy to DEV from a PR* **So That** *I can work on issues that require aspects of a full AWS environment that are not readily available in my local environment*

**Additional Context**
- enter text here
- enter text here

**Acceptance Criteria**
- [ ] Criteria for use broadly but clearly stated and understood
- [ ] Requirements for communication about when DEV is deployed form a PR vs Main

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by basilv** [comment]
Did a partial implementation to unblock Ian. Gated deploy on PR open for front-end only is in place.
