### ISSUE TITLE
User Experience when Access is Restricted based on FAM roles and Groups

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#309]
**Describe the task**
When the security permissions are in place, the front-end needs to handle the following scenarios:
 
- Only access to one application to admin

- Access to no applications to admin

- Access to multiple applications to admin

- App security - Redirect to login page if not logged in 

**Acceptance Criteria** TBD (tomorrow)
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by NickSaglioni** [comment]
This task also requires a major notification code refactoring, which is taking additional time to complete.

**Comment by ianliuwk1019** [comment]
Just a note, while reviewing, the first 3 tasks seems to me is dependent on the one backend task (#359), which just merged into main branch. So these 3 tasks should be good without frontend change. However, the frontend security redirect and error handling should be the focus on this ticket (point 4 on this ticket). And, that might be a good test cases here. 
@MCatherine1994  @ArogeG

**Comment by ianliuwk1019** [comment]
Maybe some of the below thoughts can be discussed with team and be considered for improvement later and not for this ticket if too much to change at this time.

We can use Vue Router's **router guards** (navigation guards) for:
	1. for **access/security checks**
		(for example, can't navigate to the /manage route without application selected)
	2. **data fetching**
	
Current navigation is that the frontend let the user navigate to the page first and wait for the page to fetch data from backend (and checking if there is error). Vue has two ways to fetch data ("**Fetching After Navigation**" and "**Fetching Before Navigation**"). Personally I prefer fetching before navigation but it depends on user experience we like to offer for the users.
	3. So the app might also need to have some sort of **loading/progress bar** when loading data.
	
For example, there might be scenario that the user just logged in and the frontend immediately navigate to Select Application page and at the same time fetching applications from backend but backend encounters problem and cannot return data to frontend. Then the user would stuck at the Select Application page **with blank content** not knowing what happened (with only general error).

Reference:
- https://router.vuejs.org/guide/advanced/data-fetching.html
- https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard

@ArogeG @basilv

**Comment by basilv** [comment]
Great points Ian. The select application screen explicitly does fetch after for user experience - a loading message is display to the user prior to the content being loaded. I have thought about moving this to the authCallback screen though, that would essentially be fetch before navigate then. In that case we'd keep the loading message on the select application screen, but the auth callback screen would need the error handling if the load fails, and I'm not sure if that would actually work well combined with navigating to the select app screen.
