### ISSUE TITLE
Deal with re-used new user name inheriting old user access.

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#323]
**Describe the bug**
If in IDIR or BCeID a user like jsmith is created, granted access in FAM and they log in to set their user_guid, 
then later this user is ended in IDIR and a different jsmith is hired, gets the jsmith idir username with new GUID, when they log into FAM the auth function will overwrite the existing user record with prior popluated user_guid with the new user_guid and this new user will inherit the access of the old user.

One possible fix is to only update the user where user_guid is null. Otherwise, have an authentication failure? 
Maybe we don't need to deal with this scenario if IDIR & BCeID don't reuse user names.

**Long term solution is to integrate with IDIM web service**

Risk is low as it can only happen between time when record is created an they login

**Comment by gormless87** [comment]
Need validation for when a decommissioned user id is re-created 

A good subject for internal demo discussion
