### ISSUE TITLE
Database Permissions on Tables created subsequent V1

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#333]
**Describe the bug**
Database migrations that add tables subsequent to the V1 migration, are not accessible by the ${api_db_username}

**To Reproduce**
1. hit the user_role_assignment end point deployed to AWS.
[user_role_assignment link](https://qrep67z3j7.execute-api.ca-central-1.amazonaws.com/test/api/v1/fam_applications/2/user_role_assignment) will return "internal error"
2. view the cloudwatch logs for the lambda and you will see the following error:
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table fam_role_type: [link to cloudwatch error](https://ca-central-1.console.aws.amazon.com/cloudwatch/home?region=ca-central-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Ffam-api-lambda-credible-meerkat/log-events/2022$252F12$252F12$252F$255B$2524LATEST$255D447d53313552458d8417f6c0366175e9$3Fstart$3DPT3H)

**Expected behavior**
When the tables are created in migrations ideally they should automatically be viewable by the ${api_db_username}

**Additional context**
This bug identifies two issues that need to be resolved:
1. fix api docker-compose as they should be running under the ${api_db_username} locally to expose these issues before they get to AWS

2. create a new migration that executes the following lines in the db:

``` SQL
GRANT SELECT, UPDATE, DELETE, INSERT ON ALL TABLES IN SCHEMA app_fam TO ${api_db_username};

ALTER default privileges in schema app_fam grant select, insert, delete, update on tables to ${api_db_username};
```

**Comment by basilv** [comment]
Done - Updated database migrations management wiki page 
Confirmed - a missing grant would be detected when testing the API either directly or from front-end using local docker-compose.
