### ISSUE TITLE
Filter FAM Front-end by Environment 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#336]
**As a** *FAM user with access to multiple FAM environments **I want** to view FAM applications by environment **So That** *I can easily provision access to the correct environment*

**Additional Context**
-To support the decision to create multiple DEV, TEST, and PROD IDP configuration in the Prod environment , the front-end needs to be designed to allow users select the environment they intend to work on.
- Create three single select buttons for Prod, Test, and Dev
- Filter the list of application based on the button selected. 

**Acceptance Criteria**
- [ ] Given that the single select buttons are in place, when a user select an environment, then the application list should be filtered to display only applications in the selected env that the user has access to administer. 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/06460c3d-f3ea-4f61-aeba-1f9674a9bc89)

**Comment by NickSaglioni** [comment]
A conversation was held on 03/03 with myself and @OlgaLiber2 about this implementation and two possibilities were discussed. The first one was to implement this task as it is described in this ticket. The other possible implementation would be to have a multiple selection for cases were a specific user would need to be granted access to multiple environments at the same time like, for instance, PROD and TEST. This second implementation would need a major application refactoring as the grant access screen and backend API currently only expect a single application at a time. Olga also raised the possibility to change the current app workflow for granting access, but that needs to be verified and validated first. For now, the implementation described in the task was chosen. @ArogeG

**Comment by NickSaglioni** [comment]
@MCatherine1994 suggested to use the bootstrap package for vue3 for this implementation to create a common radio button component.

https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js
