### ISSUE TITLE
Add a db Application Attribute that stores record of an Application Environment 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#337]
**As a** *FAM User* **I want** *to view FAM applications by the Environment they are created for* **So That** *Provision access to the correct environment*

**Additional Context**
- Create a look-up table on the database for the application environment: Dev, Test, and Prod
- The application name displayed on the front-end should be a combination of the application name and the environment type.

**Acceptance Criteria**
- [ ] Existing data must be updated; existing records designated as DEV
- [ ] New app/role entries added for TEST/PROD
- [ ] Can view on Select application Screen 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/f2ad333b-80ec-45cd-997e-8673abe9e003)

**Comment by ianliuwk1019** [comment]
Just to clarify my understanding.

Migration Script:
	* New Code Table ("**FAM_APP_ENVIRONMENT_TYPE_CODE**") with codes: DEV, TEST, PROD.
	* New column (**APP_ENVIRONMENT_TYPE_CODE**) to FAM_APPLICATION table, nullable = false, default = DEV.
 
Data Script:
	* Insert new records into FAM_APPLICATION table for "fam" and "fom" for: TEST and PROD environments.
	
Question:
	* Currently Terraform output a variable "target_env", this isn't the environment for our "Permanent" production DEV/TEST/PROD.
	  That "target_env" is for our development. So are our development (dev/test/prod) FAM_APPLICATION records all with ("DEV") type code?
	  
Note:
	Our flyway script has V17 (data inserts for FAM Admin Records) but there is no V17 at backend Alembic script.
	Based on established flow (Alembic to Flyway) and my understanding, Alembic will encounter problem when it attempt to create next migration (which is V17)
	as the version does not match to the flyway (it is a safety guard check from Kevin's script).
	Will need to take a look to see if V17 can be skipped from Alembic easily from script, or just add it into Alembic script as well,
	or is there alternative...

@gormless87 @basilv

**Comment by basilv** [comment]
I should have gone offline a while ago, but quick response - this looks reasonable to me. I didn't fully understand your Terraform target_env question, I would think this corresponds to what we display in the FAM UI for the environment.

**Comment by ianliuwk1019** [comment]
Yes, Basil, "target_env" is used for FAM UI to display.
So in our AWS 'prod' "Permanent" environment this "target_env" should be empty.

**Comment by ArogeG** [comment]
Backend changes have been implemented. I don't think the second part of this ticket has been done : "The application name displayed on the front-end should be a combination of the application name and the environment type." 

Right now, the application name is the name provided in the Application name column on the db.  ![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/7d26598a-ef50-41c8-9e37-be9c59fd691b)

**Comment by ianliuwk1019** [comment]
Hm... as the title almost suggest this is a database change, so sorry that I missed the second point.
However, do you like to cut the second point to another ticket for discussion? I think second point will involve backend, frontend and also openapi change and.
@ArogeG @basilv 
As for "app_environment", this was discussed with Conrad/Basil and intended as nullable from my understanding.

**Comment by basilv** [comment]
My interpretation for MVP was that we just display the application name (which includes the environment) and that is the simplest way to achieve the requirement for MVP.

The environment column needs to be nullable for the special case of FAM, which to avoid confusion we don't want associated with an environment based on Gbola's suggestion that I really liked during the discussion on environments and managing access by environment. E.g. we just list FAM with no environment in the list of applications. Currently, granting access to FAM_ACCESS_ADMIN applies to the entire FAM instance (so dev, test, and prod environments for FOM).

**Comment by ArogeG** [comment]
created a different  ticket for the app + dev name: https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/417
