### ISSUE TITLE
 Return Abstract FAM Role in the Get Role Assignment Endpoint

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#339]
**Describe the bug**
 Role name for FOM_Submitter we want to just be FOM_SUBMITTER without the forest client number suffix. 

**To Reproduce**

**Expected behavior**
When a concrete role that relates to an abstract role, return the name of the abstract role for display in the frontend

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/4a00af00-b220-4e8f-b026-894360408a7b)

**Comment by NickSaglioni** [comment]
@ArogeG @gormless87 I have a question about this task. I have identified that there is a way of doing this change in the frontend only, avoiding messing around with the backend and the DB. Are there any other places where this abstract role should be shown as well? Thank you.

**Comment by ArogeG** [comment]
@NickSaglioni The abstract role is currently only used in the Get Role Assignment and the Get roles endpoints. I think this abstract role display is only required on the Manage Access screen of the front-end.
