### ISSUE TITLE
Orientation to API tasks

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#346]
**Describe the task**
@ianliuwk1019 to help @NickSaglioni get familiar with the FAM API

**Acceptance Criteria**
- [ ] Nick and Ian have shared knowledge
- [ ] Nick can begin to take on some API tasks 

**Additional context**
- Also consider doing some pair programming sessions

**Comment by ianliuwk1019** [comment]
Gave overview to Nick and did some troubleshooting on his environment together on Dec 23rd.
