### ISSUE TITLE
Test API secured API endpoints 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#354]
**Describe the task**
Following from #(?) the secured endponts need to be tested rigorously before the secuity pattern is applied to the rest of the endpoints

**Acceptance Criteria**
- [ ]  Switch frontend URLS for two secured endpoints and report back

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by basilv** [comment]
I've started testing, see comment on issue #347

**Comment by basilv** [comment]
Completed testing and provided feedback on issue #347. Main outstanding issue is that applications endpoint needs to filter results to only return applications for which the user belongs to the {app}_access_admin role.  Informed Conard, he'll be raising a new issue to address that.
