### ISSUE TITLE
Scope API methods for row-level security rules

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#359]
We missed a requirement when we wrote **https://github.com/bcgov/nr-forests-access-management/wiki/API-Security**.

Excerpt:

**There is a business rule that these endpoints should only return data that is associated with applications for **
**which the user has {appname}_ADMIN role.** For example, if the user has FAM_ADMIN but not FOM_ADMIN, "Get FAM applications" returns only the "fam" application object and not the "fom" application object. Likewise, "Get FAM Roles" in this scenario would return roles associated with the "fam" application object and not the "fom" application object.

Currently these endpoints do not filter based on the fam permissions, they just return all the data.

- [ ] Add filter to "Get Fam applications"
- [x] Add filter to "get fam roles" ("/{application_id}/fam_roles" is already scoped to roles for the application in question. "/fam_roles" is disabled with a 501 (not implemented) since it's not being used and the same thing can be accomplished with the previous.

**Comment by ConradBoydElliottGustafson** [comment]
@gormless87 @basilv This is the issue that tackles the defect identified by Basil. Not that hard if you want to take a crack at it. Automated tests might be tricky, but if you skip that you could probably crank this one out.

**Comment by basilv** [comment]
Description looks good to me. The filter for getFamRoles is I think done (the API returns roles for single application, and if the user doesn't have access I believe a 403 is already returned. Unless my memory is off).

Some test cases for getFamApplications endpoint:
1. User with FAM_ACCESS_ADMIN and FOM_ACCESS_ADMIN has both applications returned (same as current behavior).
2. User with only FAM_ACCESS_ADMIN - has only the FAM application returned.
3. User with no ACCESS_ADMIN access to any applications - has no applications returned.

**Comment by ianliuwk1019** [comment]
Verified code at main branch, we still need to work on this "Get Fam applications" filtering.

**Comment by ianliuwk1019** [comment]
Hm... based on the rule "{appname}_ACCESS_ADMIN role" to filter the applications works. But that needs to hardcode the "_ACCESS_ADMIN" from the rule "{key}_ACCESS_ADMIN" in the backend code.
Somehow, not sure if our db model need to be evolved from this (maybe not now yet) so we(FAM Super Admin) have more flexible way and control to grant deep-nested levels roles without too much hardcode keys and rules in backend and also the admin person can create roles for any names they like (without needing to follow "_ACCESS_ADMIN"). Not sure if possible or maybe has been proved too complicated in the past.... just wondring...

For now I will reuse-refactor using Conrad's initial code to do the filtering using key "_ACCESS_ADMIN"
@ConradBoydElliottGustafson  @basilv

**Comment by basilv** [comment]
Yes, I expect this will need to evolve in the future, but it likely should be sufficient for MVP.

**Comment by ianliuwk1019** [comment]
While working on this application filtering, I have started also with improving a little on using [FastAPI global "Depends"](https://fastapi.tiangolo.com/tutorial/dependencies/global-dependencies/) when possible, that will reduce code needed for authorization in the business code itself. Also there are ["advanced dependencies"](https://fastapi.tiangolo.com/advanced/advanced-dependencies/) and ["advanced security"](https://fastapi.tiangolo.com/advanced/security/) that are worth considering for our FAM implementation as well.

But, later decided to leave it into another branch for the later improvement.
The branch for the improvement is here: https://github.com/bcgov/nr-forests-access-management/tree/feat/359-auth-dependency-injection-partial-work.
Partial work was done, maybe worth taking advantages of it when we work on ticket #367.
