### ISSUE TITLE
Internal STRA 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#362]
**Describe the task**
Document risks, propose solutions or highlight for further consideration

**Acceptance Criteria**
- [ ] Internal TRA 
- [ ] Gbola to review 

**Additional context**
- TRA doc in Confluence: FAM Threat and Risk Assessment

**Comment by basilv** [comment]
See https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/FAM+Threat+and+Risk+Assessment.
