### ISSUE TITLE
Manually create definitions for IDIR IDP and attribute mapping

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#37]
The IDIR IDP in Keycloak maps certain attributes; We want our IDP to map the same attributes to it is mostly transparent whether you have logged in via Cognito or Keycloak.

AC:
Can create a test client that allow login via IDIR and it creates a jwt that has the same attribute mapping as the jwt you would have gotten from Keycloak.
All attribute mappings are understood and documented

Map the following fields as oidc standard names (no name changes):

  "name"
  "given_name"
  "family_name"
  "preferred_username"
  "email"  
  "email_verified"

Map the following fields as cognito standard names (change from keycloak mapping to standard cognito)

  "username" -> "idir_username"

Add the following Cognito-special fields:

  "identity_provider": "identity_provider"
  "display_name" -> "display_name"
user_guid (map to "idir_user_guid")

**Comment by ConradBoydElliottGustafson** [comment]
Here's what comes back in the auth token from Keycloak: 

{
  "exp": 1663633665,
  "iat": 1663633365,
  "auth_time": 1663633236,
  "jti": "802ee49c-c081-4af3-a9f5-3ce7e90b6450",
  "iss": "https://dev.loginproxy.gov.bc.ca/auth/realms/standard",
  "aud": "fsa-cognito-idir-sm-dev-4107",
  "sub": "b5ecdb094dfb4149a6a8445a01a96bf0@idir",
  "typ": "Bearer",
  "azp": "fsa-cognito-idir-sm-dev-4107",
  "nonce": "aa2b118a-b85d-42fa-a735-2f29c321d9d6",
  "session_state": "0e64e935-65f0-4907-a6e1-8e108ac235ad",
  "scope": "openid idir email profile",
  "sid": "0e64e935-65f0-4907-a6e1-8e108ac235ad",
  "idir_user_guid": "B5ECDB094DFB4149A6A8445A01A96BF0",
  "identity_provider": "idir",
  "idir_username": "COGUSTAF",
  "email_verified": false,
  "name": "Conrad Gustafson",
  "preferred_username": "b5ecdb094dfb4149a6a8445a01a96bf0@idir",
  "display_name": "Gustafson, Conrad CITZ:IN",
  "given_name": "Conrad",
  "family_name": "Gustafson",
  "email": "c.gustafson@cgi.com"
}

**Comment by ConradBoydElliottGustafson** [comment]
Here's what comes in the ID token from Cognito:

{
  "at_hash": "YTrnTsHNEnIlvw_3cWRTeQ",
  "sub": "13844749-eb91-4b64-9f2c-31ad6045289e",
  "cognito:groups": [
    "ca-central-1_UWmSQsqLc_idir"
  ],
  "custom:identity_provider": "idir",
  "custom:user_guid": "B5ECDB094DFB4149A6A8445A01A96BF0",
  "iss": "https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_UWmSQsqLc",
  "preferred_username": "b5ecdb094dfb4149a6a8445a01a96bf0@idir",
  "identities": [
    {
      "userId": "b5ecdb094dfb4149a6a8445a01a96bf0@idir",
      "providerName": "idir",
      "providerType": "OIDC",
      "issuer": null,
      "primary": "true",
      "dateCreated": "1663376768397"
    }
  ],
  "auth_time": 1663801017,
  "exp": 1663804617,
  "iat": 1663801017,
  "jti": "cbb7464e-ead9-4c50-83d2-fd2c133bb8e3",
  "email": "c.gustafson@cgi.com",
  "email_verified": false,
  "pet_preference": "cats",
  "cognito:username": "idir_b5ecdb094dfb4149a6a8445a01a96bf0@idir",
  "custom:display_name": "Gustafson, Conrad CITZ:IN",
  "given_name": "Conrad",
  "nonce": "a132b52e-3b4c-4552-98e8-af12e9aab4ee",
  "origin_jti": "3547d75e-e81a-4355-a5a9-cd80ccefdaa6",
  "aud": "7urf5n4k3bb1249nkt2uoiupvq",
  "token_use": "id",
  "name": "Conrad Gustafson",
  "family_name": "Gustafson"
}

**Comment by ConradBoydElliottGustafson** [comment]
Documented on the WIKI: https://github.com/bcgov/nr-forests-access-management/wiki/OIDC-Attribute-Mapping
