### ISSUE TITLE
TF destroy cycle error

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#376]
**Describe the bug**
Terraform. Error: Cycle: aws_api_gateway_integration.fam_api_gateway_integration_proxy_root, aws_cognito_user_pool_client.fam_console_oidc_client, aws_api_gateway_deployment.fam_api_gateway_deployment, aws_api_gateway_integration.fam_api_gateway_integration_proxy

**To Reproduce**

**Expected behavior**
Process works, all pertinent infrastructure elements destroyed

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by basilv** [comment]
Findings/progress:
- Added terraform continuous integration job as part of 380 to help troubleshoot. CI job fails on the "plan -destroy" with the same error as when the job is run.
- Found that test environment can be deployed and destroyed with no errors
- Tried manually deleting some resources in AWS (RDS proxy), but didn't help. 
- Suspect state inconsistency might be the culprit.

**Comment by basilv** [comment]
Continuous integration infrastructure github action just passed yesterday, so this is likely resolved. Testing now. Didn't explicitly change anything, perhaps the state inconsistency got fixed via some deployments to dev with actual changes (for vanity URL).

**Comment by basilv** [comment]
Destroy job is now succeeding for dev.
