### ISSUE TITLE
UX review of current FAM frontend mockup

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#377]
**Describe the task**
Service Design to review of current FAM frontend mockup

**Acceptance Criteria**
- [x] Recommendations documented
- [x] lo-fi mockup for team discussion

**Additional context**
-includes environment changes

**Comment by OlgaLiber2** [comment]
UI mockups are in Figma: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?node-id=168%3A70475&t=fV8bNGuaN015ZzWl-1 

has a team discussion and a new ticket will be created to look into comments brought up by the team. Tasks include: 
- split the domain to show the IDIR from the domain seperately
- look into the search functionality 
- add forest client number to the table 
- find out if we need to display organization 
- ?filter by application environment
- fix breadcrumbs
- consider taking out part of the footer (showing the app page)
- look into the header
