### ISSUE TITLE
User Research and UI Design on Delegate Access Requirement

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#379]
**Describe the task**
Conduct user research on FAM Delegation and design UI for delegation requirements 

- Discuss with business application owners & existing access management team: (how do you vet incoming requests) about the process for understanding for identifying delegates.
- _**-How: Discuss with the business and streamline the process during service design:**_

**-Ability to create delegate roles for specific roles and forest client** 
As a application administrator, I want to assign delegate specific role(s)  to a user on FAM. 
-Ability to create delegate role and allow you to login to FAM and Assign users to a specific roles (Service Design)
   Delegate role could be unique to applications. 

**- Provision access to delegate users for only specific roles /forest client?**
As a delegate user I want to create role assignment  for  roles within my delegate authority for a specified forest client organization.
	

**Acceptance Criteria**
- [ ] Delegation requirements should be driven by at least thee user groups 
- [ ] FAM UI mockup should be developed for delegation requirements

Technical Design to follow once service design is completed.

**Comment by gormless87** [comment]
Superceded by #617
