### ISSUE TITLE
Scaffold api code and injest database defs

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#38]
* create a basic fastapi app.
* create a database / import DDL generated from ER Studio
* evaluate whether defs can be slurped into app. or define how database models can be handled external to fastapi / sqlalchemy framework

Related Issue: https://github.com/bcgov/nr-forests-access-management/issues/20

**Comment by franTarkenton** [comment]
phase 1 of this ticket, ran the ddl that was output from SQL developer.  Now working on evolving this to run the flyway migrations instead

**Comment by gormless87** [comment]
Confirm with @franTarkenton that this is still outstanding  @rparfig - have the latest data model changes been pushed?

**Comment by rparfig** [comment]
@franTarkenton @gormless87 : Yes, the latest data models were deployed more than a week ago.

**Comment by rparfig** [comment]
@franTarkenton @gormless87 : It is not possible to find the creation date of the tables in Postgres using SQL, but I have done a review of the changes made in the data model against the database and the latter IS reflecting the last changes made. The last DDL was committed to GitHub on main. 

https://github.com/bcgov/nr-forests-access-management/pull/77/commits/931f720013eb6b5b7a0390d1eb8280bbe3d3f5f8

**Comment by rparfig** [comment]
@franTarkenton : Just curious, why are you pulling a DDL from SQL Developer when the DDL that reflects the model resides in Git?

**Comment by franTarkenton** [comment]
a bunch of work has been completed on other tickets that make this one a bit out of date / irrelevant.

The following PR https://github.com/bcgov/nr-forests-access-management/pull/98 includes the following work:

1. created a temporary postgres database
2. ran the flyway migrations against the database
3. used sqlacodegen to create a sqlalchemy model from the physical postgres database.
4. Updated the backend/models/model.py file the model generated from sqlacodegen
5. unittests then started failing due to integrity constraints... Addressed the integrity constraints so that all tests now pass
