### ISSUE TITLE
Update Terraform Scripts to populate Alternate Domain name and AWS certificate for Cloudfront 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#380]
**Describe the task**
Change terraform scripts to populate the alternate domain name and AWS certificate for Cloudfront.

Domain name for FAM has been created and TLS/SSL certificate have been created on AWS. This task is to create a similar script on Terraform to support the pipeline and ensure that the certificate and domain names are populated with every destroy and create. 

**Acceptance Criteria**
- [ ] After every terraform destroy, the deployment should associate Alternate domain name and AWS certificate to Cloudfront
- [ ] Alternate Domain name and certificate should be created for Dev, Test, and PROD. 
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by basilv** [comment]
In progress - populating done, now need to parameterize

**Comment by basilv** [comment]
As part of this I'm cleaning up all the github actions and adding a terraform CI job.
