### ISSUE TITLE
MVP 1.0 behavior-based test setup

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#388]
**Describe the task**
Persona-based test scripts
Need to test in the TEST environment - data setup?
Also need to test in PROD

**Acceptance Criteria**
- [ ] Document test flow - checklist
- [ ] Specify behaviors to test
- [ ] 

**Additional context**
- Use DEV to inventory testing steps

**Comment by ianliuwk1019** [comment]
Sample [FOM Test Script](https://app.zenhub.com/files/486378283/d114a0a5-58b2-48ad-b823-a8988d9a9b33/download) attached.

**Comment by MCatherine1994** [comment]
Thanks Ian!

**Comment by MCatherine1994** [comment]
[https://app.zenhub.com/files/486378283/af83b77e-8e9d-4cd1-b61b-d07913be0dac/download](https://app.zenhub.com/files/486378283/af83b77e-8e9d-4cd1-b61b-d07913be0dac/download) Upload the first version of the test script for review!

**Comment by ArogeG** [comment]
Test script seems to cover the different use cases. Hoping to review comments with @MCatherine1994 on Tuesday.
