### ISSUE TITLE
Add UTC time zone to DATA columns

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#389]
**Describe the task**
Change timestamp columns to include time zone (TIMESTAMPTZ)  --UTC time zone

**Acceptance Criteria**
- [ ] all DATE datatype columns in the database are changed to include timestamp

**Additional context**
- Based on Basil's comment on #359:

Here's my assessment of what's outstanding and what needs to be done:
Pre MVP:

Change timestamp columns to include time zone (TIMESTAMPTZ)

**Comment by MCatherine1994** [comment]
I'm not sure if we really need make this change. When I check the Postgres db run on local, by default it's using the "UTC" timezone, and seems like the local timestamp already returns the time in "UTC" timezone:

![image.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/291bea0e-60b7-4a75-bfb6-2dbbe7a8c60e)
