### ISSUE TITLE
Create definitions for BCeID *Basic* IDP and attribute mapping

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#39]
The BCeID Basic IDP in Keycloak maps certain attributes; We want our IDP to map the same attributes to it is mostly transparent whether you have logged in via Cognito or Keycloak.

AC:
Can create a test client that allow login via IDIR and it creates a jwt that has the same attribute mapping as the jwt you would have gotten from Keycloak.
All attribute mappings are understood and documented (inside Terraform)

**Comment by MCatherine1994** [comment]
Close it for now, will reopen it if get this request later
