### ISSUE TITLE
Complete PROD BCeID Cognito detail

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#390]
**Describe the task**
Final steps for Cognito setup following BCeID approval

**Acceptance Criteria**
- [ ] make github secrets environment changes
- [ ] test the changes

**Comment by ConradBoydElliottGustafson** [comment]
@ArogeG @gormless87 The changes are made. I just realized I don't have a production BCeID account to test with. Does anybody have such a thing?

**Comment by ArogeG** [comment]
@ConradBoydElliottGustafson  do you need to login, or you just need an ID?

**Comment by ConradBoydElliottGustafson** [comment]
Just need somebody to test the login. I have the process to ask for a "test" BCeID business credential in production. I'll go through that and the team can share it for production smoke testing.

**Comment by ArogeG** [comment]
This is my BCeID: GAtitebi
