### ISSUE TITLE
Login issue in TEST 

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#398]
**Describe the bug**
TEST env login issue see screenshot for console error msg

**To Reproduce**
1. Go to homepage
2. Click on 'login'

**Expected behavior**

**Screenshots**
![image.png](https://images.zenhubusercontent.com/61f87aa78804f87afc5530bd/93e7c2a7-6af4-46dc-a90f-b3b1d5f8ce7b)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ConradBoydElliottGustafson** [comment]
Configuration items in terragrunt were mangled. Fixed a cut&paste error. Didn't show up in DEV because that one was fine. Probably should have done more testing before I went on vacation, but I was up until 9PM coding before catching a plane the next day!!
