### ISSUE TITLE
Error loading applications after login or after leaving application sit unused

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#399]
Quite frequently for multiple people in the dev environment, when going to the select application page it displays an error due to failing to load applications.

The problem goes away after refreshing the page.

This problem can happen immediately after login, or can happen if leaving the app sit unused for ~60+ minutes.

My theory is one of two things:
1. browser concurrency issue between the authCallback page and the selectApplication view. I suggest moving the loading app logic into the auth callback.
2. token or session timeout.

**Comment by basilv** [comment]
I started working on this, but more to clean up code and add console logging, see my branch/draft PR. Open to others helping troubleshoot the actual issue.

**Comment by ianliuwk1019** [comment]
Just a not for observation from AWS log from CloudWatch:
It seem 399 issue (so far I tried) is not related to frontend code.
It is more like AWS some timing out (lambda? or probably RDS?)
It happens consistently but can goes away (if probably constantly hitting api into database). The log showing this:
d0464206-9b58-4456-af31-14e2b1a95e89 Task timed out after 3.04 seconds and that's when the frontend browser does not get the response back.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/92f1367d-e935-4fc1-8100-8ac1d4805bee)

**Comment by basilv** [comment]
As of this morning, still seeing error post-login sometimes, but now the front-end is automatically retrying and ends up loading the application list successful. So we just want to stop displaying an error message if we are going to retry.

**Comment by ianliuwk1019** [comment]
This is tricky and does not happen always.
I had to change backend to randomly throw exception to simulate errors return to frontend in order to deep dive into the issue.
I saw that if there were already reties 401 twice then when the next time 401 happens again, it did not seem to retry anymore for second 401 and so the toast message pops up.
Solution is add missing 'reset' the retry count back to 0 when the retried request indeed was successful.

**Comment by ArogeG** [comment]
I encountered a similar error at about 2:50pm (feb 14) today, when I attempted to load the FAM home page.  I'm will move  this ticket to MVP1.1 for the team to monitor and investigate a bit further during the technical sprint.

**Comment by ianliuwk1019** [comment]
> I encountered a similar error at about 2:50pm (feb 14) today, when I attempted to load the FAM home page. I'm will move this ticket to MVP1.1 for the team to monitor and investigate a bit further during the technical sprint.

Hi @ArogeG , do you have steps to reproduce or screenshot so it will be easy to know what happened if we need to investigate further? Thanks.
