### ISSUE TITLE
Create definitions for BCeID *Business* IDP and attribute mapping

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#40]
The BCeID Business IDP in Keycloak maps certain attributes; We want our IDP to map the same attributes to it is mostly transparent whether you have logged in via Cognito or Keycloak.

AC:
Can create a test client that allow login via IDIR and it creates a jwt that has the same attribute mapping as the jwt you would have gotten from Keycloak.
All attribute mappings are understood and documented (inside Terraform)

**Comment by ArogeG** [comment]
Conrad is working on a documentation in the Wiki.

**Comment by ConradBoydElliottGustafson** [comment]
Documentation complete: https://github.com/bcgov/nr-forests-access-management/wiki/OIDC-Attribute-Mapping
