### ISSUE TITLE
PROD rollback/recovery testing prior to go-live

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#400]
**Describe the task**
Prior to full go-live, we want to confirm the deploy/rollback/restore procedures execute as expected in PROD

**Jan 26: More discussion from Team needed to establish the scope of this exercise**
**Acceptance Criteria**
- [x] deployment confirmation
- [x] database recovery confirmation
- [x] documentation is updated

**Additional context**
Last opportunity to test procedures before a a real workload is supported
--Pair programming opportunity

**Comment by ConradBoydElliottGustafson** [comment]
Did restore from snapshot. Pointed RDS-proxy to the new DB, but got an error: ![image.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/661be5c1-f7c7-4cd0-9950-3037b03e476c)

**Comment by ConradBoydElliottGustafson** [comment]
Another interesting problem: following the wiki instructions, I renamed the restored cluster, but not the writer instance. When TF ran, it created the two instances specified in the HCL, but it added them both as reader instances and left the old writer instance sitting there. Maybe the procedure should be to rename the writer instance as well.

![image.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/9767ca78-632d-4dc4-8924-f64a048df095)

**Comment by ConradBoydElliottGustafson** [comment]
Re-ran the terraform and got another error.

Error: registering RDS DB Proxy (prod-fam-cluster-fam-api-proxy-api/default) Target: DBProxyTargetAlreadyRegisteredFault: The target group prx-tg-099052e261fa670b1 already has other registered targets. Registering multiple targets is not supported at this time.
│ 	status code: 400, request id: 05e49d3e-fcba-44cf-8057-5675a5701919
[https://app.zenhub.com/files/486378283/69171312-c221-47d4-8768-0533e4065a32/download](https://app.zenhub.com/files/486378283/69171312-c221-47d4-8768-0533e4065a32/download)

**Comment by ConradBoydElliottGustafson** [comment]
Did a LOT of testing and put some love into the wiki documentation. Also discovered a pipeline bug -- the flyway lambda function does not support running the deploy workflow from a tag (instead of a branch). @gormless87 we should fix this as a "tech debt" item so we can have simpler release management as per @basilv 's release management confluence documentation.
