### ISSUE TITLE
Onboard FAM with Client Management System- FAM DEV

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#401]
**As a** *Developer* **I want** Integrate the client management system with FAM* **So That** I can manage authentications and authorizations for the client management system with FAM. 

**Additional Context**
**- FAM Related Task**

- Set up application client in FAM

- Assign FAM admin roles to administer specific applications

- Create OIDC client for application based on the number of APPs

- Create Cognito OIDC record for app integration on the database

**Client Management  Possible Task**

- Set up Client  back-end with configuration details for Cognito including urls.

- Change Client  API back-end decryption of JWT token to use FAM certificate (public cert for decryption)

- Setup Client front-end with cognito login on all environment

- Update CORS url to point to Cognito

- Design login/logut chain for application (explore setting up the chain implementation on FAM)

Begin with Dev integration first

**Acceptance Criteria**
- [ ] Given that Roles have been obtained from the client management team, create roles for the client management system. 
- [ ] Given that the integration is complete, client management system should be able to authenticate and authorize through FAM. 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by ConradBoydElliottGustafson** [comment]
Yeah, I think this is done and in production. Some of the description on this ticket doesn't completely make sense. I think we should close this.
