### ISSUE TITLE
Explore test container for Postgres testing

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#403]
test container for python: https://testcontainers-python.readthedocs.io/en/latest/README.html
test container example to run docker compose file: https://medium.com/swlh/testcontainers-in-python-testing-docker-dependent-python-apps-bd34935f55b5

pyway: https://pypi.org/project/pyway/, latest version published in 2020, not sure if we really need it, but at least good to take some look

**Comment by ianliuwk1019** [comment]
The comment added in PR link (https://github.com/bcgov/nr-forests-access-management/pull/465#issuecomment-1452479279) for reference.
When we later migrate existing tests from Sqllite to using 'Testcontainers' we should watch out for running time for all tests.
