### ISSUE TITLE
Make ci_infrastructure.yml jobs execute in series

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#415]
**Describe the task**
There are some github actions that should be in series but are currently in parallel

**Acceptance Criteria**
- [ ] Checkin Terraform Plan checks are in run in series

Looks like it was previously running in series but commented out for some reason. Code is in ci_infrastructure.yml

![image.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/7f2deccd-ce5f-44d9-bbe7-c77cff7f8638)

**Comment by basilv** [comment]
Did this as part of #421 investigation as terraform changes were needed and running in parallel caused a failure due to inavailability of terraform cloud.
