### ISSUE TITLE
Change Token Timeout from 60 mins to 5 mins to ensure permission changes are reflective in 5 mins or less

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#418]
**Describe the Task** 

Change Token expiry to 5 mins timeout. Here the refresh token can be used to get the new access token with any changes that might have been made. 

This will reduce the time it takes for permission changes on FAM to be effected. 

............................
**Additional Information.**
When access is removed from an App, the app remains available to the user on FAM until the user logs in and out. After I removed my access to Forests Operation Map (Prod), I was still able to select the app from the application list and I was able to Grant access on FOM (Prod). Upon logging in and out,  the record created after my access was revoked was still available. 

Token should be expired in 5 mins -timeout. The refresh token can be used to get the new access token. 
Calls the auth function. 

*Describe the bug**
When access is removed from an App, the app remains available to the user on FAM until the user logs in and out. After I removed my access to Forests Operation Map (Prod), I was still able to select the app from the application list and I was able to Grant access on FOM (Prod). Upon logging in and out,  the record created after my access was revoked was still available.

**Comment by MCatherine1994** [comment]
update "access_token_validity" and "id_token_validity" in the terraform config for oidc_clients_fam and oidc_clients_fom

**Comment by ArogeG** [comment]
I'm not sure that this fix solves the problem of access changes being reflected within 5 mins.
