### ISSUE TITLE
Create Cloud-watch monitoring dashboard and alarms in PROD

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#425]
**Describe the task**
Create a cloudwatch dashboard similar to the dashboard in Dev to support uptime monitoring. 

Dashboard should include metrics on the following:

- Lambda Errors

- API gateway 400 & 500 errors

- Lambda Invocations

-Latency 

- RDS CPU usage and 

- Concurrent Executions 

**Acceptance Criteria**
- [ ]Dashboard should be similar to dashboard created in Dev 
- [ ] Alarms should be sent to the fingerprint distribution mailbox. 
- [ ] third

**Additional context**
- See details of CloudWatch monitoring here: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/FAM+Operations#FAMOperations-MonitoringDashboard
- Or here

**Comment by basilv** [comment]
@ArogeG I suggest someone else on the team make the prod dashboard as a learning opportunity, based on the specification I created on the FAM Operations confluence page.

**Comment by basilv** [comment]
I reviewed prod and it looks good now. This can be closed.
