### ISSUE TITLE
Change Configuration to navigate to CLP from the FAM Home Page

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#426]
**As a** FAM User* **I want** to be directed to the Common Login Page after I click on Login on the FAM home page* **So That** *I would have less steps when logging in to FAM.

**Additional Context**
On the FAM Home Page/ Sign-in page, add two buttons for IDIR and BCeID IDPs. 
When the IDP button is selected,  navigate user to the common login page directly and hide the Cognito User pool page 

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/23dfbe8e-98c2-48fa-a66f-7a0709d6677d)
**Acceptance Criteria**
- [ ]When the IDP button is selected,  navigate user to the common login page directly and hide the Cognito User pool page 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by gormless87** [comment]
Duplicates #464
