### ISSUE TITLE
FAM Logout Chain

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#427]
**As a** FAM user * **I want** to logout of keycloak and siteminder  **So That** when I am required to authenticate every time I login to FAM*

**Additional Context**
- Change the logout up the chain, so that a logout from cognito, log users out upstream: Keycloak and Siteminder. 
-- See https://stackoverflow.developer.gov.bc.ca/questions/83/84 for Marco's take on this

**Acceptance Criteria**
- [ ] When a user clicks "logout" on FAM, they no longer have an active session on Cognito, Keycloak, or SiteMinder
- [ ] When a user starts a logout process for FAM (or any other app that shares SSO sessions at either Keycloak or Siteminder), the user must re-enter their credentials at Siteminder.
- [ ] Having logged out of FAM, the next login attempt should route users to the CLP page for a re- authentication. 

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

Tests: 
- try using the cognito refresh token to obtain a new access token
- try using the keycloak refresh token to obtain a new access token

**Comment by MCatherine1994** [comment]
We chain the logout back to siteminder is because the logout from cognito won't invalid the session from Keycloak and siteminder. So we have to chain back to actually invalid all the user sessions.

**Comment by MCatherine1994** [comment]
Chatted with Marco Villeneuve from Pathfinder team:

- logout from Cognito won't log us out automatically from Keycloak, so we want to chain the logout url
- the Keycloak logout redirect_uri parameter is deprecated, if the new Keycloak version v20 will not support it anymore, then we can't use it anymore, we have to change to the combination of post_logout_redirect_uri and id_token_hint
- for now just test the Keycloak logout using redirect_uri, but it doesn't support multiple parameters in the url

**Comment by MCatherine1994** [comment]
Finally found a simpler solution for now:

Amplify library method `Auth.signOut()` can log the user out from Cognito, so we don't need to call the Cognito logout url anymore.

So the logout chain will just call the SiteMinder logout, chained to the Keycloak logout, then back to our application logout page. `https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=http://localhost:5173`

A small UI issue for this method is that, both "Auth.signOut()" and the logout chain will do a redirect to the application page, so it will do the redirect twice
