### ISSUE TITLE
Add redirect callback url and display name for FOM in the infrastructure config file 

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#430]
Add the redirect callback and sign out urls to the config file for FOM client, so it won't disappear after redeployment. 

Add attribute mapping for display name vs custom:idp_display_name

**Comment by ianliuwk1019** [comment]
For Cognito "redirectSignin" Url setting for FOM (for admin frontend, only admin needs signin). Confirm these URL with Basil:

Dev (question):
https://fom-dev.nrs.gov.bc.ca (? or is it dynamic route based on PR number?)
or just use http://localhost:4200?

Test:
https://fom-test.nrs.gov.bc.ca

Prod:
https://fom.nrs.gov.bc.ca
