### ISSUE TITLE
Make CD pipeline work based on GitHub tags

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#435]
As a release manager, I want to trigger a Github action to deploy a version of FAM based on a release tag in the repository (not a branch)

**Additional Context**
Currently, the flyway lambda function is passed information about the github branch that is being deployed. When the lambda is run, this github context is passed as parameters to the execution call. The lambda function downloads the repo (at the correct branch) to get the scripts. When we deploy from a tag, the lambda function code (not our code) gets confused and can't download the repo.

**Acceptance Criteria**
- [ ] Make a new S3 bucket in the infrastructure. Upload the flyway sql scripts to the bucket before running flyway
- [ ] Run flyway with an S3 configuration (instead of a github configuration). Will require permissions in AWS

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by MCatherine1994** [comment]
Duplicate as #438
