### ISSUE TITLE
Discussion: Database Model Management Pattern

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#452]
**Describe the task**
Discuss the proposed Database Model Management Pattern.

https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=146449362

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
remove above confluence page?

**Comment by OlgaLiber2** [comment]
@OlgaLiber2 archive confluence page
