### ISSUE TITLE
FAM User guide

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#456]
Describe the task
As a Development team member looking to leverage FAM I want a complete and concise User Guide for integrating with FAM so that I can reliably and efficiently carry out required tasks with consistent results.

Acceptance Criteria
[ ] - How do I onboard to FAM --how to request, who to talk to, how to troubleshoot
[ ]  - Technical integration - get and use
[ ] - Configuration parameters
[ ] - Lives in GH Wiki

 

Additional context
[ ] - Counterpart documentation Ops Guide is described in #296

**Comment by MCatherine1994** [comment]
Hi @Gbola, I wonder if in our questionnaire, we should ask our user what IDP attributes they want? I assume most likely just username or user id? Just thinking team Alliance might request more, shall we add that question in the questionnaire if we're going to use that to onboard new project?

**Comment by MCatherine1994** [comment]
FAM Onboarding User Guide: https://github.com/bcgov/nr-forests-access-management/wiki/FAM-Onboarding
FAM Onboarding Ops Guide: https://github.com/bcgov/nr-forests-access-management/wiki/FAM-Onboarding-Ops-Guide, not sure when to give the prod ids yet

**Comment by ArogeG** [comment]
@MCatherine1994  I like the idea of adding attributes to the onboarding questionnaire. We could potentially, add the available attributes as multi select options for the PO to select from.  We should add it to the questionnaire.

**Comment by ArogeG** [comment]
For the FAM Onboarding User Guide, looks good but I have a couple of questions. I think it is important that another team member uses the guide to onboard an application. Scheduled a meeting with Catherine on Friday to walk through the document together.

**Comment by ArogeG** [comment]
Reviewed with Catherine, Gbola to make a few more edit but this task is done.
