### ISSUE TITLE
FAM Pipeline TEST Environment API Gateway Deployment Strange Behavior Issue. 

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#457]
During last FAM pipeline (Terraform) deployment to TEST (Feb 19/20/21), some strange deployment/state were observed (after successfully deployed to AWS).
- TEST frontend (when user is signed-in) attempted on API calls failed for some CORS reason (allowed-origin issues), although the current default was "*" (allow all origins). The cause is believed to be from AWS API Gateway (something to do with its setup).
- When redeployed to TEST (by changing api-gateway.tf for trying out some settings for allowed-origin), although deployment were successful, the values changed did not appear to take affect (for example: deploy #2 and deploy #3 did not change deploy #1 values).
- More obvious was that DEV does not have problem after deployment for API Gateway (deployed often) and so was the first PROD environment release deployment was also good on the API Gateway.

Also the deployment outcome look different (don't know why) on proxy and trigger (lambda):
- Dev:
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/4e28869a-4bbc-43b4-930e-a2ca5d3cc863)
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/fa093890-1566-4a27-886b-1cdad536c751)

- TEST:
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/9f9d05ea-159e-4ab3-bf52-a11365f67f24)
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/84427a7d-e3b2-4b67-b340-b104bb9e8120)

- PROD:
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/7519b0e9-c841-4082-a8b5-4942a2843819)
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/de2da903-ce21-4464-8d70-0ec2b0352a0a)

The same terraform api-gateway.tf is being used for all 3 environments for deployment but we don't know why TEST behavior differently.
The quick solution might be to remove from AWS console for TEST API Gateway then try deploy again using pipeline/Terraform and see if it will restore back to normal state.

**Comment by MCatherine1994** [comment]
Think this is gone after we did the destroy and redeployment
