### ISSUE TITLE
Fix CORS origin to be secure for TEST & PROD

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#472]
**Describe the task**
Fix CORS origin to be secure for TEST & PROD

**Acceptance Criteria**
- [ ] frontend works
- [ ] Open API works
- [ ] <s>OIDC debugger works in DEV & TEST</s>

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
While researching this, found that Api backend is the most appropriate place to do CORS, not the api gateway and backend can also handle multiple origins. For our python FastAPI framework, it is set in middleware.
Also while trying out implementation, CORS issue is always confusing, but realized that we don't need to bother for the "oidc debugger" and OpenAPI docs is at the same origin as API so there is no need to worry.
The only thing need to set is frontend domain and also consideration for local development.

**Comment by ArogeG** [comment]
@ianliuwk1019, I might need you help reviewing this. Lets talk after scrum.

**Comment by ArogeG** [comment]
Reviewed this with Ian. The CORS origin has been restricted to the FAM domain for Dev, TEST and Prod.
