### ISSUE TITLE
Spike: Investigate the impact of using SQLaCodeGen to generate the ORM model

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#474]
**Describe the task**
 Investigate the impact of using SQLaCodeGen to generate the ORM model since it uses a lower version of SQL Alchemy

**Acceptance Criteria**
- [x] impact for the different version of sqlalchmy
- [x] if we can use SQLaCodeGen or we need to generate the ORM model manually 
- [x] review documents related to Alembic

**Additional context**
- With the existing sqlite test, if we regenerate the ORM model, it might break the sqlite test, need to verify the tests

**Comment by MCatherine1994** [comment]
Looks like it has a pre-release recently that supports the sqlalchemy version we're using
Link to SQLAcodegen GitHub repo: https://github.com/agronholm/sqlacodegen
Link to SQLAcodegen Pypi package: https://pypi.org/project/sqlacodegen/
![Screen Shot 2023-04-25 at 10.36.00 AM.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/850cebec-7f47-45b8-b517-77f50cc2c43e)

**Comment by MCatherine1994** [comment]
It doesn't support the Unique Index we created in the fam_user table, but other than that seems work fine

SAWarning: Skipped unsupported reflection of expression-based index fam_usr_uk

**Comment by MCatherine1994** [comment]
Upload a file for the comparison of our current model vs. the generated model:

[https://app.zenhub.com/files/486378283/0487c4b6-2c90-4e93-b0f5-4b639fb4d6c9/download](https://app.zenhub.com/files/486378283/0487c4b6-2c90-4e93-b0f5-4b639fb4d6c9/download)

**Comment by MCatherine1994** [comment]
Reviewed the documentation `server/backend/api/alembic/readme.md` and `server/backend/api/alembic/dbMigrationsBackground.md`
