### ISSUE TITLE
Eliminate random pet names in terraform AWS infrastructure

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#475]
Need to consider how to roll this out to prod where our existing infrastructure already has pet names.

Primary purpose of doing this is to simplify monitoring and make it easier for support staff.

I'd recommend all resource names should still be prefixed or suffixed by environment, although this isn't necessary with our current environments.
- [x] resource "random_pet" "auth_lambda_name" (auth lambda name)
- [x] resource "random_pet" "api_lambda_name" (api lambda name)
- [x] resource "random_pet" "flyway_lambda_name" (flyway lambda name)
- [x] resource "random_pet" "flyway_scripts_bucket_name"  (s3 bucket for flyway)
- [x] resource "random_pet" "lambda_bucket_name" (web app resources for CloudFront)

No longer used -- can delete with no consequence
- [x] resource "random_pet" "famdb_subnet_group_name" (subnet for RDS)

This secret name is not really used as a secret.  It's holding a value in order to break a CI/CD circular dependency. I think we can leave this one without impact to setting up monitoring
resource "random_pet" "fam_oidc_client_id_secret_name" (client ID for FAM to use to validate tokens)

No need to change these secret names, and it would create a ton of overhead (DB scripts, etc.) Also, secrets are kind of unique in the AWS SEA as they can't actually be deleted. Also kind of weird because the old flyway scripts would fail without these. We could change everything to point to a new "non-random" secret name, but we would have to keep these in any case. No real reason to change them because we're not going to build monitoring off them as far as I know.
resource "random_pet" "master_creds_secret_name" (credentials for DB root user)
resource "random_pet" "api_creds_secret_name"  (credentials for API user)

**Comment by ConradBoydElliottGustafson** [comment]
Found an AWS bug. Reference here: https://stackoverflow.com/questions/54067224/execution-failed-due-to-configuration-error-invalid-permissions-on-lambda-funct
