### ISSUE TITLE
Deploy API as Lambda using Terraform

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#48]
Wrap fastapi in a Lambda function and deploy to AWS via terraform need db connection via db proxy

AC:
-can execute all endpoints via http request
-database connection as per example app added to code

--create separate issue for:
API gateway to expose API to internet via AWS
E2E testing of API endpoints

**Comment by franTarkenton** [comment]
potential article to help with this ticket: 
https://www.deadbear.io/simple-serverless-fastapi-with-aws-lambda/

**Comment by explorertolu** [comment]
The lambda function for the sample API has been deployed to AWS via Terraform, the database connection using AWS secret manager (via Terraform) has been completed as well.
