### ISSUE TITLE
Import FOM users assignments in Keycloak to FAM FOM Prod. 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#481]
**Describe the task**
Import FOM users assignments in Keycloak to FAM FOM Prod to support the cutover to FAM  

**Acceptance Criteria**
- [x] Retrieve  a list of FOM users in Keycloak and import record to FAM  
- [x] Data validation of the exported users and the Excel spreadsheet with FOM Users
- [x] Run against TEST  (KC PROD to FAM TEST)
- [x] Add Documentation to Ops Guide - steps for loading users to FAM from Keycloak
- [x] Cleanup DEV/TEST - removing PROD KC entries (SQL or via UI)

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by MCatherine1994** [comment]
Run the script one more time when we officially use FAM for FOM, run it in FAM PROD for FOM_PROD client, to make sure we get all the latest users from Keycloak

**Comment by MCatherine1994** [comment]
Sql script to clean up fom prod user in FAM TEST for FOM_DEV/TEST/PROD:

Run the following to remove user role assignment for FOM_DEV/TEST/PROD:
```
delete from fam_user_role_xref where user_role_xref_id in (select user_role_xref_id from fam_user_role_xref where role_id in (select role_id from fam_role where application_id=2));
```
Remove the users that don't have any role assignment:
```
delete from fam_user where user_id not in (select user_id from fam_user_role_xref);
```
Remove child role for FOM_DEV/TEST/PROD:
```
delete from fam_role where parent_role_id is not null and application_id=2;
```
Cleanup forest client table as no application has forest client records:
```
delete from fam_forest_client where forest_client_number is not null;
```
