### ISSUE TITLE
Create GitHub tag on merge

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#484]
**Describe the task**
Automate tag creation upon PR merge to identify the location of the code in the codebase and allow for automated versioning of release when there is a merge to main. 

**Acceptance Criteria**
- [ ] Whenever we merge from branch to Main, an automated tag will be associated to the PR. 
- [ ] second
- [ ] third

**Additional context**
- Leverage [Conventional Commit specification](https://www.conventionalcommits.org/en/v1.0.0/#specification) 
- We would need to distinguish between minor and major versions. 
-Determine the triggers for Tag creation.

**Comment by MCatherine1994** [comment]
If we're using release please, then that GitHub Action handles that for use, not need to worry about this by ourselves

**Comment by ConradBoydElliottGustafson** [comment]
Yep, this is redundant now that release please is tagging for us. Close.
