### ISSUE TITLE
UI Mockup For Forest Client API Front-end 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#489]
**Describe the task**
Create a UI Mockup for Forest Client Numbers that allows users to see the Client #, Company name, and Status

**Acceptance Criteria**
- [x] The mockup should be applicable to the current UI
- [x] The mockup should be reflective of the user interview sessions

**Additional context**
- Met with CLIENT AND RESULTS POs (Ziad and Caroline) to understand what information they want to see when they enter a Forest Client ID.

**Comment by OlgaLiber2** [comment]
Mockups are in figma. Had team and PO discussion and we are going ahead with "Mockup2" 

Link to figma:
https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?node-id=0%3A1&t=Grt1IvMM7lU63w7n-1

![forest client id- active status.PNG](https://images.zenhubusercontent.com/63b5e912a39d01413a894255/52d6f181-adf0-4c48-8dec-acf5532d0f3d)

![forest client id- inactive status.PNG](https://images.zenhubusercontent.com/63b5e912a39d01413a894255/97d03382-9001-4d9e-a440-e9d15194ad3f)
