### ISSUE TITLE
Create a FAM release for this sprint

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#493]
**Describe the task**
Building in #484, #485 setup to deploy a FAM release by end of this sprint

Release scheduled for Prod on March 27th/28th should include the following tickets:

- [ ] https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/506
- [ ] https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/516
- [ ] https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/519

A deployment to TEST can be attempted on March 24th if the tickets above have been completed and reviewed and merged. 

**Acceptance Criteria**
- [ ] tag created
- [ ] version created
- [ ]  Release notes on wiki
- [ ] deployed to dev/test/prod

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
Release created so far during this sprint:

1.1.0 (2023-03-25)
1.1.1 (2023-03-25)

**Comment by ArogeG** [comment]
@ConradBoydElliottGustafson and @catherine, I don't think there is a need for another deployment in this sprint.  Closing this ticket.
