### ISSUE TITLE
Create Random Test Data > 10,000 records for FAM DEV environment

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#499]
**Describe the task**
Generate random data for FAM Dev and Prod

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ConradBoydElliottGustafson** [comment]
What kind of random data. Lots of users? Lots of roles? Lots of applications? Not sure what this is going for. It would make more sense in the context of some kind of NFR test.

**Comment by ConradBoydElliottGustafson** [comment]
I guess loading up all the tables with data would tell us if our queries are efficient when there is lots of data.

**Comment by OlgaLiber2** [comment]
@ConradBoydElliottGustafson I'm not clear on the purpose of this ticket. I'm closing it.
