### ISSUE TITLE
SPIKE: how FAM works when a bceid or idir username changes

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#500]
**Problem statement:**
If we just store username in our database, when the idir or bceid user changed their username, we could end up in a situation that:

usernameA with guidA changes to usernameB with guidA......................usernameC with guidC comes along and changes to usernameA with guidC. If everything is based off username, usernameC just got access to whatever usernameA had access to

**Proposed solution:**

I saw in our fam_user table we have a column "user_guid", if we can integrate with the IDIR/BCeId API, and store the user_guid, then use the guid to identify the user. The guid for the user will not change and will always be the same. 
So in the case when the username changes, the application admin can try to add that new username in FAM. And on our side, when they click the "grant access" button, we check if we can found that guid instead of the username, and if found, then we do an update for the username. And in the normal case, we still do an insert for the real new user.

**Comment by ArogeG** [comment]
Currently, user guids are stored on the database once a user logs in. Once FAM integrates with IDIM web service, the user Guid will be stored with in the FAM database upon creating a role assignment on the grant access screen.
