### ISSUE TITLE
Spike: Design a process to manage data inserts when Onboarding Applications to FAM

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#503]
**Describe the task**
Design a process to manage data inserts when Onboarding Applications to FAM.  

- Explore options for onboarding applications without a hot fix. 
-This should include the ability to add roles and users without a deployment. 
-Also explore the ability to add applications if possible

**Acceptance Criteria**
- [ ] Potential solutions for each onboarding element are documented
- [ ] Possible alternative options for creating OIDC client or Cognito records
- [ ] Business friendly terms to replace 'concrete' and 'abstract' for role types

**Additional context**
- Adding an new customer application along with the associated roles, users and role assignments.
- Possibility to self-serve add applications, roles, users and role assignments via UI
- Potential for application and role management - renaming

**Comment by ConradBoydElliottGustafson** [comment]
This includes both data changes (adding a new application to the database)_ and terraform changes (creating a new Cognito client). I think a hotfix is the best way to go. It could be done manually and then imported into Terraform I suppose. Not a fan of inventing a new mechanism for no good reason.

**Comment by OlgaLiber2** [comment]
@ConradBoydElliottGustafson  I'm closing this ticket.
