### ISSUE TITLE
High level reference for provisioning access on FAM for Business Users

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#505]
Description
Please create a high level reference for provisioning access on FAM for Business Users and include the following points.

- FAM links (Test & Prod)
- FAM PROD environment and how to tell the difference between TEST and PROD
- The different supplementary/downstream apps environments available on FAM PROD for example: SPAR TEST, SPAR PROD, FOM Dev etc.
- Logging in and out of FAM
- Navigation to the Grant Access screen
- Navigation to the Manage Access screen

**Comment by OlgaLiber2** [comment]
I started a mural board mapping out user steps for completing certain actions (granting, managing, deleting access): https://app.mural.co/t/climatechange4363/m/climatechange4363/1679339811077/c4fda75657d83b58fc437978b08e11a4273b5a3a?sender=u84301558fa490f89e6792901

I will meet with Gbola on Wednesday (March 22) to get feedback if anything else needs to be added or taken out, then I will start compiling a document.

**Comment by gormless87** [comment]
Will not do at this time
