### ISSUE TITLE
Insert SPAR roles in FAM

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#506]
**Describe the task**
Please add the following SPAR roles to FAM

**SPAR Roles**
![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/23d366c3-10d7-41ef-b2b2-0e625edac735)

**Acceptance Criteria**
- [ ] add all the roles SPAR needs
- [ ] delete the test roles

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by basilv** [comment]
Do as a hotfix target March 24th.

**Comment by ArogeG** [comment]
Need to confirm if all the roles require a forest client (concrete roles /abstract roles)

**Comment by ConradBoydElliottGustafson** [comment]
the ALT-supervisor one requires a forest client as well.
