### ISSUE TITLE
UX for manage application roles

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#515]
**Describe the task**
- service design captures the UI for frontend for addding/updatting roles
- definition about what means of adding/updating roles
- who can do that, any access management
- any warnings when doing this
- role types (concrete vs abstract)
- if allow deleting roles

**Comment by OlgaLiber2** [comment]
@MCatherine1994 seems it's on a backburner for now so I will close this ticket and we can write a new one with more detail when the time comes.
