### ISSUE TITLE
Duplicate and Environment Conflict when Creating Role Assignment in PROD for FOM TEST for Client 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#516]
**Describe the bug**
When a role assignment record exists in an application's environment (DEV), the same role assignment cannot be created in the another environment(TEST). The system returns a duplicate record notification. 

When the record is deleted in one environment(DEV) and re-created in a different environment(TEST), the record is displayed in the previous environment (DEV)

**To Reproduce**
1. Go to 'FAM Dev'
2. Click on 'FOM DEV' application on the Select Application screen
3. Create a role assignment with a client # for FOM
4. Save the record
5. Navigate back to Select application on FAM
6. Click on 'FOM TEST' application 
7. Create the same Role assignment with the same client #

The screen returns an error message: _Duplicate record cannot be created_

8. Delete the same role assignment from FOM Dev application on FAM
9. Recreate the Record for FOM TEST application, FAM notifies that record has been successfully created

**Record is not displayed on the Manage Access screen**

10. Navigate back to the FOM Dev application on FAM Dev

**Record can be seen on the Manage Access Screen.**

**Expected behavior**
**user assignment should be unique across multiple environments**
**Recreated records should be created for the environment in which the record is being created **

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/1617614c-0837-4c1e-941d-d064b90c9825)

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/6764a709-b2c1-43f9-80c9-3e6153efe26b)

**Comment by basilv** [comment]
Nice find. We just need to fix logic (either db constraint or business rule) to check environment as well. But I'm confused why that wasn't already done - the application should be part of what's checked for duplicate, and the application is scoped to environment. Unless we are missing application from the check?

**Comment by ianliuwk1019** [comment]
Backend code fix and new tests are added into PR #520.

**Comment by ArogeG** [comment]
Thanks @ianliuwk1019 is this deployed to Dev yet?

**Comment by ianliuwk1019** [comment]
Yes it is currently deployed to dev as the pr is merged and closed, but I moved this ticket back for your review @ArogeG . Also FOM's thickline is fixed as well.
(logout - need to do it in FAM) is still in progress. So FOM test still has problem for logout.

**Comment by ArogeG** [comment]
Sounds good, thanks! It seems to be working as expected now. I will do some more test tomorrow.
![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/d09f2cf3-25fe-4909-a90d-cdd8e1c2e1f9)
