### ISSUE TITLE
FAM Cognito logout setting for FOM (TEST) does not work.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#519]
While testing on FOM on (TEST )environment, the logout has an error popup.
Suspect Cognito setting for logout url might be wrong (or if correct, then need to check FOM openshift deployment template for this settings.)

Note: FOM (TEST) environment is configured to use FAM (PROD) Cognito with `**fom_test**` environment.
Also, double check Terraform Cognito logout url setting for PROD as well.

**Comment by ianliuwk1019** [comment]
Interesting.....

Both (FOM Test, FAM PROD - fom_test) configurations are there, but it is a mismatch. The Cognito logout url fix was deployed last week.
On FOM Test - it is:
```
https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=https://fom-test.nrs.gov.bc.ca/admin/not-authorized?loggedout=true
```

But on FAM PROD (fom_test), it is:
```
https://logon.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=https://fom-test.nrs.gov.bc.ca/admin/not-authorized?loggedout=true
```

Checking on Terraform/Terragrunt configuration the settings seem to be fine (but looks to me on Cognito, **fom_test** is using terragrunt proudction setting):
This is terragrunt `test` setting:
```
  fam_logout_urls = [
    "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=https://fam-tst.nrs.gov.bc.ca",
    "https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=http://localhost:5173"
  ]
```

This is terragrunt `prod` setting:
```
  fam_logout_urls = [
    "https://logon7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?redirect_uri=https://fam.nrs.gov.bc.ca",
  ]
```

So, did we do it wrong or am I confused? And, does it mean, the terragrunt PROD deploy settings should have **"3"** set of "fam_logout_urls" urls for Cognito client(s): **fom_dev**, **fom_test**, **fom_prod**, instead of just "1" logout_url set.

@basilv @gormless87 @MCatherine1994

**Comment by MCatherine1994** [comment]
Oh Thanks @ianliuwk1019 that's a good catch!  So we need to rethink about this, maybe the logout url chain shouldn't be different based on fam environment, but should be different based on the client environment

For all FAM env:
    - FOM-DEV client: use Siteminder and Keycloak **DEV** logout url
    - FOM-TEST client: use Siteminder and Keycloak **TEST** logout url
    - FOM-PROD client: use Siteminder and Keycloak **PROD** logout url

Or we only use PROD for FAM Prod and client prod?

**Comment by ianliuwk1019** [comment]
From the current design of terraform code, it seems all 3 environments client specific settings (fom_dev, fom_test, fom_prod) needs to be in each FAM stage. @MCatherine1994.
