### ISSUE TITLE
Onboard with IDIR&BCEID Lookup Tool

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#528]
**Describe the task**
Contact IDIM team for web service account setup

**Acceptance Criteria**
- [ ] get account setup
- [ ]  review webservices lookup usage
- [ ]  test use of the web service(s) - curl or postman

**Additional context**
web service document: [https://app.zenhub.com/files/486378283/6f648b83-2bb3-41f9-8f3d-ad633e96ea15/download](https://app.zenhub.com/files/486378283/6f648b83-2bb3-41f9-8f3d-ad633e96ea15/download)

**Comment by ArogeG** [comment]
Began conversations with IDIM, see details of required steps for the onboarding. I have now reached out to Chris.

You will need to work with one of your designated Ministry BCeID Client Managers to get up an rolling with successful BCeID Web Service calls - ( Chris Smith is Primary ) ( Eric Valikoski is Secondary ).

•	Step 1 > Identify which non-production OSD entry you will use to begin your non-production BCeID Web Service call development work & testing in:
o	https://www.development.bceid.ca/os/?2523 [ We recommend you start in DEV and after refinement & testing, promotion to TEST prior to implementation in PROD ]
o	https://www.test.bceid.ca/os/?9441 
	Please notify IDIM.Consulting@gov.bc.ca which OSD entry in which BCeID environment you will commence your BCeID Web Service call development work in.

•	Step 2 > One of your BCeID Client Managers will need to share with you the OSID # associated with your target OSD entry for your BCeID Web Service call development work.

•	Step 3 > One of your BCeID Client Managers will need to register an IDIR Service Account in the correct BCeID Client profile in the correct BCeID environment and associate that IDIR Service Account with the correct OSD entry in that BCeID environment.
o	Best Practice:  Use a proper ‘IDIR Service Account’ = an IDIR account with a non-expiring password.
o	Best Practice:  Don’t re-use ‘IDIR Service Accounts’ = 1 IDIR Service Account per OSD entry per BCeID environment = use different Service Accounts in different BCeID environments = [ 1 IDIR Service Account : OSD entry : BCeID environment ]

In the Client signed Portal Service Agreement for FAM, we identified some ‘future state’ BCeID Web Service based use cases… Do you anticipate or expect any required modifications to those ‘paper’ documented use cases?

•	If not, once you identify which non-production FAM OSD entries you will be using for your initial BCeID Web Service call development work, Rob Lowe or I can pre-populate those BCeID Web Service based data sharing scenarios | information sharing rules in the target OSD entry almost immediately.

**Comment by ArogeG** [comment]
Created request for service account: https://apps.nrs.gov.bc.ca/int/jira/browse/SD-66872

**Comment by ArogeG** [comment]
Step 1 has been completed,

 At the moment, there are no additional changes to the use case documented in the service agreement. As requested in step 1 , we will begin our initial BCeID Web Service call development work on our Dev environment. Here is the FAM Dev OSD # FA10-D20F-0F7F-45B8 for FAM dev environment.

Thanks, 
Gbola.

**Comment by ArogeG** [comment]
MOF_FAM setup with BCeID Dev, FAM we can now test the webservice config

**Comment by ArogeG** [comment]
Service account is required for TEST and PROD. 
Service account would need to be setup for FAM TEST and PROD OSD. 
Please reach out to Chris Smith once ready.
