### ISSUE TITLE
Publish FAM API code to FAM repo

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#53]
Want to have a discussion about the following before i merge my code:
* how to structure directories in the repository
* branching
* how / when do we start merging with main

Currently code only exists locally, want to merge with:
https://github.com/bcgov/nr-forests-access-management

**Comment by ConradBoydElliottGustafson** [comment]
@franTarkenton @gormless87  I think we've talked through these issues. Code is merged into the "backend" directory for now and we have tickets to integrate it into the build/deploy pipeline.

Branching strategy is currently the old standby of dev->test->prod. Nothing has gone to test or prod yet. Merging to main will happen when we are ready to go to prod (ish)!

I think we can call this sucker done?
