### ISSUE TITLE
SPIKE: Explore the option of not using RDS Proxy to Reduce FAM  Cost. 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#541]
Possible options:
- Delete proxy
- Remove Deployment
- Deleting Dev & TEST does not seem like a viable option for cost & efficiency of FAM. 

Acceptance Criteria:
[ ] - add GHA on schedule to implement existing scripts
[ ] - clarify options on splitting Terraform scripts
[ ] - options to manage AWS costs, particularly RDS proxy
[ ] - Provide Pros & Cons of explored options.

**Comment by ConradBoydElliottGustafson** [comment]
Considered all the available options and wrote up a SPIKE option paper here: https://github.com/bcgov/nr-forests-access-management/wiki/SPIKE:-Connection-Pooling-and-RDS-Proxy-Costs

**Comment by gormless87** [comment]
Nice write up.
