### ISSUE TITLE
Request for a new Forest Client API endpoint

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#543]
**Describe the task**
- We want to request a general search api, which will allow us to provide either a name (client name) or a forest client number, and the api will return all the possible result by a wildcard search.
- For the return data, we want to get description for the client type code and client status code

For example:
In an input box, we type “CanFor”, we can get all the forest client that has client name includes “CanFor”
And if we type “1234”, we can get all the forest client that has client number includes “1234”

**Acceptance Criteria**
- [x] Send to Team Alliance

**Comment by gormless87** [comment]
@MCatherine1994 - can I close this issue?

**Comment by MCatherine1994** [comment]
yeah we can close this one, but I just don't think team Alliance started this work, it's in their backlog maybe
