### ISSUE TITLE
Defect when provisioning access to a deleted role assignment

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#552]
**Describe the bug**

**To Reproduce**
1. Go to 'FAM TEST'
2. Select FOM application
3. Click on 'Grant Access screen'
4. Create a new user (BCeID user) with FOM submitter role and Forest client (00082820)
5. Once created, delete role assignment 
6. create user again by repeating step 3-6

Actual Result: Application Error has Occurred 

Expected Result: User role assignment has been created successfully

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/e7e9b762-af79-43fb-86bc-4672beb504cc)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MCatherine1994** [comment]
[https://app.zenhub.com/files/486378283/3f084673-3e02-49ea-bebb-653a49a2dcfd/download](https://app.zenhub.com/files/486378283/3f084673-3e02-49ea-bebb-653a49a2dcfd/download)

**Comment by ianliuwk1019** [comment]
Added prod log from Basil.
[https://app.zenhub.com/files/486378283/81d5ecb1-790e-4473-8fbc-144343c120d2/download](https://app.zenhub.com/files/486378283/81d5ecb1-790e-4473-8fbc-144343c120d2/download)

**Comment by ianliuwk1019** [comment]
From the log and prod data:
Backend has a check on if user exists, based on '**user_type_code**' (B or I) and '**user_name**' (**ilike** - case insensitive), before creating a user.
For this case from production database query, it shows 2 fam_user records ("**DVALK**" and "**DValk**"). So, backend returns error when the check found more than 1 user with **"the same" name** and type.
	
```	
famdb=> select * from fam_user where UPPER(user_name)='DVALK';
 user_id |            user_guid             |                          cognito_user_id                          | user_name |                   create_user                   |
 create_date          |  update_user  |      update_date       | user_type_code
---------+----------------------------------+-------------------------------------------------------------------+-----------+-------------------------------------------------+---------
----------------------+---------------+------------------------+----------------
     552 | FDFEE614672C4B56A3E168CD91C790F7 | prod-bceidbusiness_fdfee614672c4b56a3e168cd91c790f7@bceidbusiness | DValk     | fam_proxy_api                                   | 2023-04-
12 00:00:00+00        | fam_proxy_api | 2023-04-12 00:00:00+00 | B
     551 |                                  |                                                                   | DVALK     | prod-idir_7f27542b4f1a45478f90b967ff34d74b@idir | 2023-04-
12 18:07:59.618679+00 |               |                        | B
(2 rows)
```

* Based on prod data:
	**First** fam_user record "**DVALK**" (user_id=**551**) looks like is created by Julius using FAM frontend to create user/role assignment.
	**Second** fam_user record "**DValk**" (user_id=**552**) likely is from the user login to FOM (and based on prod data, it should be user's first time and no role returned for this login user to FOM)
	
* How the auth-lambda function created **second** fam_user when there exists already first fam_user (user_id=**551**):
   Possibly, the auth-lambda function is based on unique constraint: `CONSTRAINT fam_usr_uk UNIQUE (user_type_code, user_name)`
   and this isn't case insensitive. The user with the same user_type could have same name with different case ("**DVALK**", "**DValk**").
   In this case, auth-lambda could not find and update first user.
   ```
	    INSERT INTO app_fam.fam_user
            ...
            ...
            ON CONFLICT ON CONSTRAINT fam_usr_uk DO
            UPDATE SET user_guid = {user_guid},  cognito_user_id = {cognito_user_id};
   ```

**Comment by MCatherine1994** [comment]
Just add some notes:
- When a new user has been created through the FAM UI, the username depends on whatever the user types in, we don't make changes
- When a new user has been created through the first time login to the application integrated with FAM, the username will be the "custom:idp_username" from IDP

**Comment by basilv** [comment]
I don't understand these comments - the user name must be identical in both scenarios (or at least matched to the same user record), or FAM won't work as intended.
Scenario 1: User John Smith logs into FAM. Their IDIR is supplied as JSmith. A user record is created (if it doesn't already exist), or is updated, matching on the user id (and domain).
Scenario 2: An admin grants access to user John Smith. They likely type JSMITH or jsmith for the user id. A user record is created (if it doesn't already exist), and an access assignment is created linking to the user identified by the user id (and domain)

FAM must ensure that the user record in scenario 1 and scenario 2 are the same, irrespective of the order they occur in.

**Comment by MCatherine1994** [comment]
Yes, so when create user through FAM UI, we call this method to check if there is an existing user, think it's case insensitive now
![Screen Shot 2023-04-18 at 4.55.56 PM.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/e646105e-20b3-4391-8554-0a12346df93e)

But when the user has been created through the auth function, it's checking the constraint fam_usr_uk, which is case sensitive
```
ALTER TABLE app_fam.fam_user ADD CONSTRAINT fam_usr_uk UNIQUE (user_type_code, user_name);
````

**Comment by MCatherine1994** [comment]
I just document how we fixed the dev deployment here, we could move it to other place later:

To remove the KMS key, we need to use the terragrunt cli:
- download required cli tools
   - terraform: https://developer.hashicorp.com/terraform/downloads
   - terragrunt: https://terragrunt.gruntwork.io/docs/getting-started/install/
- login to terraform cloud, the token can be found through [here](https://ca-central-1.console.aws.amazon.com/systems-manager/parameters/octk/tfc/team-token/description?region=ca-central-1&tab=Table#list_parameter_filters=Name:Contains:%2Foctk%2Ftfc%2Fteam-token)
   ![Screen Shot 2023-04-19 at 3.14.33 PM.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/e956a8be-9226-4f37-9581-1180db6e5922)  
- Go to our repository directory, for FAM DEV environment, go to the terragrunt file directory for our FAM DEV, which is at `terraform/dev/terragrunt.hcl`
- Set up the environment variable `export tfc_workspace=sfha4x-dev`, 'sfha4x-dev' is our license plate for dev
- Run `terragrunt init` and `terragrunt state list`  to see all the state
- And then run `terragrunt rm [kms_key_name]`

But Basil and I both have problems run the terragrunt command, it hangs there, so we got the help from Warren Uniewski, he helped us remove that. So the key is still in the AWS scheduled for deletion, but terraform will ignore it

**Comment by MCatherine1994** [comment]
In order to fix this problem, 
- we first fixed the FOM-DEV deployment, reference my last comment
- and then we create a branch for the hotfix, which includes
  - update the constraint that the auth function is using, update that to support case insensitive when check if the user exists or not
  - add flyway script to find and remove duplicate user records
  - update local cognito env variables, so tests can run in pipeline
  - merged a specific commit that we must have, which is [Conrad's change for RDS postgres verison](e76ab9d39c5809feeedc5a1259e8d3ec8161037e)
  - merged a specific commit that we must have, which is [FOM demo callback urls](ff6f416e4ecd1d218c386ee8d438313d0ae329fe)
- and then we fix the hotfix release please pipeline, update the target branch to be "hotfix", so when we merge fix to the hotfix branch, it can trigger the hotfix release

**Comment by ArogeG** [comment]
Thanks all for working urgently on this, much appreciated.
