### ISSUE TITLE
FAM-API - Define Role End Points

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#56]
* POST Role - Add new role to the api / database
* GET Role - List existing roles in the database

**Comment by ianliuwk1019** [comment]
I resolved my local issue on running backend api.
I don't seem to have problem running existing endpoints Keven created, at least can run these with success (currently empty data returned): 
* GET: /api/vi/fam_applications
* GET: /api/vi/fam_users

And was able to fix one simple typo and have GET: /api/vi/fam_roles working.

Was having some confusion for how roles work and being modeled.
Really appreciate Richard spent time explaining how "fam_roles" will work for FAM to resolve my confusion.
Thank you very much @rpardofigueroa !
I will continue on endponit for roles.

**Comment by ianliuwk1019** [comment]
For the third description for this task: "**Define fixture to load existing Roles (From FOM) to the FAM table**", 
It seems to me this is related to the data, **should we move to a separate task**?

Question for that third task. Do we intend to load the FOM forest client, application and FOM roles data using **migration** script?
On the second thought, maybe not from migration, but by adding these data (on boarding these application and client data) through currently in-develop **FAM API endpoints** (since FAM is meant to be generic, right)?
@gormless87 @franTarkenton @basilv @explorertolu

**Comment by ArogeG** [comment]
Merge to Dev instead of Main for FAM

**Comment by ianliuwk1019** [comment]
After talking to Kevin, this point **"Define fixture to load existing Roles (From FOM) to the FAM table."** is moved to a new ticket.
https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-forest-client-api/30

**Comment by ianliuwk1019** [comment]
I was able to follow Kevin's Alembic readme to create a new incremental migration script to fix schema for column nullable issue at local database (so no ER Studio fix first). The first simple role POST endpoint is working for me now.

One question:
I guess we will polish our endpoints later, so my question is for later ticket not this one. 
The request body for POST endpoints, like "create application", "create user", "create role", have a parameter required: "**create_user**". I haven't got the architecture that clear in mind yet but this seems to be strange to me. When the endpoint is being called, would this 'create_user' be from some token from Keycloak or ASW Cognito(so it should be no need to enter this)?

@franTarkenton @basilv @ArogeG

**Comment by basilv** [comment]
Yes, I discussed this with Kevin a while back - I never include audit columns in an API call as the whole point is to system-generate that information to avoid having an attacker be able to fake it. Now if this isn't an audit column, but has a business meaning - e.g. I'm submitting a request to create an account for another user, that's different.

**Comment by ianliuwk1019** [comment]
It's a reference.
Our ORM mapping for table primary key (sequence, auto-increment) is working for normal dev environment but the test environment (which spin up quick database) isn't working (using sqlLite from the testing framework).
The finding is that, our ORM maps the primary key to BigInteger(not sure why needing such big datattype) and sqlLite does not recognize BigInteger and SqlAlchemy has a trick for that by using: "**BigInteger().with_variant(Integer, "sqlite")**" for the primary key column.

**Comment by basilv** [comment]
If you have more than about 2 billion rows, Integer is too small (assuming 32 bit integer). Won't be the case for FAM, but I've worked on a couple of systems were that was a legitimate concern.
