### ISSUE TITLE
Application error when only has access to one application

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#560]
**Describe the task**
When the user only has access to one application, we will skip the "Select Application" page, and show the "Manage Access" page directly, but there will be an error message show on the screen
![image.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/8f1f7c5e-b635-44be-a8e1-b0ee7fa57cb2)
![Screen Shot 2023-04-21 at 9.32.24 AM.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/21f3bce2-be7d-479b-8422-fff1ce574875)

**Acceptance Criteria**
- [ ] No error show on the screen, when the user only has access to one application

**Comment by ArogeG** [comment]
The error seems to come-up when the token is being refreshed.

**Comment by MCatherine1994** [comment]
Found another case that could trigger this error:

When we are on the "Manage Access" page, and then we refresh the page, this error will shows again.

It's because refresh page will reset our local "selectedApplication" variable, and then triggers a redirect back to the select application page.
