### ISSUE TITLE
Develop a plan for routine and emergency patches and upgrade on FAM

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#563]
**Describe the task**
Develop a plan for routine and emergency patches and upgrade on FAM

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ConradBoydElliottGustafson** [comment]
I think the renovate strategy is fairly stable at this point. This ticket might not be necessary.

**Comment by gormless87** [comment]
Superseded by #296
