### ISSUE TITLE
Spike: Determine options for generating Access logs/Event logs 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#566]
Quick spike to determine if access logs can be generated from Cognito and event logs from RDS/ any other AWS service

There might be opportunities to retrieve access logs from AWS Cognito. These logs might be available in Amazon CloudWatch Logs, and can be retrieved using the CloudWatch Logs API or the CloudWatch Logs console but needs to be configured.

**Comment by basilv** [comment]
AWS RDS has audit logging functions. In particular see https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html, and the statement "In addition to the standard PostgreSQL logs discussed in this topic, RDS for PostgreSQL also supports the PostgreSQL Audit extension (pgAudit). Most regulated industries and government agencies need to maintain an audit log or audit trail of changes made to data to comply with legal requirements. For information about installing and using pgAudit, see Using pgAudit to log database activity." is relevant for auditing activity of support staff, and we likely eventually want to consider it, but this doesn't identify activity specific to individual FAM users - we'll see the database operations issued by the fam_api system account instead.

**Comment by basilv** [comment]
AWS RDS has audit logging functions. In particular see https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html, and the statement "In addition to the standard PostgreSQL logs discussed in this topic, RDS for PostgreSQL also supports the PostgreSQL Audit extension (pgAudit). Most regulated industries and government agencies need to maintain an audit log or audit trail of changes made to data to comply with legal requirements. For information about installing and using pgAudit, see Using pgAudit to log database activity." is relevant for auditing activity of support staff, and we likely eventually want to consider it, but this doesn't identify activity specific to individual FAM users - we'll see the database operations issued by the fam_api system account instead.

**Comment by basilv** [comment]
So in conclusion, AWS has native capabilities to identify activities performed by the dev/support team members, but this won't allow auditing of activity by specific FAM end users. For that we'd have to provide some audit logging capability within FAM itself.
