### ISSUE TITLE
Search for Forest Client by Name

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#569]
**As a** *FAM Application Administration* **I want** *to search for a forest client by name * **So That** *I can provision access for users in an organization*

**Additional Context**
- On the grant access screen, allow users search for clients by both forest client name & number
- enter text here

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by OlgaLiber2** [comment]
not a priority. Closing this ticket
