### ISSUE TITLE
Add Renovate to FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#574]
**Acceptance Criteria**

- Have RenovateBot running against FAM github repo
- Auto-create dependency dashboard issue
- Detect dependency issues with frontend (node), backend (python), and dockerfiles

**Comment by basilv** [comment]
Will need @DerekRoberts help with this.

**Comment by DerekRoberts** [comment]
@basilv Thanks for the include!  I (probably) have everything needed to set up, but just needed the okay from you team.  :)

**Comment by DerekRoberts** [comment]
@basilv @ianliuwk1019 Please add the user/bot bcgov-renovate to your repo with write access.  Then we can start the PR generation.

**Comment by basilv** [comment]
Waiting for depedency dashboard issue to be created, then will review.

**Comment by ianliuwk1019** [comment]
Thank you @DerekRoberts for adding this!
Does it have capability for setting up "Python" backend detection or is currently only for node packages?
Thank you.

**Comment by DerekRoberts** [comment]
@ianliuwk1019 Glad to!  It does support Python, but I'm not strong in that language.  Any chance you'd like to help?

**Comment by DerekRoberts** [comment]
Dependency Dashboard waiting and ready!  :)
https://github.com/bcgov/nr-forests-access-management/issues/582

**Comment by ianliuwk1019** [comment]
@DerekRoberts , Oh~ I don't know what magic you did so quickly, I see it does have Python:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/4a517d21-3ca0-4cd9-89ae-57d3809af2da)
Thank you so much, Kevin will be very happy.

**Comment by basilv** [comment]
Dashboard looks good, just waiting to see auto-created PRs.

**Comment by basilv** [comment]
As per Derek, PRs are typically created Mondays or after 3 days.
