### ISSUE TITLE
Implement PubCode for FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#575]
**Describe the task**
Add Pubcode to FAM repo

**Acceptance Criteria**
- [ ] All of the mandatory Sections/Fields on the data entry form are populated correctly

**Additional context**
- JSON schema for bcgovpubcode.yml: bcgovpubcode.yml is a metadata standard for repositories containing software developed or acquired by the Public Administration, aimed at making them easily discoverable and thus reusable by other entities.
- Form to enter metadata: https://pubcode.apps.silver.devops.gov.bc.ca/form
- Source repo (see readme) : https://github.com/bcgov/pubcode

**Comment by gormless87** [comment]
[https://app.zenhub.com/files/486378283/7e69a28c-edb1-4928-b03e-88591340202f/download](https://app.zenhub.com/files/486378283/7e69a28c-edb1-4928-b03e-88591340202f/download)


Above is yml, changed extension so Zenhub would allow upload

**Comment by basilv** [comment]
@gormless87 Here's what I specified before I saw your above comment. Need to clarify the ministry, data custodian (I put you :), and description primarily.


BCGov Public Code

---
data_management_roles:
  data_custodian: Pete Tollestrup
  product_owner: Pete Tollestrup
product_external_dependencies:
  identity_authorization:
    - IDIR
    - Business-BceId
    - BC-Services-Card
    - AWS-Cognito
  notification_standard: []
product_information:
  api_specifications: []
  business_capabilities_standard:
    - Authorization Management
  ministry:
    - Forests
  product_acronym: FAM
  product_description: >-
    The Forests Authorization Management product (FAM) will meet the needs of
    the sector to allow business users to define and assign groups and roles.
    FAM will integrate with an OIDC service so that authorization context will
    be securely and transparently included in the context of any authentication
    process.
  product_name: Forest Access Management
  product_status: active
  product_urls:
    - https://fam.nrs.gov.bc.ca/
  program_area: TODO
product_technology_information:
  backend_frameworks: []
  backend_languages_version:
    - name: Python
      version: '3.8'
  ci_cd_tools:
    - GitHub-Actions
    - Terraform
    - Terragrunt
  data_storage_platforms:
    - Postgresql
  frontend_frameworks:
    - name: Vue
      version: '3'
  frontend_languages:
    - name: TypeScript
      version: '4.7'
  hosting_platforms:
    - Amazon-Web-Services
version: 1

**Comment by gormless87** [comment]
Ministry is WLRS (Ministry of Water, Land and Resource Stewardship)
Description in your comment above is OK as it matches IRS

Still spongy on who the data custodian is.
