### ISSUE TITLE
Onboard Silva to Fam for dev environment

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#578]
**Describe the task**
The Result application will be modernized to a new application Silva. And they're looking forward to onboard with FAM for just dev environment to see how FAM works. They just want 2 test roles for now (read-only and write-only). They will submit the onboarding questionnaire to us.

**Acceptance Criteria**
- [ ] Onboard Silva dev in FAM -- they just want IDIR to start with

Additional Context
- [ ] CHEFS form has been submitted

**Comment by MCatherine1994** [comment]
Our onboarding questionnaire doesn't allow enter localhost url, need to confirm with them the dev redirect url they provide is actually what they use.

**Comment by basilv** [comment]
Talk to Jaskirat Singh Grewal for details. Probably start with just IDIR.
