### ISSUE TITLE
Review FAM onboarding form

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#579]
**Describe the task**
Need a review about the FAM onboarding form to see if all the questions make sense to our user. Also notice that the URL validator the CHEFS form is using that doesn't support localhost, so we might want to remove the valuation for our redirect url fields.

**Acceptance Criteria**
- [x] All questions make sense to users
- [x] Validation rules make sense
- [ ] Test the form

**Additional context**
- Note: formIO (CHEFS is using it) url validator doesn't accept localhost (correct spelling, with http or https) as a valid URL. Needs a domain suffix.

**Comment by MCatherine1994** [comment]
- Change the url component fields to be regular text fields
- Make the role fields to be not mandatory

**Comment by gormless87** [comment]
Thanks Catherine, looks good. We will continue to revise the form based on Fingerprint needs and user feedback as it comes in.
