### ISSUE TITLE
FAM-API - Add Application / Client

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#58]
In order to be able to get to select an application (Post MVP), an application type needs to exist in the FAM api.

Two options to add the a application / client:
* Define end point
* Define a migration fixture

Relates to:
https://github.com/bcgov/nr-forests-access-management/issues/20

AC: 
-tests included

**Comment by MCatherine1994** [comment]
Close it for now, need to discuss the process when adding a new application
