### ISSUE TITLE
SPIKE: Frontend end-to-end testing

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#580]
**Describe the task**
A spike of the end-to-end testing method for our frontend, maybe Cypress? Like how to do configuration, how to use it

**Acceptance Criteria**
- [ ] Got the configuration for the end-to-end testing
- [ ] Document how to use it

**Comment by NickSaglioni** [comment]
### Cypress Spike

**Advantages of Cypress**
* Cypress framework captures snapshots at the time of test execution that allows QAs or developers to hover over a specific command in the Command Log to see exactly what happened at any particular step;
* There is no need to add explicit or implicit wait commands in test scripts, Cypress waits automatically for commands and assertions;
* Developers or QAs can use Spies, Stubs, and Clocks to verify and control the behavior of server responses, functions, or timers;
* The automatic scrolling operation ensures that an element is in view before performing any action (for example Clicking on a button);
* Cypress currently provides support for Chrome, Firefox and Edge browsers;
* As the programmer writes commands, Cypress executes them in real-time, providing visual feedback as they run;
* Excellent documentation and community support.

**Trade-offs**
* Cypress is not a general purpose automation tool;
* Cypress commands run inside of a browser - which can be slower than other testing frameworks;
* There will never be support for multiple browser tabs;
* You cannot use Cypress to drive two browsers at the same time;
* Each test is bound to a single superdomain. Cross-origin navigation inside tests can be enabled by using the cy.origin command;
* Cypress doesn’t provide support for browsers like Safari and IE at the moment;
* Limited support for iFrames;

**Cypress Vs Vitest**
Vitest is best used for headless testing. Cypress has the benefit of having browser-based test runner using real browser APIs. There will be a lot of potential issues or bugs that Cypress can cover that Vitest will not be able to.

Cypress offers more visual oriented test development at the cost of speed based on the real browser engine so it is closest it can be possibly be to the user-environment. The confidence in knowing its the closest to the user-environment is the biggest benefit of Cypress.

**Installing Cypress**

`npm install cypress  --save-dev`

**Running Cypress**

`npx cypress open`

**Adding npm Scripts**

Add the following line to the scripts section of the **package.json** file:

```
{
  "scripts": {
    "cypress:open": "cypress open"
  }
}

```

Now cypress can be invoked by  the command below from the project frontend folder:

`npm run cypress:open`


**VSCode errors with TypeScript Typings for cy.mount() Commands**
When working in TypeScript, it will be needed to add custom typings for your commands to get code completion and to avoid any TypeScript errors.
The typings need to be in a location that any code can access, therefore, it is recommend creating a cypress.d.ts file in the root directory, and use this example as a starting point for customizing your own command:

```
import { mount } from 'cypress/vue'

type MountParams = Parameters<typeof mount>
type OptionsParam = MountParams[1]

declare global {
  namespace Cypress {
    interface Chainable {
      mount: typeof mount
    }
  }
}
```

It could also be needed to manually include the **cypress.d.ts** file in all **tsconfig.json** files:

`"include": ["./src", "cypress.d.ts"]`

**Comment by NickSaglioni** [comment]
I have created a branch for this spike with Cypress installed and configured and a test example for the Landing Page:

https://github.com/bcgov/nr-forests-access-management/tree/feat/580-spike-frontend-e2e-testing

**Comment by NickSaglioni** [comment]
### Useful links

https://docs.cypress.io/guides/getting-started/installing-cypress
https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test
https://docs.cypress.io/guides/component-testing/overview
https://docs.cypress.io/guides/continuous-integration/github-actions
