### ISSUE TITLE
Update postgres test container to start docker just with postgres and flyway service

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#584]
**Describe the task**
Test container now supports start the docker container with specific service: https://github.com/testcontainers/testcontainers-python/issues/315. Update our Postgres testing to start the docker container based on the docker compose file, but just with postgres and flyway service, ignore the api service. Make the change in the file `server/backend/testspg/conftest.py`

**Acceptance Criteria**
- [ ] Postgres testing container only start with the Postgres and flyway service

**Comment by MCatherine1994** [comment]
refs: #403, #405

**Comment by MCatherine1994** [comment]
Looks like they added that feature, but haven't release it yet, https://github.com/testcontainers/testcontainers-python/pull/337

**Comment by ConradBoydElliottGustafson** [comment]
This was already done by somebody. Ian I think. We have a new docker-compose file that omits the API container.
