### ISSUE TITLE
Renovate dashboard - backend

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#592]
**Describe the task**
Address Renovate dependency dashboard - backend

**Acceptance Criteria**
- [ ] identify which items are related to or can be bundled with backend issues
- [ ] confirm reported package is actually being used.
- [ ] clear up dashboard items for backend

**Additional context**
- More testing exists for backend, will address frontend in separate ticket

**Comment by DerekRoberts** [comment]
@gormless87 @ConradBoydElliottGustafson Please don't batch Dependabot or Renovate dependency PRs unless necessary.  It can block future updates and defeats the purpose of keeping updates as small as possible.
