### ISSUE TITLE
Renovate dashboard - frontend

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#593]
**Describe the task**
Address Renovate dependency dashboard - frontend

**Acceptance Criteria**
- [ ] identify which items are related to frontend issues
- [ ] clear up dashboard items for frontend
- [ ]  confirm reported package is actually being used.

**Additional context**
- More testing exists for backend, will address frontend in separate ticket
- For "@types/node to v18" upgrade, please try remove this dependency from package.json first, if success (build and try frontend pages), then no need to merge renovate pr for this one.

**Comment by ianliuwk1019** [comment]
Frontend 'Renovate' PRs **verified and merged**:
* fix(deps): update dependency aws-amplify to v5 #600
* chore(deps): update dependency vue-tsc to v1 #597
* chore(deps): update vite to v4 (major) #590
* chore(deps): update dependency jsdom to v22 #589

Waiting to be merged:
* chore(deps): update dependency yup to v1 #598:
   - has considerable fix for the update, not sure if Basil is interested on review, but can be merged.
* chore(deps): update dependency @types/node to v18 #585:
   - This one, we can remove (not like renovate bot update dependency version). I removed and verified locally. However, just like to discuss how to do this one: create a new pr to do it or remove dependency in renovate created pr and change title (not sure if it is appropriate).

**Comment by ianliuwk1019** [comment]
Frontend 'Renovate' PRs **verified and merged**:
* fix(deps): update dependency aws-amplify to v5 #600
* chore(deps): update dependency vue-tsc to v1 #597
* chore(deps): update vite to v4 (major) #590
* chore(deps): update dependency jsdom to v22 #589

Waiting to be merged:
* chore(deps): update dependency yup to v1 #598:
   - has considerable fix for the update, not sure if Basil is interested on review, but can be merged.
* chore(deps): update dependency @types/node to v18 #585:
   - This one, we can remove (not like renovate bot update dependency version). I removed and verified locally. However, just like to discuss how to do this one: create a new pr to do it or remove dependency in renovate created pr and change title (not sure if it is appropriate).
