### ISSUE TITLE
Cleanup alembic remnants from backend code

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#594]
**Describe the task**
Follow up from #474 - remove unused code

**Acceptance Criteria**
- [ ] unused code removed
- [ ] app still works
- [ ] tests still run
- [ ] pipeline updates to remove sql lite content
- [ ] documentation adjusted accordingly (readme)

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
This ticket is mostly completed at PR#614. Pipeline is running good as well.
The one thing that's not directly "**alembic**" related but indirectly "**sqllite**" related is the "model.py" for Python ORM.
This I feel should be separate into a new ticket itself as a direct implementation ticket follows from #474.
The ORM "model.py" itself probably contains just few tweaks from the past specific for **"sqlite" testing**. 
We can generate **a new ORM "model"** to use, but in new ticket, it will mostly be focusing on detail verification at the model: our test pipeline still runs and frontend all business functions are still working (hitting as many endpoints as we can), login auth and its returned roles still correct etc... as a new complete model generated from first try of "**sqlacodegen**" tool could potentially missed something and hidden (such as mentioned in ticket #474 from Catherine's investigation). 
@gormless87

**Comment by gormless87** [comment]
@ianliuwk1019 - I noticed this issue:

Update postgres test container to start docker just with postgres and flyway service#584

IT seems you may have addressed it with  PR#614

**Comment by ianliuwk1019** [comment]
Add #631 to separately dealing with generating new models for backend from sqlacodegen tool.
