### ISSUE TITLE
Data model for FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#6]

**Comment by ConradBoydElliottGustafson** [comment]
I will work with @rparfig on Friday to define a data model. 

Tentative AC:

- Logical data model in ER studio?
- Physical data model in ER studio? (targeting PostgreSQL)
- Model tracked in github on this repo perhaps?

**Comment by ConradBoydElliottGustafson** [comment]
@gormless87 FYI
@rparfig and I have been collaborating on this. Next step is to get it into the physical and then put a diagram and a link to ER studio on the FAM wiki.
Then we plan to generate DDL and put it into the FAM repo. Success!
