### ISSUE TITLE
FAM - API - Figure out Data Migrations Flow

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-forests-access-management#60]
Current situation:
* Data model defined in ER Studio
* ER studio exports SQL
* using [sqlcodegen](https://pypi.org/project/sqlacodegen/) to slurp up database defs to api model
* using Alembic to export SQL associated with models
* flyway consumes SQL from previous step and creates a migration
* migration run

Have had some discussions about this which is how we arrived at rough flow above.

Objectives:
* for local dev easy way to change data model
* Clearly defined process for how changes to datamodel made during feature development should take place
* Define automated way to update the api model when changes are made using flyway.

Current Challenges:
* no flow defined for how we keep the datamodel in ER - studio up to date. Does this matter?  What is the purpose of having the datamodel in ER Studio?  ... is there another way to accomplish this.

Relates to: 
https://github.com/bcgov/nr-forests-access-management/issues/20

**Comment by gormless87** [comment]
Need to formalize the business Req's around E/R Studio and the BC Data catalog - source of truth, (automated) synchronization with dev team changes

**Comment by ConradBoydElliottGustafson** [comment]
We have chosen to have a "dev-first" approach (generating sql scripts from Alembic/SqlAlchemy) and backporting to ER Studio. Requires some manual process to keep the ER Studio data model up to date.

Alternatively, if we make major changes in ER studio, it's possible to generate change scripts and then re-generate the Alembic files from the new DB. Probably more finicky.
