### ISSUE TITLE
Onboard Team members to FAM API

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-forests-access-management#61]
Kevin to onboard Tolu to the FAM API so we can expand the team's capacity to work on FAM related issues.

**Comment by franTarkenton** [comment]
for requirements for this session / development:
* WSL
* python 3.8
* docker and docker-compose
* podman (nice to have, my preference)
* vscode

Ideally before session try to setup a venv for development:
https://github.com/bcgov/nr-forests-access-management/blob/dev/backend/readme.md

**Comment by ConradBoydElliottGustafson** [comment]
@gormless87 I think we did this? Need some work to keep porting Kevin's code from the /backend directory over to the skeleton that @explorertolu built in the /server directory. I think "onboard" can be called done!
