### ISSUE TITLE
OpenShift Project setup

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#621]
**Describe the task**
Implement an OpenShift project and supporting resources for the bceid-proxy

**Acceptance Criteria**
- [x] delete everything except the api
- [x] deploy default api and be able to call it from the internet (OpenShift routing works, basically hello world)
- [x] DEV/TEST/PROD deployed (PROD will have fake creds)
- [x] deployment management  -separate git repo setup
- [x] change enablement --pipeline works

**Additional context**
- https://github.com/bcgov/quickstart-openshift
- Proposed name for github repo: 'bcgov/nr-fam-lookup-proxy'. We decided to use 'bcgov/nr-fam-idim-lookup-proxy'.

**Comment by DerekRoberts** [comment]
SonarCloud project requested.
https://github.com/BCDevOps/devops-requests/issues/1516

**Comment by ianliuwk1019** [comment]
Thanks to Derek! We have initial repo here: https://github.com/bcgov/nr-fam-idim-lookup-proxy

**Comment by ianliuwk1019** [comment]
The new pipeline for PR #6: https://github.com/bcgov/nr-fam-idim-lookup-proxy/actions/runs/5314741054 run successfully.
Hello-World API deployed:
Test: https://nr-fam-idim-lookup-proxy-test-backend.apps.silver.devops.gov.bc.ca/api
Prod: https://nr-fam-idim-lookup-proxy-prod-backend.apps.silver.devops.gov.bc.ca/api

Interestingly, the pipeline go straight from TEST to PROD and no gate for approval. Not sure if we want a gated prod approval pipeline.

**Comment by DerekRoberts** [comment]
@ianliuwk1019 That's a crutch.  Ideally we'll go straight to PROD every time with as many small changes as possible, which is beneficial for stability and (inevitable) troubleshooting.  What we should be doing is to add checks between TEST and PROD.
