### ISSUE TITLE
SPIKE: RDS proxy usage refinement

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#685]
**Describe the task**
All access to FAM uses the same proxy user. RDS proxy is the largest cost item for our AWS infrastructure. Can we configure a single RDS proxy to allow segregation? 

**Acceptance Criteria**
- [x] Documentation review to make sure we understand the potential
- [x] Make sure we can do it with Terraform

**Comment by gormless87** [comment]
@ConradBoydElliottGustafson -ticket for RDS spike

**Comment by ConradBoydElliottGustafson** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy.limitations makes it clear that you can have up to 200 different secrets in a single proxy. Making sure Terraform supports this.

**Comment by ConradBoydElliottGustafson** [comment]
It was somewhat confusing, but it looks like you can do this in Terraform. Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17713

**Comment by gormless87** [comment]
woot-woot!

Each proxy can have up to 200 associated Secrets Manager secrets. Thus, each proxy can connect to with up to 200 different user accounts at any given time.
