### ISSUE TITLE
Create wiki entry to describe our testing approach

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#691]
**Describe the task**
First draft to capture discussions on how we will implement testing.

**Acceptance Criteria**
- [ ] wiki article and one round of peer review
- [ ] 

**Additional context**
- 3 levels testing concept; team agreement -->pragmatic approach vs perfection; evolves over time

**Comment by MCatherine1994** [comment]
Please check this wiki page: https://github.com/bcgov/nr-forests-access-management/wiki/Testing-Approach

**Comment by gormless87** [comment]
Good point Nick. Our DOD and DOR need work.
