### ISSUE TITLE
Request new AWS certificates

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#698]
**Describe the task**
TLS Certificate used RSA 2048 bit with SHA-256 too weak. Replace existing certificate in AWS Certificate Manager with one using ecdsa-384 algorithm.

**Acceptance Criteria**
- [x] ecdsa-384 based certificate issued
- [x] process documented in case we (or others) need to do this again
- [ ] 

**Additional context**
- https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Improving+Security
- Looks like this will require revalidating the domain which is a tricky process to coordinate. We could test in dev.
- AWS req's proof of domain ownership prior to issuing a cert. 72 hr window, hard to coord in gov timelines; need to give network team (Lucas?) advance notice to prioritize 
-- bundle request for all 3/4 env's 
- AWS complication: certs are created in US East; cets auto renew once implemented

**Comment by ianliuwk1019** [comment]
YFI... "[According to research conducted by Microsoft, it’s been found that ECDSA is easier to solve compared to the RSA cryptosystem for **Quantum Computing**](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/09/1706.06752.pdf)" (bottom of the article - Discussion section) @gormless87 @basilv

**Comment by basilv** [comment]
Nice job finding this. I looked at the paper, but don't have the expertise to evaluate. Chris Prince would need to review and comment.

**Comment by gormless87** [comment]
Created Service Desk Jira issues https://apps.nrs.gov.bc.ca/int/jira/browse/SD-81756 for updates to existing vanity URLS and https://apps.nrs.gov.bc.ca/int/jira/browse/SD-81757 to create a new vanity URL for the TOOLS namespace.

**Comment by MCatherine1994** [comment]
documentation added at: https://github.com/bcgov/nr-forests-access-management/wiki/Update-AWS-Cloudfront-Certificate

**Comment by basilv** [comment]
Certs had to be P256 to be compatible with cloudfront
