### ISSUE TITLE
Renovate babysitting

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#713]
Describe the task
Address renovate PR's in a timely manner. Clear communications with DevOps Specialist.

Acceptance Criteria

 All PR's accepted and implemented OR declined

**Comment by gormless87** [comment]
Differentiate security vulnerabilities from regular updates

**Comment by gormless87** [comment]
@DerekRoberts Snyk-related PR does not follow conventional commit format

**Comment by basilv** [comment]
@DerekRoberts never mind the above. The snky commit does follow conventional commit, but when I auto-updated the branch from main in GitHub, the commit message from GitHub didn't follow conventional commit format and caused the linter failure.

**Comment by DerekRoberts** [comment]
> @DerekRoberts never mind the above. The snky commit does follow conventional commit, but when I auto-updated the branch from main in GitHub, the commit message from GitHub didn't follow conventional commit format and caused the linter failure.

Shouldn't we be focused on PR titles and not commits? We do have a fair bit of control over PR generation.

**Comment by basilv** [comment]
FAM is using conversational commits for generating release notes, so the commits do matter. But as it turns out, we do squash & merge anyways for these PRs, which allows us to edit the final commit message anyway, so this isn't an issue with any of the devops tooling setup.
