### ISSUE TITLE
Component/integration testing for Summary Page

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#716]
**Describe the task**
Create integration test for the summary page. Need some learning for the testing library.

**Acceptance Criteria**
- [ ] test the functionality for all elements in the summary page
- [ ] increase the code coverage for the summary page

**Comment by gormless87** [comment]
May not need to do - summary page replaced with Modal (pop-up)

**Comment by MCatherine1994** [comment]
summary page is deleted, no need this ticket anymore
