### ISSUE TITLE
Get user profile information from cognito id token

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#720]
**Describe the task**
Think maybe we could start try to get the user profile information from the Cognito id token. So far we only have the IDIR userID in the id token, maybe we could see if we could grab the display name and the email by adjust the Cognito config in the terraform for FAM.

**Acceptance Criteria**
- [x] Remove the hardcode data in the profile
- [x] Add display name and email to the id token return by Cognito
- [x] Display the userID and display name and email get from the id token to the profile section 
- [x] Test and confirm with IDIR only at this time

**Additional Info**
 - Frontend only

**Comment by MCatherine1994** [comment]
Hi @OlgaLiber2 not sure what avatar we should use for the user, I just use the first two letter in the IDIR username and shows as an avatar for now. Background color and text color are hardcoded to use the blue and white we use for the header. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f921a983291352e6618d021aefe0445101ee06fb/Screen%20Shot%202023-09-14%20at%201.26.51%20PM.png)

**Comment by gormless87** [comment]
Works in DEV:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVhHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b51681c2d3f3551b9fcd8f08c7f2ea321eb2f731/image.png)
