### ISSUE TITLE
Add WAF through terraform

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#725]
**Describe the task**
Create WAF ACLs using terraform, and add WAF to the cloudfront and api gateway and cognito

**Acceptance Criteria**
- [ ] WAF ACLs has been created through terraform
     - One for Cloudfont with Global region, with 5 rules:
                - Amazon IP reputation list (AWS-AWSManagedRulesAmazonIpReputationList)
                - Core rule set (AWS-AWSManagedRulesCommonRuleSet)
                - Known bad inputs (AWS-AWSManagedRulesKnownBadInputsRuleSet)
                - Linux operating system (AWS-AWSManagedRulesLinuxRuleSet)
                - SQL database (AWS-AWSManagedRulesSQLiRuleSet)
     - One for Api Gateway with Canada region, with the same 5 rules as above
     - One for Cognito with Canada region, with 3 rules, because the other two rules block the access outside Canada, Nick and Jota can't access to FAM when added those two rules
                - Amazon IP reputation list (AWS-AWSManagedRulesAmazonIpReputationList)
                - Known bad inputs (AWS-AWSManagedRulesKnownBadInputsRuleSet)
                - Linux operating system (AWS-AWSManagedRulesLinuxRuleSet)
                
- [ ] WAF has been added to the cloudfont, api gateway and cognito through terraform
- [ ] Added a comment for the ACL for Cognito, explain why we can only have three rules

**Aditional info**
Test this out in the TOOLS environment - hack-away!

**Comment by ianliuwk1019** [comment]
For web ACL for Cloudfront, AWS says:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2NWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e961b6417d7f94ba47d0acc627a58c116ee1520b/image.png)
However, I am facing an error: 
```
│ Error: reading WAFv2 WebACLs: WAFInvalidParameterException: Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "4867c2ce-9e12-4931-b752-9c997aefd894"
│   },
│   Field: "SCOPE_VALUE",
│   Message_: "Error reason: The scope is not valid., field: SCOPE_VALUE, parameter: CLOUDFRONT",
│   Parameter: "CLOUDFRONT",
│   Reason: "The scope is not valid."
│ }
```
This seems to indicate the ACL created for Cloudfront has issue, perhaps something is missing for Cloudfront WAF ACL resource block.

**Comment by ianliuwk1019** [comment]
When merging pr to main, terraform deployment fail due to the WAF resource already exists (previously WAS were added from AWS console manually).
Manually deleted WAS and redeploy resolve the issue.

Next release (TEST/PROD) we will need to remove these manually added WAF first before deployment.
@gormless87

**Comment by ianliuwk1019** [comment]
When merging pr to main, terraform deployment fail due to the WAF resource already exists (previously WAS were added from AWS console manually).
Manually deleted WAS and redeploy resolve the issue.

Next release (TEST/PROD) we will need to remove these manually added WAF first before deployment.
@gormless87
