### ISSUE TITLE
Spike: how we can support redirect urls pattern in Cognito

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#727]
**Describe the task**
For the application that is deployed in openshift, all their dev deployment urls is using a pattern of "https://[app_name]-[pull_request_number]-[whatever].apps.silver.devops.gov.bc.ca/", and it's not a fixed one. We're having this problem for FOM as well, whenever we want to test the login in dev, we need to manually add the redirect urls in Cognito. Maybe we should check if there is a way can support a url pattern for redirect in Cognito.

**Acceptance Criteria**
- [x] To see if there is a way can handle the redirect urls that are not fixed

**Comment by ianliuwk1019** [comment]
Part of this was explored at last few comment s on ticket #430.
Attached screenshot.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/371adc83-79ef-4240-ad50-968552b0b7eb)

**Comment by ianliuwk1019** [comment]
I have seen an AWS documentation for endpoints available to call for callback url before, mentioned previously in Team Chat (but now being removed) and forgot to document that on previous ticket. But they are available for us to use.

Some points of thoughts if we are going to improve for these:
- These callback urls are specific for our client apps (not for FAM), I am feeling it is **not necessary** to be added into **Terraform** for each application to increase our difficulties for release (**except our FAM itself** for the callback url).
- AWS has this strict callback url without wildcard pattern for security reason.
- For **PROD-PROD** environment we probably have this new built API only for FAM internal to update callback url on behalf on our client apps; or if we decide to allow other clients updating Cognito callback urls for other client apps than the new built API has to work in a very secure way.
- For lower environment like **PROD-DEV/PROD-TEST**, probably can open for other client apps to do update freely.

**Comment by MCatherine1994** [comment]
Reference reading and learning:

[AWS Cognito user pools API Guide](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/Welcome.html) and [operation list](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pools-API-operations.html)   
[example of the API method to update cognito user pool client setting in python](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp/client/update_user_pool_client.html)
[more sample code](https://docs.aws.amazon.com/cognito/latest/developerguide/example_cognito-identity-provider_ListUsers_section.html)


I think most of the time, the test and prod client will have a fixed url. We could start with one api just the dev client.

**Comment by MCatherine1994** [comment]
If we use python and boto3 library, we need to [config the credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) in order to connect to our AWS service. I'm not so sure if we have an [access account and key](https://docs.aws.amazon.com/powershell/latest/userguide/pstools-appendix-sign-up.html) pair, or we need to create or apply one. 

```
import boto3

cognito_idp_client = boto3.client(
    'cognito-idp',
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY
)

response = cognito_idp_client.update_user_pool_client(
    UserPoolId='string',
    ClientId='string',
    CallbackURLs=[
        'string',
    ],
    LogoutURLs=[
        'string',
    ]
)
```
