### ISSUE TITLE
Address high severity dependabot alert #112 - fast-xml-parser vulnerable to Regex Injection via Doctype Entities

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#734]
This security alert is not addressed by existing rennovate-bot PRs, so a PR https://github.com/bcgov/nr-forests-access-management/pull/730 was created from dependabot but there are compatibility issues as the CI build fails.
(Although the build fails might not be related?)

Raising this as an issue since it doesn't appear to be covered by RennovateBot.

**Comment by ianliuwk1019** [comment]
#752 is merged and closed. So this one can be closed as well.
