### ISSUE TITLE
Replace the close button for the error dialog to top right

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#739]
**Describe the task**
Fix the close button for the error dialog when assign duplicate role. Should we have the close button on the top right?
![image.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/00e2a851-f6f3-4056-abb5-5deac6bbe004)

**Acceptance Criteria**
- [ ] replace the close button to the top right

**Comment by J0taFerreira** [comment]
That is weird, I tested it in three different browsers and it is ok for me. Can we talk about it so I can understand it better?![409_edge.png](https://images.zenhubusercontent.com/649090ffb7619f1bbb8a8889/035a6869-d440-4750-907c-bec9ab31d9a4)![409_firefox.png](https://images.zenhubusercontent.com/649090ffb7619f1bbb8a8889/57a72287-a658-4425-b338-9a90d2fece00)![409_google.png](https://images.zenhubusercontent.com/649090ffb7619f1bbb8a8889/0ae6d3d2-5f1f-4e7c-9692-49388b915161)

**Comment by MCatherine1994** [comment]
When we run our code locally, the api call for duplicate user role assignment will return a status code "409 conflict", but in FAM dev, it only returns "409"

![image.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/10d30631-520d-446c-a353-bab5fe2f7720)

![image.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/73e4949e-402f-441e-b220-9cc81fef36f3)

**Comment by ianliuwk1019** [comment]
Backend returns "**HTTPStatus.CONFLICT**" in code for FastAPI. I don't see we manipulate that. But as long as it is still a 409, it is correct. I have no idea that extra "Conflict" is coming from.
Does it create problem for the frontend? I assume not.

**Comment by MCatherine1994** [comment]
yeah... frontend will think backend will return "409 Conflict", so "CONFLICT" will be the title of the popup modal. But it returns only on local, but not in FAM dev. Not sure why it's difference between local vs deployed version. I think the frontend should have a default title though, just in case we don't have error title returned from status code.

**Comment by ianliuwk1019** [comment]
I see. Seeing the "Title" as "CONFLICT" isn't right to me. I would not believe it is a language from the service design.
Frontend should not use "**useErrorDialog.dialogTitle = axiosResponse.statusText**;" as its title. This has no meaning for the user in general and is specific for the http verbose. 
I think, **With "title" or without "title"**, the component probably (possibly) can be **style** in a way the button is always on the right corner. Hope it is not difficult, but if it is, use our header template (slot) might also be possible.
@J0taFerreira

**Comment by MCatherine1994** [comment]
yeah, I feel we could use a hardcode title like "Error", and make the button always on right corner

**Comment by MCatherine1994** [comment]
Will close this one, we'll switch to use toast notification to show server errors in #746
