### ISSUE TITLE
Secret scanning plugin for github

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#744]
**Describe the task**
Integrate (investigate if this is a SPIKE!) a secret scanning plugin for the FAM GitHub repository - to prevent secrets from getting committed.

**Acceptance Criteria**
- [ ] Enabled GitHub security secret scanning

**Additional context**
- Trivvy already scan for passwords  -what about tokens?

**Comment by basilv** [comment]
I've enabled secret scanning in GitHub that blocks pushes if a secret is detected. If this causes issues the push protection can be disabled
