### ISSUE TITLE
User duplication check for BCeID changed username

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#747]
**Describe the bug**
If a user has already logged into FAM with a BCeID, and then edits BCeID user name, the auth function will insert a new user record (with same GUID), since the 'on conflict' logic is done by user_type_code and user_name, not by user_guid.

**To Reproduce**
1. Log in through Cognito with a BCeID
2. Change BCeID username
3. Kill the Cognito session (through the console)
4. Log in through Cognito again
5. Observe 2 records in the DB for the same user

**Expected behavior**
A new record should only be created if it is a different BCeID. The auth function should compare the GUID first and do an update if the GUID already exists.

**Additional context**
This is legacy MVP behaviour. There is a case where we use the FAM console to assign a role to a user that has never logged in. Because we don't currently look up the user, we don't have the GUID at that time, so the check is done on username and usertype to handle that case. Until we have GUID reliably in every case, we will need to do both the GUID check and the existing one. The logic of the check likely has to change as I don't think we will be able to do the "on conflict" query in this case.

**Comment by MCatherine1994** [comment]
This ticket we can wait a bit once we can search for bceid, so we will create the user with guid to solve the special cases in the additional content. 

- [ ] when user login through FAM, in the Auth Lambda function, update the auth function, to check conflict on user guid, and update the user name if needs
<img width="1721" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f7403e2ec8db1cbabd99091973f646303d9c9a1/image.png" alt="image.png" />

- [ ] when grant user access in FAM, verify the user name. Check user exists or not by user type and guid. If user does not exist, create the user with username, user type and guid. If exist, update the username if needs
 <img width="1656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b43ad764ef7b92b7614833d0fe1992e327cbf930/Screen%20Shot%202024-01-12%20at%202.29.31%20PM.png" alt="Screen Shot 2024-01-12 at 2.29.31 PM.png" />

**Comment by MCatherine1994** [comment]
It's better to wait until we get the access to verify BCEID, so we can store the guid when granting use access (this is when we create the user in our database).

**Comment by gormless87** [comment]
Old ticket; refinement needed

**Comment by MCatherine1994** [comment]
Note that IDIM web service doesn't support search IDIR user by user_guid

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/21bfd875-c174-4dee-b5e8-9def49e5bbaa)



![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/5a6b6ea5-5307-463f-a868-8e7407e352fb)

**Comment by MCatherine1994** [comment]
There are 594 users in FAM PROD has no user_guid

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/103280e5-67f3-41bd-91bb-90d0bed7128a)

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/82a94ff0-b75a-44c7-b1c6-784d474953a9)

**Comment by MCatherine1994** [comment]
All users in FAM PROD that has user_guid are having user_guid all upper case. There are total 1416 users, 594 of them has no user_guid.

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/9fc1d47a-2a4c-49bd-864a-d2a59c805610)



![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/36a1198d-9022-49f7-b2f2-e9ced8436e8e)

**Comment by ConradBoydElliottGustafson** [comment]
That seems like a lot of missing user_guid records. Are they the result of a bulk load from another system, and maybe the users have not yet logged in through FAM? It seems unlikely that there would be that many users that were manually entered by an admin.

**Comment by MCatherine1994** [comment]
Need to verify in FAM DEV:

For Auth Lambda:
- [ ] For existing user with no user_guid stored, user_guid is added when the user logs in
- [ ] For new user login to FAM, user_guid is added
- [ ] For existing user has user_guid stored, nothing changed, login is still successful

For app access management and admin management apis:
- [ ] For granting access to existing user with user_guid stored, nothing changed, grant access successfully
- [ ] For existing user with no user_guid stored, user_guid is added 
    - [ ] When grant the user admin access
    - [ ] When grant the user delegated admin access
    - [ ] When grant the user app access
- [ ] For granting new user access, user_guid is added

**Comment by ianliuwk1019** [comment]
Test cases are good and verified from screenshots. Thanks Catherine!!
