### ISSUE TITLE
Frontend: Missing Assigned Role Information and Wrong Forest Client Number Displayed for REVIEWER role at Summary Page

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#748]
**Describe the bug**
FAM Grant Access summary page has no information for intended "assigned role" from the user pick, and Forest Client Number seems to be cached into summary page when "FOM_REVIEWER" role is selected (only SUBMITTER role needs forest client number).

**To Reproduce**
See below screenshot for steps.
1. User select SUBMITTER role to assign to a user:
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/15c4454e-7f0b-417d-bb0c-914ddb75cd86)
2. User does not see assigned role information on summary page:
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/841d0c80-e3c8-4644-9577-02030f6d4cc7)
3. User changed mind and select REVIEWER role to assign to a user:
    ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/3ee563ef-8a41-4b5b-ac02-b0a9314c57c2)
4. Forest Client Number cached into summary page (while it should not be there).
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/df475e05-57af-4ef4-87b1-33d612cd1bb7)
5. Although result and dashboard are correct.
   ![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/706c5d8c-d15f-4bdd-bfb3-9465e2843438)
**Expected behavior**

**Screenshots**

**Additional context**
Bug found at FAM frontend new design.

**Comment by NickSaglioni** [comment]
The first item of the ticket, displaying the role in the summary page, has already been fixed in a previous merge.
