### ISSUE TITLE
New FAM DDL - update data model

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#75]
Based on a discord convo:

While we are at it, the "name" field should be unique on other tables as well: fam_group, fam_role, fam_forest_client,
And there should be a unique key on fam_user for user_type/user_name combo
And we decided that we need fam_user.user_guid to be nullable for MVP (since we aren't doing a lookup yet at IDIM)
And we flubbed the multiplicity of the relationship between fam_application_client and fam_application. It was supposed to be many fam_application_client to one fam_application. We have it the other way around.
And renaming app_fam.group (name) to app_fam.group (group_name), so to use a consistent naming convention across the model. E.g. : role, client, application have columns named "role_name", "client_name", "application_name" .....

AC:
put migration into repo; pipeline run into DEV goes smoothly

**Comment by rparfig** [comment]
Completed. Merged into dev branch and successfully deployed to the database.
