### ISSUE TITLE
Sync alembic model with new DDL from #75

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#76]
Push new DDL changes to alembic/SQL Alchemy and fix tests

AC:
tests pass
process for model changes is documented

More investigation req'd before estimate is refined. Detail around schema prefix (private alias)

**Comment by franTarkenton** [comment]
Thinking this ticket would consist of:
1. get the latest DDL that has been created for the database and materialize it in a postgres temp database
2. Generate a new sqlalchemy model from the database
3. Run alembic to create a migration that implements the changes in the database model

Anticipated problems / Issues
* including schemas in alembic migrations is not necessarily something that comes out of the box with alembic.

**Comment by franTarkenton** [comment]
This ticket is addressed by:
https://github.com/bcgov/nr-forests-access-management/pull/98
