### ISSUE TITLE
Frontend: evaluate and upgrade vue-final-modal package from Renovate #618.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#760]
**Describe the task**
We can't directly upgrade version from this Renovate pr: https://github.com/bcgov/nr-forests-access-management/pull/618
Upgrade `vue-final-modal` from v3 to v4 will break FAM frontend due to breaking changes.

![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/ed5070e7-2e71-4076-aa57-18ff62a6a91c)

Either evaluate if this lib/package is still needed or use other modal (based on our soon be implemented new design), or migrate the code to use v4 version of `vue-final-modal`.

**Comment by gormless87** [comment]
May be addressed via #714
