### ISSUE TITLE
Draft Fingerprint team member Onboarding Guide

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#778]
**Describe the task**
Create a Confluence page to document required and recommended step to onboard a new Fingerprint team member.

**Acceptance Criteria**
- [ ] Draft document with internal review
- [ ] Ready for external review
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by MCatherine1994** [comment]
Added to confluence page: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Onboarding+Team+Member+Guide

**Comment by OlgaLiber2** [comment]
@OlgaLiber2 to review this

**Comment by OlgaLiber2** [comment]
@MCatherine1994 

Basil's suggestions to add to the confluence page to satisfy the security item for onboarding new team members: 

- Identify team members role before granting access. E.g. developer, ops access
- Familiarization with Heartwood software development process (not yet documented) and if doing ops, our operations guide
- Training in secure application development (assuming BC Gov has a training option for this).
- For new developers, local developer environment setup

**Comment by MCatherine1994** [comment]
The only kind of security training I did is that information security training (IM 117 Information Management: Access, Information Security, Privacy and Records Management), I believe it's for all gov employee. Not sure if we have any other secure development training.
