### ISSUE TITLE
Create Github access control policy

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#791]
**Describe the task**
Create a GitHub access control policy that includes onboarding/offboarding/transition instructions 

**Acceptance Criteria**
- [x] Inventory of current acess
- [x] Clearly defined process for granting GitHub access
- [x] Clearly defined process for removing GitHub access
- [x] Clearly defined process for reviewing GitHub access 
- [x] Clear triggers for review - regularly scheduled and/or event-driven

**Additional context**
- Must include differentiation by role (developer, admin, other)
- Must include differentiation by environment

**Comment by MCatherine1994** [comment]
Added documentation to confluence: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/GitHub+Access+Control+Policy

**Comment by OlgaLiber2** [comment]
@basilv  to review and close the ticket

**Comment by MCatherine1994** [comment]
Added the review access part into a separate file: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Review+Access+Control+Policy

**Comment by OlgaLiber2** [comment]
@ConradBoydElliottGustafson to review this

**Comment by ConradBoydElliottGustafson** [comment]
Reviewed! I left a couple of minor comments in Confluence. Let's close this sucker.
