### ISSUE TITLE
Create AWS access control policy

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#792]
**Describe the task**
Create an AWS access control policy that includes onboarding/offboarding/transition instructions 

**Acceptance Criteria**
- [ ] Inventory of current access
- [x] Clearly defined process for granting access to AWS projects
- [x] Clearly defined process for removing access to AWS projects
- [x] Clearly defined process for reviewing access to AWS projects
- [x] Clear triggers for review - regularly scheduled and/or event-driven
- [x] Document in Confluence

**Additional context**
- Must include differentiation by environment (TOOLS, DEV,TEST, PROD) 
- Must include differentiation by role (developer, admin, other)

**Comment by MCatherine1994** [comment]
Draft documentation added to https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/AWS+Access+Control+Policy. But I'm not so sure about the following questions:

- when we want to grant a user access, how should we reach out to the pathfinder team (through rocket chat or email)? what we need to provide to pathfinder team (IDIR name and role, more...)? how the process looks at? how long it will take?
- when we want to remove a user access, what we need to provide to the pathfinder team?
- who should be able to manage our AWS access? only the pathfinder team or we have self manage it?

@ConradBoydElliottGustafson @basilv @gormless87

**Comment by MCatherine1994** [comment]
#537 will take care of the review of our current AWS access

**Comment by OlgaLiber2** [comment]
@MCatherine1994  will contact SSO pathfinder team to answer those questions

**Comment by MCatherine1994** [comment]
Added the review access part into a separate file: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Review+Access+Control+Policy
