### ISSUE TITLE
Create secret rotation playbook

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#794]
**Describe the task**
Create a secret rotation playbook so action can be taken without delay in the event of leakage

**Acceptance Criteria**
- [x] Inventory of all secrets
- [x] Classification of secret access by role
- [x] Clear triggers for rotation - regularly scheduled and/or event-driven
- [x] Clear instructions for accessing each secret
- [x] Clear instructions for rotating each secret

**Additional context**
- Must include differentiation by environment (TOOLS, DEV,TEST, PROD) 
- Must include differentiation by secret type (GitHub, OpenShift, AWS, IDIR, other)

**Comment by OlgaLiber2** [comment]
@basilv  to create a template for @MCatherine1994 to work off of

**Comment by basilv** [comment]
Template pretty much complete - see https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Secret+Rotation+Procedure and https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Secrets+Registry

**Comment by MCatherine1994** [comment]
- [ ] remove unused secret in FAM repo FC_API_TOKEN
- [ ] verify if need specify IDIM_PROXY_API_API_KEY for each environment when the value is the same, if not, remove the duplicate ones
- [ ] verify if we need a default FOREST_CLIENT_API_API_KEY secret, when we already specify it for each env

**Comment by ConradBoydElliottGustafson** [comment]
Added a bunch of content and comments on the page. Please review!

**Comment by basilv** [comment]
Thanks Conard. I added some comments and made some edits as well.
