### ISSUE TITLE
Enable notification email after grant user access

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#799]
**Describe the task**
Send email notification after granting a user access in FAM. We already have our backend integrated with GC Notify. 

**Acceptance Criteria**
- [x] Update IDIM proxy return schema to include user email
- [x] Update target user schema to include email
- [x] Review the GC Notify api, update parameters based on the template from ticket #1073  if needs 
- [x] At the end of the create user role assignment method, call the gc notify email api to send the email
- [x] Only call the email api when frontend check box is checked
- [x] Verify the parameter pass to the send email method, make sure the email address is a validate one

Additional information
- In the case that email sending failed, what we need to do?  Can we trust the gc notify server and our server enough?
- Email for granting delegated admin is in ticket #1469

**Comment by MCatherine1994** [comment]
The first two acceptance criteria are done

**Comment by MCatherine1994** [comment]
Currently when we grant app access with multiple forest client numbers, we call the api multiple times. But I feel we don't want to send multiple email in this case, maybe I should create another ticket to allow the current POST method support multiple forest client numbers? So from frontend we just call the api once, and send one email with multiple forest client numbers? @ianliuwk1019 

Delegated admin is fine.

**Comment by ianliuwk1019** [comment]
> Currently when we grant app access with multiple forest client numbers, we call the api multiple times. But I feel we don't want to send multiple email in this case, maybe I should create another ticket to allow the current POST method support multiple forest client numbers? So from frontend we just call the api once, and send one email with multiple forest client numbers? [@ianliuwk1019](https://github.com/ianliuwk1019)
> 
> Delegated admin is fine.

I feel ideally it should have been like that previously; but due to we were reusing existing endpoint for quick implementation. I think we should, we probably don't want to send email for each different forest client number. It will have a major refactor at frontend I feel.

**Comment by MCatherine1994** [comment]
> > Currently when we grant app access with multiple forest client numbers, we call the api multiple times. But I feel we don't want to send multiple email in this case, maybe I should create another ticket to allow the current POST method support multiple forest client numbers? So from frontend we just call the api once, and send one email with multiple forest client numbers? [@ianliuwk1019](https://github.com/ianliuwk1019)
> > Delegated admin is fine.
> 
> I feel ideally it should have been like that previously; but due to we were reusing existing endpoint for quick implementation. I think we should, we probably don't want to send email for each different forest client number individually. It will have a major refactor at frontend I feel but should be a better frontend after change.

yeah I agree, even later one with the new design, this should still be okay. I'll create a new ticket and we could bring it up in tomorrow's scrum
