### ISSUE TITLE
Create lambda function to run flyway for DB migrations

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#8]
Need to deploy FAM data model - Terraform

We are using Flyway DB to manage migrations. The challenge is that we can't run the migrations from github actions because we can't create connections to the database from outside of AWS. 

Decision: Run Flyway inside a Lambda function that connects to the database and runs migration scripts

AC: 
Create the terraform code that provisions a lambda function that can connect to the database.
Get the database credentials from an AWS secret

Out of scope: Migration scripts added to the repo will get applied as part of the CI/CD pipeline triggered from Github Actions.

**Comment by basilv** [comment]
Decisions: ECS Task using Flyway.

**Comment by gormless87** [comment]
@basilv  - some background on 1Team's use of Liquibase, borrowing some Flyway script naming conventions.

https://apps.nrs.gov.bc.ca/int/confluence/x/qSAzAw

**Comment by ConradBoydElliottGustafson** [comment]
Breaking this into 2 parts. Keeping this ticket as part 1.

1. Create a lambda function that can run flyway and connect to the database
2. Integrate the lambda function execution as part of the CI/CD process

**Comment by ConradBoydElliottGustafson** [comment]
Merged into DEV. Not merging anything into main at this time!!
