### ISSUE TITLE
Manage AWS Bastion Host via Terraform

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#802]
AWS Dev workspace has a manually created bastion host (BasilBastionHost) and manual creation complicates doing a security review of the AWS resources. Plus what's in other environments isn't necessarily consistent. 

Assuming we need / have a bastion host in each workspace (do we?) we should create it in Terraform.

AC:
- [x] cleanup existing manually created bastion hosts
- [x] modify Terraform scripts to deploy bastion host in dormant state as part of regular pipeline 
- [x]  include Postgres

**Comment by ianliuwk1019** [comment]
Just keep a note for current (BasilBastionHost) detail information:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2FnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ab9fdc9deead88557c15a352de5e8c3ad226d64f/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc21nIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2bebe17b1e50f41baf33143c7206c01887a5a501/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3FnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bdca68c8cb2b89b3af28af7b03b043bb643602ce/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3VnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb3f57abf47cb825c910c87728d68cf98d70c001/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEdnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e1cf9b1ee798643c9dedaefd887b343c849458c/image.png)

**Comment by ianliuwk1019** [comment]
A bit confused for our current Bastion Host setting.
Based on my reading from AWS (I now understand Bastion Host is an EC2 instance, not a special tool thing :P), seems typically Bastion Host is created on "**Public** Subnet", but our manually created instance looks to me is on "**Private**" subnet (**App_Dev_azb_net** "Subnet ID: subnet-048e25be105ae01d3").
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVdoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2224da102fe9a43bd3016845ac5425ebbe491179/image.png)

Should we code a terraform code to create the Bastion Host EC2 instance on "Public" or "Private" subnet?
Also, probably since we have more restrict security groups defined now, we need to use them for the instance.
@basilv

**Comment by basilv** [comment]
Because we're accessing the Bastion Host through the AWS console (and can't access it directly externally), it basically doesn't matter what subnet its put in from an access standpoint. (Traditionally, bastion hosts are accessed directly via SSH (or via VPN) and need to be in a suitably accessible subnet.)
I'd lean towards putting the bastion host in the app subnet and fam app security group. (Yes, have to use the more restricted security group fam_app_sg.)

**Comment by basilv** [comment]
And yes, bastion host is a concept. Used to be called 'jump box' (and sometimes still is).

**Comment by ianliuwk1019** [comment]
Thanks Basil.
I notice there is a KeyPair but I can't obtain the value from console.
How did you create it, what is that for (SSH? but in app subnet, we can't ssh in right?) and I assume we don't need that, is that correct?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7cccb5d16b428553e2d9a81eee14647da1b8db6b/image.png)

**Comment by basilv** [comment]
Hmm, I think I was trying to set up for SSH, before I realized it wouldn't work. Its also possible its created by default, a requirement to have the EC2 instance. You won't be able to retrieve the value and don't need it explicitly to connect with AWS console.

**Comment by ianliuwk1019** [comment]
Had draft terrafom file to deploy to tool but keep getting this error:
```
data.aws_lambda_invocation.invoke_flyway_migration[0]: Still reading... [20s elapsed]
data.aws_lambda_invocation.invoke_flyway_migration[0]: Read complete after 21s [id=fam-flyway-lambda-tools_$LATEST_b2569c0cc651976848896adcd81284c0]
╷
│ Error: creating EC2 Instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: a44LiNtG7beLzkn_f3g0By55O6k1Qyzr2BRhHfQwKbnOW7LfdnE1fJ_RvUOp89znayn_C-pFAYE1ZJgD6OoUkM6_IVk0N2pLwqtxOhM-Rq890v32dP2lDnuWT1k3aJqvDSxONwaqck3N6TfS32pgtDPWlrlVrKOjf0iOgQbm9-SYfFf5P9n7ojgbvnpA-4NJwUdLm2qMOg5MaEcGwUZrMiJhddXRBrOgQJy7wrARuCkSeKfPFYVxixLZakWsHbUuDIjfjwc4mNKDRIU46HMNWOB22-UHj_27MO06jEawYnuVVgzA8RDQEXJMGhjTFKpr0uqU9apa4lxxqJNN5ilfSvrl1diun4cJOiIsDAqPhPoCruGcY6Rg-nWm0sgHzSmtm2mF8Nxb9xfSTaHlBt_FJbY6E_VY6Qgoy53f-zI9tQQsNnBJtyNwhxSFouh5JGyB6uXW2tVKIVKJoEzMSd3txUw4xVDrYaMQ_nDnUCeWnTFYlfyZkvMcKTz4VjzDvLXh2SI-yLSv6VhfCmLBvfXuTvRVlFT35cv0vMPuGceVYBOE4WLFVe-oiOb2e11yuZgf2zMQm9U3HK4q6dM2KEpINDQ5t_71U4L0DFS6A_Nvbf3PplsedD-VtGC77GS4k8mD0qEwuGhbjvT9FxAJsFfyukPj2cszF8gE5o9fa2xBbTGqUp3HA8SX_r9Em9cIQZFci8l6xc4P9KmGJaAwFRycMKz9btkOX1H7s3mnbzwswzhvh8zSlbFyqk_ZegAlpzInGHG32CvNwJ7CxH7EDu8zHFj3JcPb2YgXflTkhZD-dKr3PfWS
│ 	status code: 403, request id: 8bacd3e0-7f90-4657-a803-d60a5f165d6c
│ 
│   with aws_instance.fam_bastion_host,
│   on ec2_instances.tf line 15, in resource "aws_instance" "fam_bastion_host":
│   15: resource "aws_instance" "fam_bastion_host" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
time=2023-09-18T23:22:46Z level=error msg=Module /home/runner/work/nr-forests-access-management/nr-forests-access-management/terraform/tools has finished with an error: 1 error occurred:
	* exit status 1
```

Initially thought it might be due to dependency of security group, but after adding dependency to the resource, still the same:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGF2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d3c276e5f043b303eef8dd9afbbdd1990b18fbb/image.png)

Could be something to do with the IAM?....

**Comment by basilv** [comment]
It is possible the configuration of the bastion host (EC2 instance) violates ASEA rules. E.g. you can't add a public IP address. Otherwise, might need to engage the cloud pathfinder.

**Comment by ianliuwk1019** [comment]
I have tried using "iam_instance_profile" (with linking to iam resource) available in the "aws_instance", but it is still getting the same error.
Perhaps I am not in the right direction.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWUzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c6b496faab73e2cbb8878700600644fd268531d/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUczIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac83cc38bb2ddaed6e7573590e00080ac9309537/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVMzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--df568a620dbd46763881b84210547a1ca3f1c29d/image.png)

Getting the same Terraform apply error.
```
data.aws_lambda_invocation.invoke_flyway_migration[0]: Read complete after 20s [id=fam-flyway-lambda-tools_$LATEST_b2569c0cc651976848896adcd81284c0]
╷
│ Error: creating EC2 Instance: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: juGPyqKA3Cwc4xRFXlpzBxSpr9ia46l5PaNAgHwiTRezn8bq0eecGxtKq5zEkrVXZc-FDdRJ94AkS-zOfEwzveH0pxRpg9nAH20o5g3yEu09T7O3jo2TCltpiLr5jpqsRDyEFXKd5Bj5U2LLZXVppUdigsjBukgb4xN6EDSw3EQsE1dferZn7iAxJUlXttYMx0o9zmUhIHMC1yY_XXRDV-r0C-56rasrFScYxVi23acDWFoFy12xU9WeMlfEtGXJhjumVng8hn--xlkFOHyqFIdvYv8fTfIxnvp8PMkl7vFWDoLxCqjF4i_6EazfIaDs-Tzps__WOZHs2HBUYWxdpV87TVVIzyKHn178nzdKp13lDy0zimUsF4vu5FdfQ0Wuj1SRNNLL0JC0JrZ0xppvqyYZr5V0limESkvHRlAj4AAbdqarSRgXObc-14XHe8-s2rJsG3hqEQf1tvPz4Otg6JiR70CFBtOSvTXFrEQuRqExXo4vT4p6Uraml5Lah0XskNGChU54wjHgNIUGqAWSgQ9glEo_Fs1y0RWkslMcLpsiNSqAvqKhEcmg7Jnq6P-XP-kggiyoqGlHYzJ_G4YSkiOG8Qz0sE4FKjnxgUtIACp3AiC8S4Pa6uHUneZZZQuwztjWtH3OBe454t5D7fN13mL2r1jaVcDCeMYSOOyhz0i6abQwhLVTW658rT8rioBnyJv6pymuog7iAXAELh7PdrYHe9Hc6t7oCPxVSM_zSYQ_Vdcdn1jokt9OVZbsNSO9oGOfXme2S4p22kVYBJFa-DB_8hsEdqB03oOGJ2F3bUiAOg
│ 	status code: 403, request id: 91255ecc-6fed-48df-8a1b-bd826c48613e
│ 
│   with aws_instance.fam_bastion_host,
│   on ec2_instances.tf line 18, in resource "aws_instance" "fam_bastion_host":
│   18: resource "aws_instance" "fam_bastion_host" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
time=2023-09-19T23:38:24Z level=error msg=Module /home/runner/work/nr-forests-access-management/nr-forests-access-management/terraform/tools has finished with an error: 1 error occurred:
	* exit status 1

 prefix=[/home/runner/work/nr-forests-access-management/nr-forests-access-management/terraform/tools] 
time=2023-09-19T23:38:24Z level=error msg=1 error occurred:
	* exit status 1
```

Interestingly, for the encoded error from Terraform, we can decode it like this from AWS console cloud shell:
Using this command `aws sts decode-authorization-message --encoded-message "$msg" --output text | sed 's/,/\n\r/g' | sed 's/{//g' | sed 's/}//g' | sed 's/"//g'`
```
[cloudshell-user@ip-10-6-15-137 ~]$ msg='juGPyqKA3Cwc4xRFXlpzBxSpr9ia46l5PaNAgHwiTRezn8bq0eecGxtKq5zEkrVXZc-FDdRJ94AkS-zOfEwzveH0pxRpg9nAH20o5g3yEu09T7O3jo2TCltpiLr5jpqsRDyEFXKd5Bj5U2LLZXVppUdigsjBukgb4xN6EDSw3EQsE1dferZn7iAxJUlXttYMx0o9zmUhIHMC1yY_XXRDV-r0C-56rasrFScYxVi23acDWFoFy12xU9WeMlfEtGXJhjumVng8hn--xlkFOHyqFIdvYv8fTfIxnvp8PMkl7vFWDoLxCqjF4i_6EazfIaDs-Tzps__WOZHs2HBUYWxdpV87TVVIzyKHn178nzdKp13lDy0zimUsF4vu5FdfQ0Wuj1SRNNLL0JC0JrZ0xppvqyYZr5V0limESkvHRlAj4AAbdqarSRgXObc-14XHe8-s2rJsG3hqEQf1tvPz4Otg6JiR70CFBtOSvTXFrEQuRqExXo4vT4p6Uraml5Lah0XskNGChU54wjHgNIUGqAWSgQ9glEo_Fs1y0RWkslMcLpsiNSqAvqKhEcmg7Jnq6P-XP-kggiyoqGlHYzJ_G4YSkiOG8Qz0sE4FKjnxgUtIACp3AiC8S4Pa6uHUneZZZQuwztjWtH3OBe454t5D7fN13mL2r1jaVcDCeMYSOOyhz0i6abQwhLVTW658rT8rioBnyJv6pymuog7iAXAELh7PdrYHe9Hc6t7oCPxVSM_zSYQ_Vdcdn1jokt9OVZbsNSO9oGOfXme2S4p22kVYBJFa-DB_8hsEdqB03oOGJ2F3bUiAOg'
[cloudshell-user@ip-10-6-15-137 ~]$ aws sts decode-authorization-message --encoded-message "$msg" --output text | sed 's/,/\n\r/g' | sed 's/{//g' | sed 's/}//g' | sed 's/"//g'allowed:false
explicitDeny:true
matchedStatements:items:[statementId:EBS1
effect:DENY
principals:items:[value:AROAVPY5KNGB4FGL3AFZM:aws-go-sdk-1695166345577726189]
effect:DENY
principals:items:[value:AROAVPY5KNGB4FGL3AFZM:aws-go-sdk-1695166345577726189]
principalGroups:items:[]
actions:items:[value:ec2:RunInstances]
resources:items:[value:arn:aws:ec2:*:*:volume/*]
conditions:items:[key:ec2:Encrypted
values:items:[value:false]]]
failures:items:[]
context:principal:id:AROAVPY5KNGB4FGL3AFZM:aws-go-sdk-1695166345577726189
arn:arn:aws:sts::377481750915:assumed-role/BCGOV_tools_Automation_Admin_Role/aws-go-sdk-1695166345577726189
action:ec2:RunInstances
resource:arn:aws:ec2:ca-central-1:377481750915:volume/*
conditions:items:[key:aws:Resource
values:items:[value:volume/*]
key:aws:Account
values:items:[value:377481750915]
key:ec2:AvailabilityZone
values:items:[value:ca-central-1a]
key:ec2:Encrypted
values:items:[value:false]
key:ec2:VolumeType
values:items:[value:gp2]
key:ec2:IsLaunchTemplateResource
values:items:[value:false]
key:aws:Region
values:items:[value:ca-central-1]
key:aws:Service
values:items:[value:ec2]
key:ec2:VolumeID
values:items:[value:*]
key:ec2:VolumeSize
values:items:[value:8]
key:ec2:ParentSnapshot
values:items:[value:arn:aws:ec2:ca-central-1::snapshot/snap-0a248269a1caff902]
key:aws:Type
values:items:[value:volume]
key:ec2:Region
values:items:[value:ca-central-1]
key:aws:ARN
values:items:[value:arn:aws:ec2:ca-central-1:377481750915:volume/*]]
[cloudshell-user@ip-10-6-15-137 ~]$ 
```

**Comment by ianliuwk1019** [comment]
Currently Terraform Cloud seems to have problem, our workflow deployment with Terraform stuck for over half day already..... cancelling the run and rerun won't work.... will continue on this ticket when it is back....

**Comment by ianliuwk1019** [comment]
Was having trouble with (after) experimenting `aws_ebs_encryption_by_default`:
```
resource "aws_ebs_encryption_by_default" "default" {
	enabled = true
}
```
Note, this only works for the first time (and actually ASES has this as default and with rule that it is not allowed to change this). So if terraform somehow remove this code (like what I experienced in tools space) it will cause deployment trouble. (and need to remove this from state file).
Do not add this code.

**Comment by ianliuwk1019** [comment]
The terraform created instance initially has a custom role created that has permission too broad. Basil helped identify this from the CheckPoint tool:

> As suspected, CheckPoint is complaining. Here's the first finding:
> Title
> Ensure that custom IAM Role doesn't have an overly permissive scope (Contains a wildcard)
> (D9.AWS.IAM.108)
> Description
> To reduce the risk of a misuse or abuse due an overly privileged IAM Role, minimize the scope your IAM Role is allowed to perform actions on, according to the principal of least privilege.
> Ruleset
> AWS CloudGuard Best Practices
> Remediation
> 
> Note: The provided rule covers managed IAM Roles only: AWS service-roles and AWS service-role policies are excluded. In addition, this rule ignores any policy document block with one or more actions from the following action groups: sts, ssm, cloudwatch, ec2messages, ssmmessages, logs, route53.
> 
> From Portal
> 
> Sign in to the AWS Management Console and open the AWS IAM console at https://console.aws.amazon.com/iamv2/
> From the left pane, under 'Access management' select 'Roles'
> Identify and select the relevant IAM Role
> Edit its 'Permissions policies' according to the principal of least privilege

> Here's a suggested solution from CheckPoint to revise permissions granted to IamRole:fam_util_ec2_instance_role- I haven't tried to evaluate it:
> {
> "Version": "2012-10-17",
> "Statement": [
> {
> "Action": [
> "ssmmessages:CreateControlChannel",
> "ssmmessages:CreateDataChannel",
> "ssmmessages:OpenControlChannel",
> "ssmmessages:OpenDataChannel"
> ],
> "Resource": [
> ""
> ],
> "Effect": "Allow",
> "Sid": "CloudGuardGenerated0"
> },
> {
> "Action": [
> "ec2messages:AcknowledgeMessage",
> "ec2messages:DeleteMessage",
> "ec2messages:FailMessage",
> "ec2messages:GetEndpoint",
> "ec2messages:GetMessages",
> "ec2messages:SendReply"
> ],
> "Resource": [
> ""
> ],
> "Effect": "Allow",
> "Sid": "CloudGuardGenerated1"
> },
> {
> "Action": [
> "ssm:ListInstanceAssociations"
> ],
> "Resource": [
> "arn:aws:ec2:ca-central-1:377481750915:instance/i-038d04d1682e1235b",
> "arn:aws:ec2:ca-central-1:377481750915:instance/i-0975b847cd35f0e90"
> ],
> "Effect": "Allow",
> "Sid": "CloudGuardGenerated2"
> },
> {
> "Action": [
> "ssm:UpdateInstanceInformation"
> ],
> "Resource": [
> "arn:aws:ec2:ca-central-1:377481750915:instance/",
> "arn:aws:ssm:ca-central-1:377481750915:managed-instance/"
> ],
> "Effect": "Allow",
> "Sid": "CloudGuardGenerated3"
> }
> ]
> }

**Comment by ianliuwk1019** [comment]
Comparing in previous manually created EC2 instances in higher AWS environment (for example Dev/Test), instances are associated with this role (probably automatically): **`EC2-Default-SSM-AD-Role`**. And this role also exists in tools space. It is probably defined by **ASEA** environment.
Dev:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2988f1868dcd6aad25caf917c4cdd5f2f9c3e54b/image.png)

Switch terraform crated EC2 instance to use this **`EC2-Default-SSM-AD-Role`** role. However, Basil mentioned CheckPoint seem to have complaint for the instance at higher environment which uses this role. But I am not sure if the CheckPoint message is the same to indicate this role is also having too broad scope.

I feel we may temporary use this role and with another ticket to identify if CheckPoint still complaining about this role and the needs to communicate to #AWS-HowTo RocketChat channel for how to tweak the role for tighter permission. Or do we want to spend some time for solving this on this ticket?
@basilv @gormless87

**Comment by basilv** [comment]
Hi Ian, as I posted in the Teams chat, Checkpoint did complain about excessive access for the EC2-Default-SSM-AD-Role. So using it doesn't change the security warning. The most secure approach would be to define a new role with just the permissions needed.

**Comment by basilv** [comment]
You could try creating a new role with no permissions at all and see what happens.

**Comment by ianliuwk1019** [comment]
Your suggestion sounds good @basilv . I will experimenting little further.

**Comment by ianliuwk1019** [comment]
When experimenting on giving only one policy for the terraform created ec2 instance profile as such using policy attachment (with policy `policy/AmazonSSMManagedInstanceCore` as this one has something to do with ec2 instance Session Manager that we like to Connect to the instance) to try to reduce permission:
```
resource "aws_iam_role_policy_attachment" "fam_util_ec2_ssm_policy" {
  role       = aws_iam_role.fam_util_ec2_instance_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}
``` 
The created instance is always given with additional policies afterward. Cross verifying with the aws console created instance, the policies are identical from the default role `"EC2-Default-SSM-AD-Role"` by the platform.

Confirmed with Rocket Chat #aws-how-to from Warren `"The ASEA automatically adds that to all instance profiles so that you can connect to EC2 instances using SSM."`.
So it looks like using aws_iam_role_policy_attachment to reduce permission is redundant.

**Comment by ianliuwk1019** [comment]
For the improvement highlighted from Basil's finding from SecurityHub:
```
EC2.8 EC2 instances should use Instance Metadata Service Version 2 (IMDSv2) - This control checks whether your Amazon Elastic Compute Cloud (Amazon EC2) instance metadata version is configured with Instance Metadata Service Version 2 (IMDSv2). The control passes if HttpTokens is set to required for IMDSv2. The control fails if HttpTokens is set to optional.

PBMMAccel-EC2_INSTANCE_DETAILED_MONITORING_ENABLED
 ```
it can be easily added in the aws_instance as:
```
  metadata_options {
    # Enable IMDSv2 (Instance Metadata Service Version 2)
    http_tokens = "required"
  }

  monitoring = true
```

**Comment by ianliuwk1019** [comment]
Dev is verified after deployed:
* The instance is created with "stopped" status.
* Can use Session Manager to "connect" to the instance and run `psql` command to the database.
* When redeploy again, the instance goes back to "stopped" status (in case someone forgot to 'stop' the instance).
