### ISSUE TITLE
Update Ops guide to include audit functionality

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#805]
**Describe the task**
Update the [FAM Operations](https://apps.nrs.gov.bc.ca/int/confluence/x/mKa6C) guide to include pertinent information about audit logs. 

--PO note: we may decide to have a standalone audit doc and reference it from the Ops guide

**Acceptance Criteria**
- [ ] description of log format, storage location, retention, access control, 
- [ ] description of how to export audit logs to third party in a secure manner
- [ ] 

**Additional context**
- See  #561 for initial audit log implementation
- See [STRA risk item #7](https://apps.nrs.gov.bc.ca/int/confluence/x/PKa9CQ)

**Comment by MCatherine1994** [comment]
Added description for our current audit log: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/FAM+Operations

Not sure what "access control" means in the acceptance criteria, and not sure where we want to export the audit logs?

**Comment by MCatherine1994** [comment]
Found a small bug that, currently when we remove a user role assignment, the audit log shows the event type is "CREATE_USER_ROLE_ACCESS", will push a fix change it to "REMOVE_USER_ROLE_ACCESS"
