### ISSUE TITLE
Deploy sample api

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#81]
As per #74:

Deploy a sample api as described, say, from in https://www.deadbear.io/simple-serverless-fastapi-with-aws-lambda/ and be able to call it from CLI

AC:
-sample app is deployed via Terraform
-sample app is callable  from CLI

Work Plan:

- [x] Get a FastAPI example app (from the url above) and put it into /server/lambda (replacing what is there)
- [x] Figure out how to run the example app locally in python
- [x] Add a build step to pull_request.yml
- [x] Add a build step to push.yml
- [ ] Figure out how to run tests (?) >>breakout to separate ticket
- [x] Add a terraform file to /server that deploys the build as a lambda function
- [x] Use the AWS admin console to execute the lambda function to verify that it works.

**Comment by gormless87** [comment]
Deploy lambda via Terraform requires Admin access

**Comment by explorertolu** [comment]
@ArogeG and @gormless87 I still don't have the admin access in AWS. I am getting "aws_iam_role.fam_api_v1_lambda_exec will be created" but was not created.

**Comment by fadekemiatitebi** [comment]
@explorertolu  I have sent another reminder and added Julian to the chat. Are you able to work on something else while we await your access elevation request?

**Comment by explorertolu** [comment]
@ArogeG Sure, thanks!

**Comment by explorertolu** [comment]
Thanks @ArogeG, my admin access is now working.
@gormless87

**Comment by explorertolu** [comment]
@gormless87 I have completed the work except for the testing that we need to breakout in a separate ticket.
