### ISSUE TITLE
Investigate:  Frontend - Build Message: scss didn't resolve at build time

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#813]
**Describe the bug**
This is an observation found for frontend build.
Not sure since when (and why) there are such messages (multiple lines)
```
vite v4.3.9 building for production...
transforming...

../assets/font/BCSans-Regular.woff referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
```
from frontend build, and is it normal or is there implication that we should concern with. Didn't see them previously.

**To Reproduce**
This can be observed locally or at pipeline.
* Go to "frontend" directory.
* Do `npm run build` to build production package.
* Observe terminal message during build.
* Will see these:
```
> vite build

vite v4.3.9 building for production...
transforming...

../assets/font/BCSans-Regular.woff referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-Italic.woff referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-Bold.woff referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-BoldItalic.woff referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-Regular.woff2 referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-Italic.woff2 referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-Bold.woff2 referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime

../assets/font/BCSans-BoldItalic.woff2 referenced in /home/runner/work/nr-forests-access-management/nr-forests-access-management/frontend/src/components/Landing.vue?vue&type=style&index=0&scoped=976083d0&lang.scss didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 10413 modules transformed.
```

**Expected behavior**
Not sure if this is normal to see these messages. Please investigate why **.scss didn't resolve at build time** and if that's a bug.

**Additional context**

**Comment by ianliuwk1019** [comment]
I think I probably found the root cause of this.
Our frontend Vite compiler does not know how to resolve "Fonts" from third lib with "nr-fsa-theme" repo using (../assets/font) relative path. So Vite would leave these at run time.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e69064af0d77a52a10eb7fbf612ceebc4046579e/image.png)

Jota does have a pr open for the fix of this issue in our FAM repo, but my thought is this is just an alternative solution and not an ultimate solution. Also this fix could probably lead to future problem.

However, I am not too deep on understanding SCSS functions that much so wondering if solution can be more than one. For example, maybe the best solution is ultimately fixed at "nr-fsa-theme" repo, I wonder our FAM using map.get is a suitable function in this case or maybe there is alternative (since map.get() function probably did not interpret the path and just give exactly as is as "../assets"):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTgvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b0f88572f09b8fad04ba78b213fac8ef4f9dd57/image.png)
  
@MCatherine1994

**Comment by MCatherine1994** [comment]
I took a deep look into this issue. And I think the error was not from our FAM repo. The problem is from this "body-type" import inside the landing page stylesheet in the common repo. Previously we were having the similar font path issue, so we decided to do all font changes locally in FAM (in our frontend/src/assets/styles/styles.scss file). But we forgot to clean the import here, this body-type import actually is not in use. If we could remove it from the common repo, we won't have any error on our side any more.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--33c6149894c8464fe974f8676c5cf13cc97a9bf5/image.png)

**Comment by ianliuwk1019** [comment]
This is additional but maybe also direct related.
Relative path is always better (in most cases) but seeing this **'../'** still makes me wondering.... perhaps scss does allow your to referencing sibling folders when your "load path" is configured (maybe already is by default).
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1ZGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db2e1e1519c9d993914a581be0b18c9da3f92448/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2hGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--37bd71058b18a03f2d681ac24a93240f670cf2e7/image.png)

 So if possible, better not to use **"../"** to reference relative path.

The challenging one maybe this one on "src" attribute; and using "url" seems to be referencing to external, not internal project structure (according to documentation)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFJGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eecd6b9165618ddf79ebbbbb2de7a6ef47311847/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1eddfbb79db72307a134ef817a3e4f6b8ae99666/image.png)
