### ISSUE TITLE
Frontend - Pipeline Build and Deploy Slow Down Significantly

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#814]
**Describe the bug**
This is an observation in pipeline and also can be seen in locally.
After probably task #704 (switch to carbon icons) was merged to main, frontend build and deployment slow down significantly.
From normally **2~ 3 minutes** to now can be observed between **13~20 minutes** (normal Github action slowness probably isn't the main factor at this issue).

Observation also includes:
- The frontend production build (locally and at pipeline) produces lots of import-artifacts at "dist/assets" folder (more than **7000** small files).
- During frontend deployment, these small files are contributing to the large amount of AWS bucket creation and large increase of transfer time to AWS buckets.

Possible reason:
- It is very likely due to the frontend Icon.vue component is using "**dynamic import**" for Carbon Icons.
  [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck1qIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b6de1b07d5c5ab3c6249fedf135a3377482a1dfa/image.png)
   "**Vite**" probably does not know how to resolve this (and thus include everything ?? no tree shaking?? Just a guessing).
   The intention having one component to dynamically loading icon was good but maybe it isn't the scenario to fit in this case for loading icons.

Root cause and solution are not immediately clear yet but need to be investigated for possible mitigations .
- Can "Vite" have build option to optimize this dynamic icon imports issue, plus a way for icons packing into a small bundle?
- Is it possible to still have "Icon.vue" but not using dynamic imports for icon to resolve the problem (so limit this issue within Icon.vue and no impact for other codes)?
- Don't use dynamic imports for icons for this case (basically partially re-do #704)?
- Other options?

**To Reproduce**
Please observer past pipeline run mentioned at "Additional context":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmtqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d1f15cddec152d312f7400899f17ccebf7bca2c9/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm9qIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da56c2e54cf6319c62a886711351fc246409abf1/image.png)

Locally:
1. Go to "frontend" folder (main branch).
2. Do "npm run build".
3. Observe terminal build message output.
4. Also Observe produced ".**/frontend/dist/assets**" folder.
5. Do a quick `ls | wc -l` bash line count, will show:
    [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjBqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d9ca5c5538f7db6097acd2971977786f5287bc59/image.png)

**Additional context**
We can compare the time ran between these two DEV deployments:
- https://github.com/bcgov/nr-forests-access-management/actions/runs/5907237754
- https://github.com/bcgov/nr-forests-access-management/actions/runs/5931271453

**Comment by gormless87** [comment]
Figma clues:  https://forum.figma.com/t/every-icon-best-practice-you-need-to-know/6445

**Comment by ianliuwk1019** [comment]
Just for a reference here.
The dynamic import can be bundled with this option with **vite's rollout option** ("**inlineDynamicImports**"):
        build: {
            chunkSizeWarningLimit: 1600,
            outDir: "dist",
            sourcemap: true,
            rollupOptions: {
                output: {
                  inlineDynamicImports: true,
                },
            }
        },
Tried it out, seems to be good.
However, it seems to be conflict with other vite's plugin for the manulChunk setup.
Since the code fix to specific import the icons (still it is a dynamic imports) we need can resolve much of this issue, so will just keep this option as reference for now (if issue come up again in future).
