### ISSUE TITLE
When self-granting error happens, app should stay on summary page

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#825]
**Describe the bug**
The behavior seems to be changed after DEV deployment from latest.
When self-granting a role, on summary page, when clicking submit, the error popup but user is being redirect back to Dashboard page. This isn't the behavior desired.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEU5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89b58f29888b870e26cf5024db38d7dc1f7874cc/image.png)

**Additional context**
- Although it is happening on self-granting, but in general, when business error happens, should allow user to stay on the page to verify what the user need to change. Please verify 403 error handling and route changing on page/component.

**Comment by gormless87** [comment]
Looks good, works as expected.

**Comment by gormless87** [comment]
Looks good, works as expected.
