### ISSUE TITLE
Expose FAM API via AWS api gateway via Terraform

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#83]
As per #74:

When I hit a public URL for the FAM API, the API returns a response to my computer.
expose API via Api gateway via terraform

AC:
-can make all test calls via postman/curl
-API gateway configuration should be deployed via Terraform. 
-Ticket scope is limited to a gateway on AWS. FAM code will use the AWS API gateway being used by the Sample API

**Comment by explorertolu** [comment]
The sample FAM API has been exposed via API Gateway.
URL to API Gateway (root proxy): https://ozcz02heki.execute-api.ca-central-1.amazonaws.com/dev/
GET USERS endpoint: https://ozcz02heki.execute-api.ca-central-1.amazonaws.com/dev/api/v1/users/

**Comment by ArogeG** [comment]
This has already been done via the AWS console but now needs to be done via Terraform.

**Comment by ArogeG** [comment]
Ticket needs to be refined with added Acceptance Criteria. @ConradBoydElliottGustafson @franTarkenton @basilv to discuss more technical requirement.
