### ISSUE TITLE
Frontend: Create Breadcrumb component

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#842]
**Describe the task**
Create Breadcrumb component according to the design system.

**Acceptance Criteria**
- [x] Breadcrumb component exists and is available to all pages except Manage Permissions page
- [x] Breadcrumb component stylized as per the design system
- [x] Breadcrumb links redirect to the correct pages

**Additional context**
Figma design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-108689&mode=design&t=YKuzKiz3MHGyGKLU-0[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczFzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a489b26a83311105826919d0b294f76305d8370/Capture-user%20access3.PNG)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEJzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--466e71eefd6cfdf5df44a2784aa576129c322b76/Capture-user%20access3.PNG)

**Comment by NickSaglioni** [comment]
The current backend API implementation only accepts one client ID per request, so there are two possible solutions for submitting multiple client IDs:

1. The backend API is adjusted to accept multiple IDs per request or a new separated API is created to allow this;
2. The frontend can loop through all the items in the client ID list and send one request per client ID through the current backend API;

After discussion, we have decided for now to proceed with the option 2. To accomplish that, the complexity of task has increased, because the frontend would have to handle the multiple API requests, including handling errors and it would also require adjustments on the notification component to display the IDs that were successfully added to one user and another one to display the IDs that were not added. As further discussed with the UX team, there would be also an warning notification for some special cases (trying to add an association that already exists, for instance), so this task should include this design below for the notification messages:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--281fb66a6d3d93b7a20db02a8ca05275c21937ca/Screenshot%202023-10-06%20at%2013.27.47.png)

**Comment by gormless87** [comment]
Looks good
