### ISSUE TITLE
Frontend: Create Progress Bar (stepping) component

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#843]
**Describe the task**
Create Progress Bar (stepping) component according to the design system;

**Acceptance Criteria**
- [ ] Progress Bar component exists and is displayed in the `Add new user` page
- [ ] Progress Bar component is stylized as per the design system
- [ ] Progress Bar component updates itself and indicates which step the user currently is

**Additional context**
Figma Design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-108689&mode=design&t=YKuzKiz3MHGyGKLU-0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXhzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a573bcd75c785d71e882b3b326dedb14a2b9498e/image.png)

**Comment by MCatherine1994** [comment]
user id changes: 
- cleanup the user role step (step 2)
- cleanup the org info step (step 3)

verifyIdentity (verify idir user):
- mark step 1 as complete

when we do role selection:
- mark step 2 as complete 
- check if need to show the step 3 based on role type

enter forest client input:
- change step3 icon

verify forest client:
- if there is a successful one, mark step3 as completed

**Comment by J0taFerreira** [comment]
The Developers spoke with the PO, and the conclusion was that at this time there is no need to implement the progress bar component.
