### ISSUE TITLE
Frontend: Adjust Grant Access User page

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#844]
**Describe the task**
Adjust existing components for the Grant Access User page (inputs, buttons, paddings, etc) to the improved design.

**Acceptance Criteria**
- [ ] Components are stylized and work as per the design system

**Additional context**
Figma Design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-108689&mode=design&t=YKuzKiz3MHGyGKLU-0

**Comment by gormless87** [comment]
@MCatherine1994 - looks OK to me.
