### ISSUE TITLE
Frontend: Adjust user information card

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#846]
**Describe the task**
Adjust user information card as per the improved design.

**Acceptance Criteria**
- [x] The user information card displays the information according to the improved design

**Additional context**
Figma Design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-108689&mode=design&t=YKuzKiz3MHGyGKLU-0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckpzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a75b74a9ac02db0b19f33d0e33ceaa0af43ebc76/Capture-user%20access.PNG)

**Comment by ianliuwk1019** [comment]
This ticket is loosely depends on ticket: https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-fam-idim-lookup-proxy/40
