### ISSUE TITLE
Frontend: Adjust Forest Client information card

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#847]
**Describe the task**
Adjust Forest Client information card as per the improved design.

**Acceptance Criteria**
- [x] The Forest Client information card card displays the information according to the improved design
- [x] The Forest Client card must allow multiple values and display correctly

**Additional context**
Figma Design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-108689&mode=design&t=YKuzKiz3MHGyGKLU-0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1JzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68976268f92de74dcd3834266f045d165920a105/Capture-user%20access2.PNG)

**Comment by J0taFerreira** [comment]
User will no longer be able to add an inactive client. The inactive error will be handle in the input.

The functionality to allow multiple values to be displayed is dependent on task #853
https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/853
