### ISSUE TITLE
Frontend: Adjust styling in Manage Permissions page (previously dashboard page)

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#849]
**Describe the task**
Adjust styling for the Manage Permissions page (previously dashboard page) per improved design.

**Acceptance Criteria**
- [x] Update referentes and naming from dashboard to manage permissions
- [x] Adjust table style
- [x] Adjust dropdown style
- [x] Display an icon and text according to the improved design when no application is selected, like the picture below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1JhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e7ea0955a8d9b4d050c26898b658f4dfa3ba49ae/Screenshot%202023-08-31%20at%2013.46.41.png)

**Additional context**
Figma Design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-102878&mode=design&t=V8XSihxV8ArvRHmU-0

**Comment by ianliuwk1019** [comment]
When looking at PR (#890) for this ticket, the design for the user-role table shows these columns with no data (see highlight in red):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEN0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--50396208199def8023f32029b4ddb2e71b56404d/image.png)

These information (in **red**: "First name", "Last name", "Email") my understanding is from IDIM external search. Have we discussed and know in what strategy for how we obtain this information for the frontend (fetching externally for each user, caching, combinations, or else)?
We should have backend ready before showing these columns I think?
@OlgaLiber2 , @basilv  , @MCatherine1994

**Comment by OlgaLiber2** [comment]
I think @MCatherine1994 will know what we are missing on the backend to be able to display this information.

**Comment by ianliuwk1019** [comment]
I see the Figma design has lower case for ("**User name**", "**First name**", "**Last name**"). I see more common for using **U**pper case for the column header (all words: "**U**ser **N**ame", "**F**irst **N**ame", "**L**ast **N**ame"), should we use that?
@OlgaLiber2

**Comment by ianliuwk1019** [comment]
Hi @J0taFerreira ,
As discussed in meeting, could you please remove/hide the columns ("First name", "Last name", "Email") for now and adjust column headers for **U**pper **C**ase?
Thank you.
