### ISSUE TITLE
Frontend: Adjust Forest Client number input for multiple values

### ISSUE THREAD

**Issue by NickSaglioni** [bcgov/nr-forests-access-management#853]
**Describe the task**
Allow the Forest Client number input for multiple values and add to the forest client card.

**Acceptance Criteria**
- [x] The forest client number input accepts multiple values
- [x] The forest client card shows the added values
- [x] The `submit application` button is only enabled when there are only active forest client numbers
- [x] Display error message through the field input validation when trying to add an invalid or inactive forest client number

**Additional context**
Figma design: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1773-109273&mode=design&t=maQZcd3NsABNp8hp-0

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDV0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2b643d0d7cafd1b8e120e9c03b96969180873a10/Capture-user%20access2.PNG)

**Comment by NickSaglioni** [comment]
There has been some changes in the design for this task, the inactive items should display an error message through the input form validation and not be added to the list of numbers of the Forest Client Card.

**Comment by MCatherine1994** [comment]
Hi @NickSaglioni, please merge the latest from main and improve the style from there, thanks!!

**Comment by NickSaglioni** [comment]
The current backend API implementation only accepts one client ID per request, so there are two possible solutions for submitting multiple client IDs:

1. The backend API is adjusted to accept multiple IDs per request or a new separated API is created to allow this;
2. The frontend can loop through all the items in the client ID list and send one request per client ID through the current backend API;

After discussion, we have decided for now to proceed with the option 2. To accomplish that, the complexity of task has increased, because the frontend would have to handle the multiple API requests, including handling errors and it would also require adjustments on the notification component to display the IDs that were successfully added to one user and another one to display the IDs that were not added. As further discussed with the UX team, there would be also an warning notification for some special cases (trying to add an association that already exists, for instance), so this task should include this design below for the notification messages:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--281fb66a6d3d93b7a20db02a8ca05275c21937ca/Screenshot%202023-10-06%20at%2013.27.47.png)
