### ISSUE TITLE
Integrate code coverage outcomes with the pipeline

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#87]
- [x] Sonar monorepo setup for all 3 components
- [x] Auth function code is reported to SonarCloud for PR and push to main
- [x] API code is reported to SonarCloud for PR and push to main
- [x] Frontend code is reported to SonarCloud for PR and push to main
- [x] Be able to review the code coverage on sonar for all three projects
- [x] No code coverage reporting for test code
- [x] Publish code coverage as github comment for tests (fail the build if test coverage is below threshold of 80%)
- [x] push to Sonar Cloud to make results easier to deal with

**Comment by DerekRoberts** [comment]
Two PRs for Auth Function.  Please expect more for the other two components.
https://github.com/bcgov/nr-forests-access-management/pull/664
https://github.com/bcgov/nr-forests-access-management/pull/666

**Comment by DerekRoberts** [comment]
One more PR for backend and frontend.
https://github.com/bcgov/nr-forests-access-management/pull/668

**Comment by ConradBoydElliottGustafson** [comment]
Found a few problems and sent back to "in progress". @DerekRoberts and I are troubleshooting over Discord.

**Comment by DerekRoberts** [comment]
Yup, @ConradBoydElliottGustafson is right.  Next PR!
https://github.com/bcgov/nr-forests-access-management/pull/669
