### ISSUE TITLE
Document (and improve) secure design and development process

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#879]
Line 21/22 of the security assessment identify the need for a well-documented "secure design and development process". In discussing with Chris, he agrees that the target for this could be the following:

1. Document the current process. How do features go from user interviews to production release features? What are the steps in between? Code reviews, static code analyis, automated tests, coding standards, linting, etc. What's our release process and how do we prevent mistakes or hacking? How do we use definition of ready and/or definition of done to make sure that we are all following the practices? Etc.
2. Work together as a team to identify any holes in the process and patch them up. Get Chris' feedback.
3. Implement a review process to continuously evaluate and improve the process itself. This could be as simple as a standing item during our retrospective meeting.

**Comment by OlgaLiber2** [comment]
get A/C list during refinement
