### ISSUE TITLE
Create user management Lambda infrastructure

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#884]
For security purposes, we need to create a new user management lambda function that can handle API requests for user management.

Using Terraform create the infrastructure necessary to start implementing features.

- [x] Add a new section to the /server directory in the repo. Build a new FastAPI web service with a simple GET request (for testing)
- [x] Update the GitHub actions to build and deploy the new Lambda function
- [x] Add a new random password and put it in an AWS Secret (see the existing Lambda for a pattern)
- [x] Copy and paste the data model we updated in ticket #1007 from backend/server folder and put it in the new directory
- [x] Make the new database user accessible through the RDS proxy
- [x] Copy and paste the smoke test router over and what is needed, and make sure the smoke test router works (for testing
- [x] Secure the method, requiring the FAM_ADMIN privilege (continue current pattern and check the role of the user)
- [x] Add a few simple tests, making sure they get called from GitHub actions
- [x] Add the SONAR sub-project to monitor the code and code coverage, created a follow up ticket for this #1037

Duplicate code is fine for this ticket, and we'll do the cleanup later. For now we'll just copy and update the api lambda.

**Comment by MCatherine1994** [comment]
Derek helped me submit a request to OCIO for a new SONAR project, https://github.com/BCDevOps/devops-requests/issues/1576

Next time we should follow the step to submit the request by ourselves:
1.https://github.com/BCDevOps/devops-requests
2.Issues
3.New Issue
4.Request for import GitHub repository on SonarCloud
5.Mention the monorepo name
6.Mention the project name
7.New Code Definition: Previous version
8.Submit New Issue
