### ISSUE TITLE
Add application admin endpoints to user management API

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#885]
FAM needs a mechanism to create and delete application administrator records. 

- [x] Create a POST endpoint that allows the creation of a new record in fam_app_admin
- [x] Create a DELETE endpoint that allows the deletion of an existing record in fam_app_admin
- [ ] Create a GET endpoint that gets the list of application admin records for a user (won't add this one as it won't be use for now)
- [x] Create a GET endpoint that gets a list of admin users for an application
- [x] Make sure that all the endpoints require the FAM_ADMIN role (either by inspecting the JWT or by querying the database)
- [x] Make sure that the user can't manage their own records
- [x] Make sure that POST and DELETE actions are audited similar to the current role POST and DELETE actions
- [x] Test locally 

Additional Note:
- When there is a python schema added with using Pydantic for typing and validations, the package `pydantic`, `pydantic-core` will need to be added to fix the version of them or will have strange issue when FastAPI bump its internal version.
- Not sure about these two packages `cryptography` and `psycopg2-binary`, watch out for the pipeline scan; one of both of them are from the vulnerability fix in the past.

**Comment by MCatherine1994** [comment]
Ian reminds me that if we want to discuss a little bit about the code structure. I'll provide an example to use "repository/service/router" pattern, vs "crud/router", and then we can discuss in our team.

**Comment by ianliuwk1019** [comment]
I think this acceptance criteria `Make sure that all the endpoints require the FAM_ADMIN role (either by inspecting the JWT or by querying the database)` should be "Make sure that all the endpoints require the **{application}_ADMIN** role ....".
So the router(endpoint) should check if the "user" (from the JWT token) who access to the endpoint does indeed exist records in `fam_application_admin` table for appropriate **{application}_admin** access against what roles are present in JWT token from the endpoint.

**Comment by MCatherine1994** [comment]
Hi Ian, yes, you're right, but I think for now, we only target on the FAM application admin. Later on once we manage access for other applications, we'll add the check for "{application}_admin". For the current fam_application_admin table, only FAM admin can have access to.

**Comment by MCatherine1994** [comment]
um.... I rethink about Ian's comment, I wonder so for now, only FAM admin can grant application admin access, for example (FOM_DEV_ADMIN etc.). But do we allow FOM_DEV_ADMIN to grant another user the FOM_DEV_ADMIN? 

@ianliuwk1019 @basilv @OlgaLiber2 @gormless87

**Comment by basilv** [comment]
> um.... I rethink about Ian's comment, I wonder so for now, only FAM admin can grant application admin access, for example (FOM_DEV_ADMIN etc.). But do we allow FOM_DEV_ADMIN to grant another user the FOM_DEV_ADMIN?
> 
> @ianliuwk1019 @basilv @OlgaLiber2 @gormless87

No, FOM_DEV Admin means you can grant access to FOM functionality (in DEV env).
The ability to administer FOM or any other app is a FAM capability, its a higher privilege function with potentially different workflow to approve.

**Comment by OlgaLiber2** [comment]
@MCatherine1994 for now we are keeping the scope to only FAM admin able to give the application admin role. So an application admin cannot give the application admin role to another person.

**Comment by MCatherine1994** [comment]
Thanks @OlgaLiber2 and @basilv ! got it

**Comment by MCatherine1994** [comment]
Thanks @OlgaLiber2 and @basilv ! got it
