### ISSUE TITLE
Design application admin management UI

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#886]
The goal is to stop using the fam_role table for application admin management. In order to do this, we need to create a user interface that will be used by the FAM administrator to manage the list of application administrators.

The data model is very simple. We're just matching up users and applications. FAM is an application as well.

Acceptance Criteria:

- [ ] Figma design for the new user interface and how it fits into the existing overall FAM console UI

Additional context:
- screens for: 
- FAM admin -> can assign application admin + assign FAM admins (FAM admin=super admin)
- application admin

**Comment by OlgaLiber2** [comment]
@MCatherine1994 can we close this ticket? do you have the info you need to implement this?

**Comment by MCatherine1994** [comment]
I think we are good on this one.
