### ISSUE TITLE
Implement application admin management UI - manage permission UI

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#887]
**Describe the task**
We need a cool new screen to manage application admins! Implement the awesome design in #886 for manage permission UI, design in [Figma](https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=3637-204243&mode=design&t=a9nlm8GzUvGPUPz9-0) 
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69aedd31e8a21c66688a9545a85ca89fe405948d/Screen%20Shot%202023-11-28%20at%2011.26.20%20AM.png)

**Acceptance Criteria**
 - [x] In `ManagePermissions.vue` component, when the user select "FAM" from the dropdown, load the application admins using the new admin management api
- [x] Create a new ApplicationAdminTable component, and whenever the user select "FAM" from the dropdown, display the new ApplicationAdminTable component with the application admin data
- [x] The new ApplicationAdminTable component will display the columns as in the Figma design (username, domain, application, environment, role, action). And we don't need to read role from database, just display "admin" for all the users. The application column we just show the application name, and we display the application environment in the environment column.

**Comment by OlgaLiber2** [comment]
@ConradBoydElliottGustafson  I'm assuming a new screen to manage app admins + screen/s for granting access to a new app admin. Correct?

**Comment by ConradBoydElliottGustafson** [comment]
Correct! Currently they are roles in FAM. The point of segregating is to remove those definitions from that table, so that someone can't hack the Lambda and give themselves FAM ADMIN. 

So yes, we need a simple new screen that lets the FAM admin grant app admin to users.

**Comment by ConradBoydElliottGustafson** [comment]
I made a ticket #886 for a UI design task.

**Comment by MCatherine1994** [comment]
We don't do the estimate now until the UI is ready so we'll have a better understanding.

**Comment by OlgaLiber2** [comment]
@OlgaLiber2 update mockup with added columns

**Comment by gormless87** [comment]
Closed 3 weeks ago in Project, but issue still showed it as open
