### ISSUE TITLE
Refactor auth lambda to read FAM roles from new table

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-forests-access-management#888]
Auth lambda currently reads from the fam_user_role_xref table. For FAM privileges, we want it to also read from fam_app_admin. Keep the authorization mechanism tied to the JWT so we don't have to refactor the whole API and frontend.

- [x] Add logic in the auth lambda. When the application being logged into is FAM itself, instead of reading from fam_user_role_xref, read from fam_app_admin. If the user has a record for the FAM application, add "FAM_ADMIN" to the JWT. If it is a different application, add "{app_name}_ADMIN". 
- [x] Create a Flyway script to migrate existing FAM role data from fam_user_role_xref, to fam_app_admin. 
- [ ] Remove the FAM roles from fam_user_role_xref, this will be done in another ticket #1066

**Comment by MCatherine1994** [comment]
Do this last.

**Comment by MCatherine1994** [comment]
The 1st and 2nd task is not blocked anymore. But the last cleanup task need to wait until frontend implementation is done, so frontend will read data from the new table, and then it will be safe to remove old roles.

**Comment by MCatherine1994** [comment]
Tested in AWS dev, application admins have been added successfully. But the login doesn't work anymore, cause we forgot to add the read permission for auth lambda db user to the new fam_application_admin table, I opened a new pr for the fix https://github.com/bcgov/nr-forests-access-management/pull/1074

<img width="1269" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7466667dd982f70c8a1d1e411221b06a3c77d5a9/AWS_dev_1207.png" alt="AWS_dev_1207.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fa7d665abb86973d3a3574adf96887434c295b6/AWS_dev%29app_admin.png" alt="AWS_dev)app_admin.png" />
