### ISSUE TITLE
Frontend minor adjustment

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#897]
**Description**
Some small frontend adjustment make the UI looks better

**Acceptance Criteria**
- [x] Check and update the font size on the manage permission page to match the design, for example the font size of the menu bar is 12, but it's 14 in the UI mockup

  <br />

- [x] Confirm with @OlgaLiber2 and Alison, if this "Add user permission" button looks too large? And its border-radius will show some tiny space around, do we want to get rid of the border-radius for this button? 
Update: keep the button size, remove the border-radius for this specific button
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2UzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--260719b5f58d2e0fdc490cf77d52b6d0f1a59b94/Screen%20Shot%202023-09-19%20at%204.44.20%20PM.png)

    <br />

- [x] Confirm with @OlgaLiber2 and Alison, if the height of the table header is too much? maybe we can reduce the height a bit?
Update: no need to change the header height
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0czIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--832e50c64ad0abe465974088c8a1fcf03a8aecc7/Screen%20Shot%202023-09-19%20at%204.42.39%20PM.png)
    <br />

- [x] The search input has a tiny space below (maybe no need to adjust this if we reduce the "Add user permission" button size)
Update: solved in Jota's pr #913
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1czIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fd7c6014ded634f2a25b672537aa1bdd4411340/Screen%20Shot%202023-09-19%20at%204.43.43%20PM.png)

     <br />

- [x] When click on the "Add user permission" button, the border effect doesn't look right
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBciszIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--32feab908bdb78060719b065c80babfcc1e2c219/image.png)

**Comment by OlgaLiber2** [comment]
@MCatherine1994 on your first point about the font size, we are using the "body-compact-01" style. It's is 14px. Please cross reference with the design system and make it agnostic to the component. Let me know if you need me to show you. 

"user permissions" button needs to stretch for visibility and works with the design of the table. It was user tested and we have positive feedback from on usability. I don't think the button in our designs has a border.  

Keep height of the table as it is in the Figma mockups. 

adjust the space below the search to eliminate it. 

Yes, border effect on the button needs to be removed. Can you check the button behaviour with SPAR?

**Comment by MCatherine1994** [comment]
Fix the manage permission screen table background height issue as well, when screen size is small, the background color doesn't look right

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUMvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2401222d1d905bf894b6603a2d0a9c975016e6b3/Screen%20Shot%202023-09-20%20at%206.03.44%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUcvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e7f58b62a39bdf346287a51294422060afaeedd/Screen%20Shot%202023-09-20%20at%206.03.55%20PM.png)
