### ISSUE TITLE
Secure design coding 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#905]
**Describe the task**
Draft secure design process/coding to address items from the STRA (item 21)

**Acceptance Criteria**
- [ ] a walkthrough with the team https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=171774997
- [x] reviewed by Pete
- [x] document our current process

**Additional context**
- document our current process, and have a quick conversation about it (is it acceptable, do we need to add more details?)
- C/I item
- need to be able to share with new team members and with the rest of the organization
- include link to the new draft
- when this ticket is done create a new ticket to review content with Chris

**Comment by ConradBoydElliottGustafson** [comment]
@gormless87 Please have a look at this and see if it's ready for a team review. I think a round of comments might be easier than a full meeting walkthrough, but I'll go with whatever. I'm sure there's stuff missing, but a draft today is better than a perfect document down the line.

**Comment by gormless87** [comment]
Created #928 to capture external review by Chris Prince

**Comment by ConradBoydElliottGustafson** [comment]
Comments resolved. Closing. Ready for "Chris" review.
