### ISSUE TITLE
Information security management practices, includes secret rotation playbook

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#906]
**Describe the task**
Document procedures related to FAM

**Acceptance Criteria**
- [x] reviewed by Pete
- [x] walkthrough with our team

**Additional context**
- document will capture operational security 
- content is updated on our confluence page: https://apps.nrs.gov.bc.ca/int/confluence/x/RxE9Cg

**Comment by gormless87** [comment]
Walkthrough tentatively set for Sept 06 internal demo
