### ISSUE TITLE
Action Required: Shift Terraform remote state files over to AWS S3 and DynamoDB.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#915]
**Describe the task**
Saw this on RocketChat #aws-how-to. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExBIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18d4c779437deb9c9da5e8fe391a896c15559a3b/image.png)

Original Message:
```
@here Hello Cloud Pathfinder Community,

We’ve got a quick update and some recommended actions for you.

*What is happening?*

We're suggesting that everyone using Terraform Cloud on AWS should shift their Terraform remote state files over to AWS S3 and DynamoDB.

*Why the change?*

HashiCorp has informed us of a notable price hike for Terraform Cloud come 2024. In light of this, central funding will become challenging. However, AWS offers excellent alternatives that we believe will align well with our needs and optimize our cloud expenses.

*How to make the switch?*

Here's a [simple guide](https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/blob/main/docs/tfc_to_s3_migration.md) to move your Terraform state from Terraform Cloud to AWS S3:

For teams using the Terraform Cloud Team Token in GitHub Actions:

- Migrate terraform state from Terraform Cloud to AWS S3 / DynamoDB
- Set up AWS Authentication in your GitHub Actions using OIDC. [Here’s how](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)

*Deadline*

We're aiming for everyone to make the move by Wednesday, 18th October 2023.
If you have any questions, please reach out via #aws-tenant-requests, #aws-how-to  or the cloud.pathdinder@gov.bc.ca email address.

Best regards,
The Cloud Pathfinder Team.
```

**Acceptance Criteria**
- [ ] deadline has been met and we are in compliance

**Additional context**
- Here's a [simple guide](https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/blob/main/docs/tfc_to_s3_migration.md) to move your Terraform state from Terraform Cloud to AWS S3:
- Set up AWS Authentication in your GitHub Actions using OIDC. Here’s [how](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)

**Comment by ianliuwk1019** [comment]
Hi @ConradBoydElliottGustafson @basilv ,
Initially I saw there are two instruction links provided at the RocketChat and thought they are all required for the terraform migration. 
But when look again, probably the one "**Set up AWS Authentication in your GitHub Actions using OIDC. Here’s** [how](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)" **is not needed** in our migration. Is it correct?

**Comment by ConradBoydElliottGustafson** [comment]
@ianliuwk1019 I haven't read the document yet in detail. 

It looks to me like they want us to manage our terraform state in S3 bucket, but continue to use Terraform Cloud for running the builds. 

In order to interact with S3, the GHActions need to connect to AWS. We currently don't do this. I think the "here's how" link is walking us through it. 

Can you elaborate on your question?

**Comment by ianliuwk1019** [comment]
Hi @ConradBoydElliottGustafson , I think I have some part of understanding missing for during our current terraform deployment from GHAction, so I have some doubt on weather we need "Set up AWS Authentication in your GitHub Actions using OIDC." step.

My doubt goes like this: If our current GHAction setup is able to run terraform and deploy resources to AWS, why do we need to change our GH setup to authenticate running terraform; can we just deal with migration to S3 first then we will improve our GHAction authentication setup?

This is what I see from our current GHAction, using secret (teamToken):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdi9TIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8dffd352e7264842a73adf7995666dedb0381a9b/image.png)

So, I was wondering, maybe it is enough to do first instruction to migrate to S3 first without needing to switching using "Set up AWS Authentication in your GitHub Actions using OIDC." step. However, maybe I am wrong due to missing understanding...

**Comment by ConradBoydElliottGustafson** [comment]
I'm looking at the instructions and I'm not sure they are correctly supporting workspaces. We have 2 workspaces for each of our environments. Are we sure that their instructions take that into account?

**Comment by ConradBoydElliottGustafson** [comment]
@ianliuwk1019 As for the OIDC setup, now that I look at it, I also don't see the reason for that change. Maybe you can ask the cloud pathfinder team?

**Comment by ianliuwk1019** [comment]
Thanks Conrad for contacting #aws-how-to with clear question.
As from what Max reply, the AWS-Github-OIDC instruction is needed.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1hVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--70f4eb3afcada71bacd4c121a55906cdb9b07961/image.png)

**Comment by ianliuwk1019** [comment]
After cloud.pathfinder clear the .lock, I finally able to follow instruction the first time to migrate state-file on to AWS from my "local". Although running  "**terragrunt plan**" encountered error, but it is likely due to my local needs some terraform variable to be set for true values.

state-file on AWS S3 bucket (tools space):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGZVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--387a250be6edcabd90da37e46e26323b606c8cd9/image.png)
Initial tools server state file uploaded: [server.json.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDdVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9805e46f01e6bb21c422606b8456c408f319c76d/server.json.txt)

Error when running "terragrunt plan" (due to I didn't know what values to provide):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWpVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9844a74e5175b02613c8e73135523d6b3440e978/image.png)

**Comment by basilv** [comment]
Ian, you can't just switch to S3 without doing the AWS permissions setup. There's only two possible states:
1. Run in Terraform cloud with its state file, which uses the Terraform cloud access to AWS
2. Run in GHA/locally with S3 state file, using 'direct' AWS OIDC access.
Can't have Terraform cloud use our state file in S3 as far as I know, and can't use the Terraform cloud AWS access if not running in Terraform cloud.

**Comment by ianliuwk1019** [comment]
Thanks @basilv ,
Yes, that's what currently I have problem with. Instruction is not quite clear (better than OpenSearch...), still trying to figure what our team need to set it up. I have added in workflow (for tools deployment to try it out) this block for authentication in my branch:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ25iIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f41dfc1f378a6f6bda6a15458005127f5639dec/image.png)

One problem field.
Initially thought this is the role (**BCGOV_[env]_Automation_Admin_Role**) I can use (in our Terragrunt hcl - it has an assume_role) for passing into the action.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFBiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f14f5e9f93fb2541e5c2f8b50cc3cf5307bc4bd9/image.png)

Then face the problem:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0hiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cba1e28b729a9eab00ac619155261708fe6ef6b8/image.png)

Apparently we will need to create a role and a policy (and according to the question/anwser from cloud.pathfinder we can't use **BCG
OV_xxx** role).

I am currently not clear the concept of the "**assume_role**" in terraform file vs the Github action. Are they need to be the same? Or do we create a new one for the GHAction for authentication only (but then what policy or policies do we need)?
@ConradBoydElliottGustafson @MCatherine1994

**Comment by ianliuwk1019** [comment]
Created an initial new role for the AWS-GHA authentication (tools space):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW5jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--675a8caa603a60b6abffd8fcaeffe2ecd7770390/image.png)

This now seems to **work!**, rerun previous failed tools deployment, it passes the "**Configure aws Credentials**" steps!
(Passing new role "FAM_GHA_ROLE" to the GH action, but I didn't change terraform provider's assume role yet).
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTNjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--90d9f1c701d38b2ff8ccc70b5538017afa01d24f/image.png)

However, it failed during terragrunt plan step, with two required variables (**injected values**) not set.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7fe46d6f2995cfe9149b4a3c068fbed016445346/image.png)

Looks like these two variables ("**target_aws_account_id**", "**target_env**") were injected from ASEA Terraform Cloud. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9181457b7eacb1176fe36d9ebe1882126e330212/image.png)

These two variables are being used (and the target_env are used in multiple .tf files) initially at provider's assume_role. But now we don't have these values from Terraform Cloud anymore... I am thinking we probably need to modify it to code this exact value from AWS arn in github environment secret now...
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBai9jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--38aae7364e6e1a287c425289dd7d40845de405ef/image.png)
@basilv @ConradBoydElliottGustafson

**Comment by ianliuwk1019** [comment]
Add more detail about the new role used at GHA.

To have GHA authenticated/authorized with AWS OIDC, using GH action `aws-actions/configure-aws-credentials@v4`, our current terraform deployment cannot continue use previous role **`BCGOV_tools_Automation_Admin_Role`** and a new role is created **`FAM_GHA_ROLE`**.
This role needs to be created in each AWS environment (tools/dev/test/prod). The detail:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDcyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e9bb3a45ea10dbf390fcc8e41efead2da167296/image.png)
For "Trust relationship":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVAyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01555e472cbdb7f620a16ca1cc3b4c7dd3e32901/image.png)

This new role is used in action `aws-actions/configure-aws-credentials@v4`:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW4yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6982ceeafd8083f1f519612308dc772f46352238/image.png)

With its arn value being set at GitHub repo "environment variables":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckgyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--29ee003934ebae3b7ee5856bf870d9627af28bb3/image.png)

And the workflow will need this "permission":
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmoyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8504a3880993b8150802776ca1452f3667710bf2/image.png)

Finally we can remove previous terraform provider's `assume_role`:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnYyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f3759647a073b4ef1d831d9bca5fac19aa03c2d3/image.png)

**Comment by ianliuwk1019** [comment]
[TerraformCloud_to_S3_statefile_migration_instruction.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXY1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2969848802ed2936df24d00fc78a592091e554d3/TerraformCloud_to_S3_statefile_migration_instruction.docx)

**Comment by ianliuwk1019** [comment]
TFC state file now prepared onto each environments no AWS.
