### ISSUE TITLE
Submit STRA for FAM to IDIM Consulting

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#920]
As IDIM Consulting I want to understand the security risks of an app so that I can approve webservices usage

Acceptance Criteria:
MISO approved STRA submitted to IDIM Consulting

**Definition of Done**
- [x] STRA has been submitted to IDIM Consulting

**Split this issue out from #269

**Comment by basilv** [comment]
@gormless87 is this done?
