### ISSUE TITLE
API tests for FAM API -Integrate Unit Test into Pipeline

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-forests-access-management#94]
Describe the context:
Two sets of tests are required
Unit Test: Python test are required on the pipeline: Need to create appropriate tests for each API endpoint (Integrate unit test to the pipeline)

AC:
Tests run and pass in pipeline 
have tests for all endpoints

**Comment by explorertolu** [comment]
@gormless87 I was working on this but getting the following error:  ModuleNotFoundError: No module named 'app'

**Comment by ConradBoydElliottGustafson** [comment]
Tests seem to be running. Close when ready.
