### ISSUE TITLE
Add use of AWS Security Hub into monitoring procedures in Operations Guide

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#940]
**Describe the task**
- Investigate how to best leverage the AWS SecurityHub tool to monitor security findings, both for production monitoring and as part of development process
- Document procedures in Operations Guide. Will likely need a new section on Monitoring and Event Management (missed previously)
- Review existing findings as the first pass in executing the procedure and log tasks to address legitimate findings

**Acceptance Criteria**
- [x] Operations Guide updated and reviewed - see https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Security+Monitoring
- [x] Added SecurityHub review item to Security Review procedure - see https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Security+Review+Procedure
- [x] Review existing findings - done dev, tools, test, prod
- [x] Set up SecurityHub alert in each environment - done dev.   Moved this task to #983
- [x] Test SecurityHub alert - done in dev
- [x] Walk through monitoring procedure with team.
- [x] Confirm new tasks in backlog for findings.
- [x] Talk to Cloud Pathfinder team for valid findings at the org / ASEA level.

**Additional context**
- AWS GuardDuty had no findings appear, not sure if that's a configuration issue or not. AWS Security Hub did have relevant findings. - prod has GuardDuty findings, so not an issue.
- AWS Security Hub has a lot of 'noise' in the findings - e.g. items relating to ASEA, or perhaps false positives. Will need to figure out how to filter these out. - documented as part of our procedure.
- Talk to Uniewski, Warren and Wardle, Max  to get their input/insights from the cloud pathfinder side. - added as AC item
- Perhaps consider how to integrate in Check Point Infinity Portal, assuming it is out of pilot phase? - ignoring for now

**Comment by basilv** [comment]
Considerations:
- can we add SecurityHub findings to our monitoring dashboard / alerts?
- document under either InfoSec mgmt or Monitoring sections of Ops Guide
- review existing findings.

**Comment by basilv** [comment]
Don't seem to be able to show SecurityHub findings in CloudWatch dashboard without a ton of additional work.

**Comment by basilv** [comment]
Additional learning: generating sample findings in GuardDuty causes them to have "[SAMPLE]" prefix in GuardDuty, but in SecurityHub this 'SAMPLE' prefix does not show up.

Also, GuardDuty finding suppressed in SecurityHub seems to be not suppressed in GuardDuty - we're just going to use SecurityHub as the hub, ignore GuardDuty.

**Comment by gormless87** [comment]
See also #983 for adding the AWS Event Bridge alert to Terraform

**Comment by basilv** [comment]
Finished reviewing prod SecurityHub and addressing all findings in status 'new'.
