### ISSUE TITLE
Design/investigate info for "Input sanitization for string inputs to exclude special characters" ticket 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#957]
**Describe the task**
look at all the end points and analyze each one for all the parameters and design the task for each of the parameters

**Acceptance Criteria**
- [x] understand the rule for BCeID and IDIR usernames so we can put an input mask for them
- [x] understand how many input masks we have to create in test, how many fields they need to be applied to POSTs and GETs and DELETEs (all of them)
- [ ] 

**Additional context**
- ignore FAM users and FAM roles
- address ticket #365 first

**Comment by ianliuwk1019** [comment]
I can't seem to find consistent information regarding to the format of the `username`  from online or Confluence.
For example, one of the example I see is from `FSP`:
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/cf0275f3-03f5-4ad8-98a6-5507dfa46451)
(`Alpha Numeric 30`)

The most reliable doc is the developer's guide from previous idim proxy task: 
[BCeID Client - New Web Services - Developers Guide - V2.10.0 (for BCeID WS V10).docx](https://github.com/bcgov/nr-forests-access-management/files/13059134/BCeID.Client.-.New.Web.Services.-.Developers.Guide.-.V2.10.0.for.BCeID.WS.V10.docx)
However, this document mention it does not offer `CreateAccountRequest`, so there is no spec for it, 
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/097f5bbc-9fe5-4336-913f-046595579802)
but there is a search (BCeID/IDIR) through the same request base (at 6.4	BCeIDAccount section):
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/1af239b6-b39a-4e89-a4aa-e23485263949)
(`Alpha Numeric 20`)

If that's the case (`Alpha Numeric 20`) for both BCeID/IDIR (from the webservice developer's guide, search criteria), then there is not much masking we need to do I feel.

I am not sure if we really need to contact IDIM team (<IDIM.Consulting@[gov.bc.ca](http://gov.bc.ca/)>) for this matter since we only do the search.

**Comment by ianliuwk1019** [comment]
I have sent email to "**IDIM.Consulting@gov.bc.ca**" to clarify on the IDIR/BCeID username format. Hopefully can get back from them soon.

**Comment by ianliuwk1019** [comment]
For the current FAM api, there are 2 endpoints related to the `username` string type in requests and 1 endpoint related to `forest_client_number` string type in request:
```
POST: /user_role_assignment
	body:
		{
		  "user_name": "string",
		  "user_type_code": "I",
		  "role_id": 0,
		  "forest_client_number": "string"
		}
GET : /identity_search/idir
	param:
		user_id

GET	: /forest_clients/search
	param: 
		client_number
		
```
Although this ticket does not ask about `forest_client_number` but it is clear that `forest_client_number` is a 8 digit number in string format (example: `00001011`). So for the next implementation ticket, we may well just add this masking for `forest_client_number` as well.

**Comment by ianliuwk1019** [comment]
Attach email information from both **IDIM Consulting**(for BCeID) and **WAM** Team (for IDIR): 

[RE_ Question_ IDIR_BCeID “username”(userId) input field format_.zip](https://github.com/bcgov/nr-forests-access-management/files/13191950/RE_.Question_.IDIR_BCeID.username.userId.input.field.format_.zip)

BCeID:
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/5d63808b-04ce-4611-9c4f-384f362dda80)
ref: https://urldefense.com/v3/__https://bcgov.sharepoint.com/sites/CITZ-SBC_IDIM/BCeIDFG/Shared*20Documents/BCeID*20Data*20Usage*20Notes*20-*20BCeID*20fields*20and*20descriptions*202015.xlsx__;JSUlJSUlJSUlJQ!!AaIhyw!ugYY-ErBQ3Q61m3AR1Splnlwl5v9hxgJNx4EaMdaptySx7Eto0L7x6EJ039uU28s3uqSjTYqGXP7hKhH-ymif65ybMDk$

ref: :  [https://www.ibm.com/docs/en/sva/7.0.0?topic=names-characters-disallowed-microsoft-active-directory-distinguished](https://urldefense.com/v3/__https:/www.ibm.com/docs/en/sva/7.0.0?topic=names-characters-disallowed-microsoft-active-directory-distinguished__;!!AaIhyw!ugYY-ErBQ3Q61m3AR1Splnlwl5v9hxgJNx4EaMdaptySx7Eto0L7x6EJ039uU28s3uqSjTYqGXP7hKhH-ymif4zau_Xb$)

IDIR:
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/db170344-edae-49cd-b0cf-0bf5aa38244f)

Ref: [IDIR Account Naming Standards](https://urldefense.com/v3/__https://ociomysc.service-now.com/sp?id=kb_article&sys_id=46bf75942f55bd10bef2811df699b65b__;!!AaIhyw!oWB7kJpKTpJJzF7cUwXEvST0jPl93vzzQXV9B86qVm1tpCFhs5QgncSwc2cMbXPfXMPPqRDGFg3q$)

**Comment by ianliuwk1019** [comment]
For the summary from information gathered:
**IDIR** (Account Name/ID):

	Length: 3~8 (standard), technically(limit is 64 characters max).
	Alpha-Numeric: Yes.
	Allowed(Not Allowed) special characters: 
		* Special characters and accent characters (see below) are not permitted.
		* "_" is allowed.
		* "Logon names must be between 3 and 8 alpha numeric characters – Aa through Az, 0-9 or _ (underscore)"
		** All letters must be entered in CAPS. (Not applied to our app as we search through IDIM webservice.
		   
**BCeID**:

	Length: 20 (max), technically(limit is 64 characters).
	Alpha-Numeric: Yes.
	Allowed(Not Allowed) special characters:
		* Tim points to the same document we looked at for IDIM search: "any combination of letters, numbers or symbols."
		* Tim (IDIM) suggests also to look at standard **Active Directory** ones for symbols.
		  Based on what I find out and understand from Tim's provided Active Directory link,
		  These are not allowed:
		  - (`#`, a `space` at the end, `,`, `"`, `<`, `+`, `>`, `;`, `\`)
		  - For other reserved characters, such as an equal sign (=), asterisk (*), or a non-UTF-8 character, the character must be encoded in hexadecimal.

**Comment by gormless87** [comment]
@ianliuwk1019 - nice write-up, thanks. I think we can refine #945 based on your findings, so should be good to close this issue.

**Comment by basilv** [comment]
It is unclear from these comments whether an analysis of each endpoint in FAM has been done or not.

**Comment by ianliuwk1019** [comment]
Hi @basilv , none of the current endpoints [for **endpoint("idir_search")** and for **endpoint ("create_user_role_assignment")**] have the mask/validation for either IDIR or BCeID, they do however only has basic "length" restriction for the string type.
 I have indicated on previous comments for the two endpoints related to the IDIR/BCeID masking needs and the difficulty on applying the masking for the endpoints. Not sure if it isn't clear. Please see the image:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm01QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--911b519cdcabb2e95f25cc5c6cecf33c7c543cce/image.png)

**Comment by ianliuwk1019** [comment]
To sum up which endpoints needs what input sanitization for **IDIR/BCeID**, based on the IDIR/BCeID findings I suggest adding masking/validation for these endpoints:

- Endpoint **get**(**"/identity_search/idir"**):
	- Endpoint already has **max_length**=15 limit, and we can "**increase**" it to **20**.
  	  (Doc mentions typical IDIR ranging from 3~8 length, but can be extended.)
	  (The **IDIM** API search for this is limited **20**)
	  (Note: our **db** has max **100**)	
	- Apply masking **"alpha numeric characters – Aa through Az, 0-9 or _ (underscore)"**

* Endpoint **post**(**"/user_role_assignment"**):
	- post body schema object field FamUserRoleAssignmentCreate["**user_name**"] has
	  existing range of (min_length=3, max_length=**100**). We can limit it to 
	  max_length=**20** as IDIM API search limit is **20**.
	  (Note: our db has max 100)
	  
	- Due to this ["**user_name**"] stores the value for **both**
	  **IDIR** and **BCeID**, it needs to apply **two different validations** for the field based 
	  on ["user_type_code"] field.
	  - For IDIR: **"Alpha numeric characters – Aa through Az, 0-9 or _ (underscore)"**.
	  - For BCeID: **"Alpha-Numeric, and not allowed for (#, a space at the end, ,, ", <, +, >, ;, \)"**.
	  
	- I Don't know if FastAPI or Pydantic provid dynamic validation capability that can be applied based 
		on certain request field value, this case ["**user_type_code**"], it is worth taking some time 
		finding out during implementation, or using FastAPI's ("**Depends**"). That will make better code. 
		However, if it is too much then we can simply do the validation in the "**router**" (controller).

	
- Endpoint get("**/forest_clients/search**"):
	- Endpoint already has (min_length=3, max_length=**8**) and we don't need to change it.
	- Need to apply validation for: **only numeric** character is allowed. 

Hope this is clear. @basilv

**Comment by basilv** [comment]
@ianliuwk1019 The above is clear. I don't see the API endpoint(s) listed for retrieving the list of users and their access for a selected application.

**Comment by ianliuwk1019** [comment]
Hi @basilv these 3 are the only endpoints that need IDIR/BCeID (also forestClient) sanitization. I don't find any others.
Or do we have the list of endpoints from the security review that you know of?
Our other existing endpoints are based on "Id", which is a number type. Not really sure which endpoint, maybe you meant this one: get("/{application_id}/user_role_assignment") ? which is based on application_id (number).

**Comment by basilv** [comment]
Ah, that's the confusion. The scope of this isn't just endpoints with IDIR/BCeID. We want to ensure that all arguments of all endpoints are properly sanitized. The biggest gap we knew about was the IDIR/BCeID users, which is why that's listed explicitly in the ticket. We don't know if there are other gaps. E.g. the get endpoints that just accept a number are presumably fine, but we should explicitly confirm that.

**Comment by ianliuwk1019** [comment]
Hi @basilv 
Yes, I did scan all of the api endpoints with their param/body, so these are the endpoints needed for fixing. I listed 2 endpoints(having fields related to IDIR/BCeID and other string type fields) + 1 endpoint (for forest_client string type field).
Do we really need to list each one of them here? I can do that if preferred.

**Comment by basilv** [comment]
No need to list, I just wanted to confirm the whole list was checked. Thanks, I'm good now.
