### ISSUE TITLE
Frontend Test: Add tests for adding forest client number

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#970]
**Describe the task**
Add integration tests for the adding forest client number functionality in grant access page.

**Acceptance Criteria**
- [x] test the invalid user input, forest client number is invalid (length<8), will not do this one in this ticket, validation will be tested in ticket #717
- [x] test the not found user input, forest client number is not found
- [x] test the inactive user input,  forest client number is inactive
- [x] test the duplicate user input, forest client number is already added
- [x] test the successful case for single forest client number
- [x] test the successful case for multiple forest client numbers
- [x] test adding multiple forest client number with mixed of successful and error case
- [x] test the adding button in on loading while we call the api
- [x] test the delete forest client number case
- [x] test the forest client card in error case
- [x] test the forest client card in successful case
- [x] test when property change, will cleanup the errors
- [x] test information card cleanup when property change 

**Additional context**
- might need to think about how to mock the forest client api

**Comment by NickSaglioni** [comment]
I could not find a way to have the test 'adding button in on loading while we call the api' to work. It needs a change in the `mockImplementation` for the API call to have a non-blocking delay while handling the `LoadingState`. I have tried some approaches:

- setTimeout function doesn't work for testing, the delay cannot be seem;
- Using Vitest fake timers do apply the delay, but I could not verify the correct value of the `LoadingState` after the delay, so the test always fails (is fake timer running in a blocking way?).

@MCatherine1994
