### ISSUE TITLE
Ask Cloud Pathfinder for security reviewer role

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-forests-access-management#971]
**Describe the bug**
The AWS  BCGOV_WORKLOAD_readonly role doesn't give access to even view SecurityHub findings.
There is a need for either this readonly role to at least have read access to SecurityHub findings, and/or create a security reviewer role that can both view and update findings in SecurityHub.

**Comment by basilv** [comment]
Use aws-tenant-requests on rocketchat.

**Comment by basilv** [comment]
Submitted request on 2023-10-16 to #aws-tenant-requests, the response from Max "Thank you for letting us know, we're looking into some permissions changes for the roles and feedback like this is valuable. I'll take note and when we start this work we'll be sure to consider this"

**Comment by gormless87** [comment]
Just reading this again and consulting with the team, there is a role called "security Auditor" that should do what you're asking. We can try that out and if it doesn't work I'll make a ticket to change it. I think that the purpose of the role is what you're describing. As for the readonly role, there is a ticket in flight for that change.

**Comment by OlgaLiber2** [comment]
@gormless87 email sent, waiting for reply/action

**Comment by gormless87** [comment]
Response from  cloud.pathfinder@gov.bc.ca:

Basil has been granted SecurityAuditors access role in workspace – sfha4x

Thank you.
Abi

**Comment by basilv** [comment]
Confirmed that the SecurityAuditor role does allow me to view and change the status of SecurityHub findings. 
The SecurityAuditor role does not have enough access to view FAM resources (e.g. viewing lambda configuration screens is not permitted), so the read only role might be required as well for someone like Chris doing a more in-depth assessment. 
Trying to figure out how to archive GuardDuty findings (from GuardDuty), similar issues with both SecurityAuditor and Admin role...

**Comment by basilv** [comment]
Hmm, based on AWS documentation looks like GuardDuty findings can't be archived by us ( "Currently in GuardDuty users from GuardDuty member accounts can't archive findings")

**Comment by basilv** [comment]
In summary, Security Auditor role is working for the intended purpose. Should be safe to remove my admin access to prod and regrant read-only access.
