### ISSUE TITLE
Check my own permissions for App/Delegated Admin 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-forests-access-management#985]
![Capture-my-permissions](https://github.com/bcgov/nr-forests-access-management/assets/121979429/8eaad96f-f65e-4a26-9d05-20e7b87d3890)

AC:

- [x] add new router and check if need router handler
- [x] add to side nav bar
- [x] enable global table search
- [x] create new table for view own access using cached user access info
- [x] if user has no access in FAM, he can still access to this page, and we'll display a text message shows that the user has no access in FAM

Additional context:
user access sample: https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Delegated+Access+Administration+Design

**Comment by OlgaLiber2** [comment]
[Uploading... my permissions - v1.png]

**Comment by MCatherine1994** [comment]
fyi, Figma design page: https://www.figma.com/file/5BnF5T2ncoZVpSbCbj30Mr/FAM-mockups?type=design&node-id=1845-427569&mode=design&t=SJ9H0inI21b80q4n-0

**Comment by J0taFerreira** [comment]
When the user don't have any permission, should it display something like this?
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/c4fa7c09-7dce-4e08-b659-a3715659d874)

or just show a text passed to the primevue table like that?
![Image](https://github.com/bcgov/nr-forests-access-management/assets/126905995/053773e9-6349-4765-9fdd-51f8150c2c0b)

**Comment by MCatherine1994** [comment]
Hi @OlgaLiber2, I think we need a little bit more discussion, for this view my access screen, is it just for app admin or delegated admin to check their access to manage app or user?  Or it's also for general users, for example if a user has no access in FAM, but has a FOM_REVIEWER role, can this user check the access from this page?
