### ISSUE TITLE
Add miss type check for application_id in router guard

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-forests-access-management#987]
**Describe the task**
The backend router guard "authorize_by_app_id" doesn't check the type for the parameter "application_id". So when we give an invalid application_id to our router method "get_fam_application_roles", it first checks the user access through router guard. However, the router guard miss the type check, so when it tries to call the "get_application" method, a type error returns from the database level. We have to add the type check in the router guard method, so the type error can come from the router level. 

<img width="1142" alt="Screen Shot 2023-10-23 at 3 27 02 PM" src="https://github.com/bcgov/nr-forests-access-management/assets/23131735/d5c4999c-0246-4814-a33b-ba8db66c228f">

**Acceptance Criteria**
- [ ] Add "int" type to application_id parameter in the router guard "authorize_by_app_id" method
- [ ] Check if other methods also miss type check

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
In addition to type-check issue, the FastAPI/Swagger internally seems to have a bug (or being impact by this issue).
On router level, the `application_id` does have `int` type, but FastAPI/Swagger fail to render this on the Swagger page.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/be17ca1e-243f-4359-a3f1-f7e04a2adc1b)
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/1175c031-7951-4942-9fac-3182cc09b0b3)

This seems to be solved when `int` type is added to router_guards function application_id field.
