### ISSUE TITLE
Review/QA: Frontend (Dev) GrantAccess Issues.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-forests-access-management#994]
There are various defects. Tested on Dev.
Please see screenshots.

**Screenshots**
1.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/21a69482-f89a-463a-b308-9d2303e95674)
2.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/cf456948-48a5-4fc8-8a99-52ddd91e59bf)
3.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/0fb3124b-7c90-4654-aa3f-7d0e651498c9)
4.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/dba81a84-0cca-4e55-8eba-c34f1c9966e3)
5.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/91de9e3b-c529-4039-9e54-d630d5a3f4f7)

6. When the user comes back from summary page to Grant Access page, previous forest-client input list disappear.

7.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/a5989d86-2a1e-4384-b713-2f9e5088a0e0)

8.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/1fa1918b-cf86-46e1-ad04-32d12b1310bd)

9.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/db759b5c-bda2-4da5-90cd-a0f499fba0cb)

10.
![image](https://github.com/bcgov/nr-forests-access-management/assets/81595625/ed05f428-eab8-4b6f-aec2-70e118018cb9)

**Additional context**
- One input field to handle list of string values is prone to be buggy and code tends to be more complex (hard to maintain if not code it right).

**Comment by NickSaglioni** [comment]
This task has been reviewed and split into different tasks.

Items 1, 2, 5 and 8 have been grouped into task #1014.

Items 9 and 10 have been grouped into task #1015.

Items 3 and 7 have been addressed already in PR #1011.

Item 4 will be left as is for now (discussed with @OlgaLiber2 ).

Item 6 is not a case anymore because the summary page has been removed in PR #991.

@gormless87
